<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?
/**
 * @see Mage_Catalog_Block_Seo_Sitemap_
 */
?>
<?$_items = $this->getCollection();?>
<?if($_items->getSize()):?>
    <div class="content">
        <ul class="bare-list">
            <?foreach ($_items as $_item):?>
                <li><a href="<?=$this->getItemUrl($_item)?>"><?=$_item->name?></a></li>
            <?endforeach;?>
        </ul>
    </div>
<?else:?>
    <div><?=$this->__('There are no %s available.', $this->getItemsTitle());?></div>
<?endif?>
