<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="entry-edit">
    <h4 class="icon-head head-edit-form fieldset-legend"><?=$this->__("Package Information")?></h4>
    <fieldset>
        <legend><?=$this->__("Package Information")?></legend>
        <table class="" cellspacing="5">
            <tbody>
                <tr><th><?=$this->__("Name:")?></th><td><?=$this->getPkg()->getName()?></td></tr>
                <tr><th><?=$this->__("Channel:")?></th><td><?=$this->getPkg()->getChannel()?></td></tr>
                <tr><th><?=$this->__("Summary:")?></th><td><?=$this->getPkg()->getSummary()?></td></tr>
                <tr><th><?=$this->__("Description:")?></th><td><?=nl2br($this->getPkg()->getDescription())?></td></tr>
            </tbody>
        </table>
    </fieldset>

    <h4 class="icon-head head-edit-form fieldset-legend"><?=$this->__("Current Release Information")?></h4>
    <fieldset>
        <legend><?=$this->__("Current Release Information")?></legend>
        <table class="" cellspacing="5">
            <tbody>
                <tr><th><?=$this->__("Done By:")?></th><td><?=$this->getRelease()->getDoneby()?></td></tr>
                <tr><th><?=$this->__("Date:")?></th><td><?=$this->getRelease()->getReleasedate()?></td></tr>
                <tr><th><?=$this->__("Version:")?></th><td><?=$this->getPkg()->getStable()?> (<?=$this->getRelease()->getState()?>)</td></tr>
                <tr><th><?=$this->__("License:")?></th><td><?=$this->getRelease()->getLicense()?></td></tr>
                <tr><th><?=$this->__("Notes:")?></th><td><?=nl2br($this->getRelease()->getReleasenotes())?></td></tr>
            </tbody>
        </table>
    </fieldset>
</div>