<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?
/**
 * Template for block Mage_Adminhtml_Block_Catalog_Product_Helper_Form_Gallery_Content
 */
?>
<?
$_block = $this;
/* @var $_block Mage_Adminhtml_Block_Catalog_Product_Helper_Form_Gallery_Content */
?>
<div id="<?=$_block->getHtmlId()?>" >
<ul class="messages">
    <li class="notice-msg">
        <ul>
            <li>
            <?=Mage::helper('catalog')->__('Image type and information need to be specified for each store view.');?>
            </li>
        </ul>
    </li>
</ul>
<div class="grid">
<table cellspacing="0" class="data" id="<?=$_block->getHtmlId()?>_grid" width="100%">
    <col width="120"/>
    <col />
    <col width="100"/>
    <?foreach ($_block->getImageTypes() as $typeId=>$type):?>
    <col width="70" />
    <?endforeach;?>
    <col width="70"/>
    <col width="70"/>
    <thead>
        <tr class="headings">
            <th><?=Mage::helper('catalog')->__('Image')?></th>
            <th><?=Mage::helper('catalog')->__('Label')?></th>
            <th><?=Mage::helper('catalog')->__('Sort Order')?></th>
            <?foreach ($_block->getImageTypes() as $typeId=>$type):?>
            <th><?=$type['label']?></th>
            <?endforeach;?>
            <th><?=Mage::helper('catalog')->__('Exclude')?></th>
            <th><?=Mage::helper('catalog')->__('Remove')?></th>
        </tr>
    </thead>
    <tbody id="<?=$_block->getHtmlId()?>_list">
        <tr id="<?=$_block->getHtmlId()?>_template" class="template no-display">
                <td class="cell-image"><div class="place-holder" onmouseover="<?=$_block->getJsObjectName();?>.loadImage('__file__')"><span><?=Mage::helper('catalog')->__('Roll Over for preview')?></span></div><img src="" width="100" style="display:none"></td>
                <td class="cell-label"><input type="text" class="input-text" onkeyup="<?=$_block->getJsObjectName();?>.updateImage('__file__')" onchange="<?=$_block->getJsObjectName();?>.updateImage('__file__')" /></td>
                <td class="cell-position"><input type="text" class="input-text validate-number" onkeyup="<?=$_block->getJsObjectName();?>.updateImage('__file__')" onchange="<?=$_block->getJsObjectName();?>.updateImage('__file__')" /></td>
                <?foreach ($_block->getImageTypes() as $typeId=>$type):?>
                <td class="cell-<?=$typeId?> a-center"><input type="radio" name="<?=$type['field']?>" onclick="<?=$_block->getJsObjectName();?>.setProductImages('__file__')" value="__file__" /></td>
                <?endforeach;?>
                <td class="cell-disable a-center"><input type="checkbox" onclick="<?=$_block->getJsObjectName();?>.updateImage('__file__')" /></td>
                <td class="cell-remove a-center last"><input type="checkbox" onclick="<?=$_block->getJsObjectName();?>.updateImage('__file__')" /></td>
        </tr>
        <?if($_block->hasUseDefault()):?>
        <tr id="<?=$_block->getHtmlId()?>_default">
                <td><?=Mage::helper('catalog')->__('Use Default Value')?></td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <?foreach ($_block->getMediaAttributes() as $_attribute):?>
                <td class="a-center">
                <?if($_block->getElement()->canDisplayUseDefault($_attribute)):?>
                <input class="default-checkbox" type="checkbox" onclick="<?=$_block->getJsObjectName();?>.updateUseDefault()"
<?if($_block->getElement()->usedDefault($_attribute)):?>checked<?endif;?> value="<?=$_attribute->getAttributeCode()?>"/>
                <?endif?>
                </td>
                <?endforeach;?>
                <td>&nbsp;</td>
                <td class="last">&nbsp;</td>
        </tr>
    <?endif?>
        <tr id="<?=$_block->getHtmlId()?>-image-0">
                <td class="cell-image"><?=Mage::helper('catalog')->__('No image')?></td>
                <td class="cell-label"><input type="hidden">&nbsp;</td>
                <td class="cell-position"><input type="hidden">&nbsp;</td>
                <?foreach ($_block->getImageTypes() as $typeId=>$type):?>
                <td class="cell-<?=$typeId?> a-center"><input type="radio" name="<?=$type['field']?>" onclick="<?=$_block->getJsObjectName();?>.setProductImages('no_selection')" value="no_selection" checked/></td>
                <?endforeach;?>
                <td class="cell-disable"><input type="hidden">&nbsp;</td>
                <td class="cell-remove last"><input type="hidden">&nbsp;</td>
        </tr>
    </tbody>

    <tfoot>
        <tr>
            <td colspan="100" class="last" style="padding:8px">
            <?=$_block->getUploaderHtml()?>
            </td>
        </tr>
    </tfoot>
</table>
</div>
</div>
<input type="hidden" id="<?=$_block->getHtmlId()?>_save" name="<?=$_block->getElement()->getName()?>[images]" value="<?=$_block->htmlEscape($_block->getImagesJson())?>" />
<input type="hidden" id="<?=$_block->getHtmlId()?>_save_image" name="<?=$_block->getElement()->getName()?>[values]" value="<?=$_block->htmlEscape($_block->getImagesValuesJson())?>" />
<script type="text/javascript">
var <?=$_block->getJsObjectName();?> = new Product.Gallery('<?=$_block->getHtmlId()?>', <?=$_block->getUploader()->getJsObjectName()?>, <?=$_block->getImageTypesJson()?>);
</script>