<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?switch ($element->getType()){
    case 'fieldset':?>

    <h3><?=$element->getLegend()?></h3>
    <fieldset>
        <legend><?=$element->getLegend()?></legend>
        <?foreach ($element->getElements() as $_element):?>
            <?=$formBlock->drawElement($_element)?>
        <?endforeach;?>
    </fieldset>
      <?break;
    case 'column':?>
      <?break;
    case 'hidden':?>
    <input type="<?=$element->getType()?>" name="<?=$element->getName()?>" id="<?=$element->getHtmlId()?>" value="<?=$element->getValue()?>">
      <?break;
    case 'select':?>
    <span class="form_row">
        <?if($element->getLabel()):?><label for="<?=$element->getHtmlId()?>"><?=$element->getLabel()?>:</label><?endif;?>
        <select name="<?=$element->getName()?>" id="<?=$element->getHtmlId()?>" class="select<?=$element->getClass()?>" title="<?=$element->getTitle()?>">
        <?foreach ($element->getValues() as $_value):?>
            <option <?=$_value->serialize()?><?if($_value->getValue() == $element->getValue()):?> selected<?endif;?>><?=$_value->getLabel()?></option>
        <?endforeach;?>
        </select>
    </span>
      <?break;
    case 'text':
    case 'button':
    case 'password':?>
    <span class="form_row">
        <?if($element->getLabel()):?><label for="<?=$element->getHtmlId()?>"><?=$element->getLabel()?>:</label><?endif;?>
        <input type="<?=$element->getType()?>" name="<?=$element->getName()?>" id="<?=$element->getHtmlId()?>" value="<?=$element->getValue()?>" class="input-text <?=$element->getClass()?>" title="<?=$element->getTitle()?>" <?=( $element->getOnClick() ? 'onClick="'.$element->getOnClick().'"' : '' )?>/>
    </span>
      <?break;
    case 'radio':?>
    <span class="form_row">
        <?if($element->getLabel()):?><label for="<?=$element->getHtmlId()?>"><?=$element->getLabel()?>:</label><?endif;?>
        <input type="<?=$element->getType()?>" name="<?=$element->getName()?>" id="<?=$element->getHtmlId()?>" value="<?=$element->getValue()?>" class="input-text <?=$element->getClass()?>" title="<?=$element->getTitle()?>"/>
    </span>
      <?break;
    case 'hidden':?>
        <input type="<?=$element->getType()?>" name="<?=$element->getName()?>" id="<?=$element->getHtmlId()?>" value="<?=$element->getValue()?>">
      <?break;
    case 'radios':?>
    <span class="form_row">
        <label for="<?=$element->getHtmlId()?>"><?=$element->getLabel()?>:</label>
	<?foreach($element->getRadios() as $_radio):?>
	<input type="radio" name="<?=$_radio->getName()?>" id="<?=$_radio->getHtmlId()?>" value="<?=$_radio->getValue()?>" class="input-radio <?=$_radio->getClass()?>" title="<?=$_radio->getTitle()?>" <?=( $_radio->getValue() == $element->getChecked() ) ? 'checked="true"' : ''?> >&nbsp;<?=$_radio->getLabel()?>
	<?endforeach;?>
    </span>
      <?break;
	case 'wysiwyg':?>
    <span class="form_row">
	  <label for="<?=$element->getHtmlId()?>"><?=$element->getLabel()?>:</label>
		<script language="javascript" type="text/javascript" src="<?=$baseUrl?>js/tiny_mce/tiny_mce.js"></script>
		<script language="javascript" type="text/javascript">
		tinyMCE.init({
			mode : "exact",
			theme : "advanced",
			elements : "<?=$element->getName();?>",
			plugins : "inlinepopups,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,insertdatetime,preview,zoom,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras",
			theme_advanced_buttons1 : "newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,styleselect,formatselect,fontselect,fontsizeselect",
			theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
			theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
			theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|,styleprops,|,cite,abbr,acronym,del,ins,|,visualchars,nonbreaking",
			theme_advanced_toolbar_location : "top",
			theme_advanced_toolbar_align : "left",
			theme_advanced_path_location : "bottom",
			extended_valid_elements : "a[name|href|target|title|onclick],img[class|src|border=0|alt|title|hspace|vspace|width|height|align|onmouseover|onmouseout|name],hr[class|width|size|noshade],font[face|size|color|style],span[class|align|style]",
			theme_advanced_resize_horizontal : 'true',
			theme_advanced_resizing : 'true',
			apply_source_formatting : 'true',
			convert_urls : 'false',
			force_br_newlines : 'true',
            doctype : '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">'

		});
		</script>
	  <textarea name="<?=$element->getName()?>" title="<?=$element->getTitle()?>" id="<?=$element->getHtmlId()?>" class="textarea <?=$element->getClass()?>" cols="80" rows="20"><?=$element->getValue();?></textarea>
    </span>
	  <?break;
		case 'textarea':?>
			<span class="form_row">
					<label for="<?=$element->getHtmlId()?>"><?=$element->getLabel()?>:</label>
					<textarea name="<?=$element->getName()?>" title="<?=$element->getTitle()?>" id="<?=$element->getHtmlId()?>" class="textarea <?=$element->getClass()?>"><?=$element->getValue();?></textarea>
			</span>
      <?break;
    case 'editor':?>
      <?break;
    case 'file':?>
      <?break;
    case 'checkbox':?>
      <?break;
}?>
<?if($element->getScript()):?>
<script type="text/javascript">
    <?=$element->getScript()?>
</script>
<?endif;?>
