<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="page-head button-level">
    <h3><?=$this->__('Compare Products')?></h3>
    <a href="#" class="link-print right" onclick="print();"><?=$this->__('Print This Page')?></a>
</div>
<?$_total=$this->getItems()->getSize()?>
<?if($_total):?>
<div class="compare-products">
    <table cellspacing="0" class="data-table box-table catalog-listing" id="product_comparison">
<?if ($_total>2):?>
        <tbody class="remove-buttons">
            <tr>
                <?$_i=0?>
                <?foreach($this->getItems() as $_item):?>
                <?if($_i++%10==0):?>
                <td>&nbsp;</td>
                <?endif;?>
                <td><a href="#" onclick="setLocation('<?=$this->helper('catalog/product_compare')->getRemoveUrl($_item)?>');window.opener.location.reload();"><img src="<?=$this->getSkinUrl('images/chart_remove.gif')?>" alt="<?=$this->__('Remove Product')?>"/></a></td>
                <?endforeach;?>
            </tr>
        </tbody>
<?endif?>
        <tbody>
            <tr class="first">
            <?$_i=0?>
            <?foreach($this->getItems() as $_item):?>
                <?if($_i++%10==0):?>
                    <td class="label">&nbsp;</td>
                <?endif;?>
                <td>
                    <a href="#" onclick="setPLocation('<?=$_item->getProductUrl()?>', true)" title="<?=$this->htmlEscape($_item->getName())?>"><img src="<?=$_item->getSmallImageUrl()?>" width="125" height="125" alt="<?=$this->htmlEscape($_item->getName())?>"/></a>
                    <h5><a href="#" onclick="setPLocation('<?=$_item->getProductUrl()?>', true)" title="<?=$this->htmlEscape($_item->getName())?>"><?=$_item->getName()?></a></h5>
                    <?=$this->helper('review/product')->getSummaryHtml($_item, 'short')?>
                    <?=$this->helper('catalog/product')->getPriceHtml($_item)?>
                    <?if($_item->isSaleable()):?>
                    <button class="form-button" onclick="setPLocation('<?=$this->helper('catalog/product_compare')->getAddToCartUrl($_item)?>', true)"><span><?=$this->__('Add to Cart')?></span></button><br/>
                    <?endif;?>
                    <a href="#" onclick="setPLocation('<?=$this->helper('catalog/product_compare')->getAddToWishlistUrl($_item)?>', true)" class="link-cart"><small><?=$this->__('Add to My Wishlist')?></small></a>
                </td>
            <?endforeach;?>
            </tr>
        </tbody>
        <tbody>
        <?foreach ($this->getAttributes() as $_attribute):?>
            <tr>
                <?$_i=0?>
                <?foreach($this->getItems() as $_item):?>
                <?if($_i++%10==0):?>
                <td class="label"><?=$_attribute->getFrontendLabel()?></td>
                <?endif;?>
                <td>
                    <?switch ($_attribute->getAttributeCode()) {
                        case "price":?>
                            <?=$this->helper('catalog/product')->getPriceHtml($_item)?>
                            <?break;
                        case "small_image":?>
                            <img src="<?=$_item->getSmallImageUrl()?>" width="125" height="125" alt="<?=$_item->getName()?>"/>
                            <?break;
                        default:?>
                            <?=$this->getProductAttributeValue($_item, $_attribute)?>
                            <?break;
                    }?>
                </td>
                <?endforeach;?>
            </tr>
        <?endforeach;?>
        </tbody>
        <tbody class="attribute-cart">
                <tr>
                <?$_i=0?>
                <?foreach($this->getItems() as $_item):?>
                <?if($_i++%10==0):?>
                 <td class="label">&nbsp;</td>
                <?endif;?>
                <td>
                        <?=$this->helper('catalog/product')->getPriceHtml($_item)?>
                        <?if($_item->isSaleable()):?>
                        <button class="form-button" onclick="setPLocation('<?=$this->helper('catalog/product_compare')->getAddToCartUrl($_item)?>', true)"><span><?=$this->__('Add to Cart')?></span></button><br/>
                        <?endif;?>
                        <a href="#" onclick="setPLocation('<?=$this->helper('catalog/product_compare')->getAddToWishlistUrl($_item)?>', true)" class="link-cart"><small><?=$this->__('Add to Wishlist')?></small></a>
                    </div>
                </div>
                </td>
                <?endforeach;?>
            </tr>
        </tbody>
    </table>
    <div class="form-buttons">
        <button class="form-button" onclick="window.close();window.opener.focus();"><span><?=$this->__('Close Window')?></span></button>
    </div>
</div>
<script type="text/javascript">
    decorateTable('product_comparison');
</script>
<?else:?>
<script type="text/javascript">
    window.close();
</script>
<?endif;?>
