<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   default
 * @package    default_default
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<fieldset id="order_history_block">
    <div id="history_form" class="order-history-form">
        <span class="field-row">
            <div><?=Mage::helper('sales')->__('Add Order Comments')?></div>
            <label class="normal" for="history_status"><?=Mage::helper('sales')->__('Status')?></label><br/>
            <select name="history[status]" class="select" id="history_status">
            <?foreach ($this->getStatuses() as $_code=>$_label):?>
                <option value="<?=$_code?>"<?if($_code==$this->getOrder()->getStatus()):?> selected<?endif;?>><?=$_label?></option>
            <?endforeach;?>
            </select>
        </span>
        <span class="field-row">
            <label class="normal" for="history_comment"><?=Mage::helper('sales')->__('Comment')?></label>
            <textarea name="history[comment]" class="input-text" style="height:6em;width:99%" id="history_comment"></textarea>
        </span>
        <div class="f-left">
            <input name="history[is_customer_notified]" type="checkbox" id="history_notify" value="1"/>
            <label class="normal" for="history_notify"><?=Mage::helper('sales')->__('Notify Customer')?></label>
        </div>
        <div class="f-right">
            <?=$this->getChildHtml('submit_button')?>
        </div>
        <div class="clear"></div>
    </div>
    <div class="divider"></div>
    <ul class="note-list">
    <?foreach ($this->getOrder()->getStatusHistoryCollection(true) as $_history):?>
        <li>
            <strong><?=$this->helper('core')->formatDate($_history->getCreatedAt(), 'medium')?></strong>
            <?=$this->helper('core')->formatTime($_history->getCreatedAt(), 'medium')?><span class="separator">|</span><strong><?=$_history->getStatusLabel()?></strong><br/><small><?=$this->helper('sales')->__('Customer')?>
            <strong class="subdue">
                <?if ($_history->getIsCustomerNotified()):?>
                <?=$this->helper('sales')->__('Notified')?>
                <img src="<?=$this->getSkinUrl('images/ico_success.gif')?>" width="16" height="16"/>
                <?else:?>
                <?=$this->helper('sales')->__('Not Notified')?>
                <?endif;?>
            </strong></small>
            <?if($_history->getComment()):?>
                <br/><?=$_history->getComment()?>
            <?endif;?>
        </li>
    <?endforeach;?>
    </ul>
    <script type="text/javascript">
    if($('order_status'))$('order_status').update('<?=$this->getOrder()->getStatusLabel()?>');
    </script>
</fieldset>