<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?$_order=$this->getOrder()?>

<div class="box-left">
    <!--Order Information-->
    <div class="entry-edit">
        <h4 class="icon-head head-order-date"><?=Mage::helper('sales')->__('Order # %s', $_order->getRealOrderId())?></h4>
        <fieldset>
            <table cellspacing="0" class="form-list">
            <tr>
                <td class="label"><label><?=Mage::helper('sales')->__('Order Date')?></label></td>
                <td class="input-ele"><strong><?=$this->formatDate($_order->getCreatedAt(), 'medium', true)?></strong></td>
            </tr>
            <tr>
                <td class="label"><label><?=Mage::helper('sales')->__('Order Status')?></label></td>
                <td class="input-ele"><strong><span id="order_status"><?=$_order->getStatusLabel()?></span></strong></td>
            </tr>
            <tr>
                <td class="label"><label><?=Mage::helper('sales')->__('Purchased From')?></label></td>
                <td class="input-ele"><strong><?=$this->getOrderStoreName()?></strong></td>
            </tr>
            <?if($_order->getRelationChildId()):?>
            <tr>
                <td class="label"><label><?=Mage::helper('sales')->__('Link to the new order')?></label></td>
                <td class="input-ele"><a href="<?=$this->getViewUrl($_order->getRelationChildId())?>">
                    <?=$_order->getRelationChildRealId()?>
                </a></td>
            </tr>
            <?endif;?>
            <?if($_order->getRelationParentId()):?>
            <tr>
                <td class="label"><label><?=Mage::helper('sales')->__('Link to the previous order')?></label></td>
                <td class="input-ele"><a href="<?=$this->getViewUrl($_order->getRelationParentId())?>">
                    <?=$_order->getRelationParentRealId()?>
                </a></td>
            </tr>
            <?endif;?>
            </table>
        </fieldset>
    </div>
</div>
<div class="box-right">
    <!--Account Information-->
    <div class="entry-edit">
        <h4 class="icon-head head-account"><?=Mage::helper('sales')->__('Account Information')?></h4>
        <fieldset>
            <table cellspacing="0" class="form-list">
            <tr>
                <td class="label"><label><?=Mage::helper('sales')->__('Customer Name')?></label></td>
                <td class="input-ele"><strong><?=$_order->getCustomerName()?></strong></td>
            </tr>
            <tr>
                <td class="label"><label><?=Mage::helper('sales')->__('Email')?></label></td>
                <td class="input-ele"><a href="mailto:<?=$_order->getCustomerEmail()?>"><strong><?=$_order->getCustomerEmail()?></strong></a></td>
            </tr>
            <tr>
                <td class="label"><label><?=Mage::helper('sales')->__('Customer Group')?></label></td>
                <td class="input-ele"><strong><?=$this->getCustomerGroupName()?></strong></td>
            </tr>
            </table>
        </fieldset>
    </div>
</div>
<div class="clear"></div>

<div class="box-left">
    <!--Billing Address-->
    <div class="entry-edit">
        <h4 class="icon-head head-billing-address"><?=Mage::helper('sales')->__('Billing Address')?></h4>
        <fieldset>
            <address><?=$_order->getBillingAddress()->getFormated(true)?></address>
        </fieldset>
    </div>
</div>
<div class="box-right">
    <!--Shipping Address-->
    <div class="entry-edit">
        <h4 class="icon-head head-shipping-address"><?=Mage::helper('sales')->__('Shipping Address')?></h4>
        <fieldset>
            <address><?=$_order->getShippingAddress()->getFormated(true)?></address>
        </fieldset>
    </div>
</div>
<div class="clear"></div>
