<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?$_order=$this->getOrder()?>
<div class="grid">
    <table cellspacing="0" class="data">
        <col/>
        <col width="70"/>
        <col width="80"/>
        <col width="80"/>
        <col width="100"/>
        <col width="90"/>
        <col width="90"/>
        <col width="100"/>
        <col width="100"/>
        <thead>
            <tr class="headings">
                <th><?=$this->helper('sales')->__('Product')?></th>
                <th><?=$this->helper('sales')->__('Item Status')?></th>
                <th><?=$this->helper('sales')->__('Original Price')?></th>
                <th><?=$this->helper('sales')->__('Price')?></th>
                <th><?=$this->helper('sales')->__('Qty')?></th>
                <th><?=$this->helper('sales')->__('Subtotal')?></th>
                <th><?=$this->helper('sales')->__('Tax Amount')?></th>
                <th><?=$this->helper('sales')->__('Discount Amount')?></th>
                <th class="last"><?=$this->helper('sales')->__('Row Total')?></th>
            </tr>
        </thead>
        <tbody>
            <?$_items = $this->getItemsCollection()?>
            <?$i=0;foreach ($_items as $_item):$i++?>
                <tr class="<?=($i%2==0)?'even':'odd'?>">
                    <td class="giftmessage-single-item"><?=$this->renderInfoColumn($_item)?></td>
                    <td><?=$_item->getStatus()?></td>
                    <td class="price"><?=$_order->formatPrice($_item->getOriginalPrice())?></td>
                    <td class="price"><?=$_order->formatPrice($_item->getPrice())?></td>
                    <td><?=$this->getQtyHtml($_item)?></td>
                    <td class="price"><?=$_order->formatPrice($_item->getRowTotal())?></td>
                    <td class="price"><?=$_order->formatPrice($_item->getTaxAmount())?></td>
                    <td class="price"><?=$_order->formatPrice(-$_item->getDiscountAmount())?></td>
                    <td class="last price">
                        <?=$_order->formatPrice($_item->getRowTotal()-$_item->getDiscountAmount()+$_item->getTaxAmount())?>
                    </td>
                </tr>
            <?endforeach;?>
        </tbody>
    </table>
</div>