<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="inner-head">
    <h5><?=$this->__('Address Book')?></h5>
    <a href="<?=$this->getAddressBookUrl()?>"><?=$this->__('Manage Addresses')?></a>
</div>
<div class="col2-set">
    <div class="col-1">
        <h6><?=$this->__('Primary Billing Address')?></h6>
        <address>
            <?=$this->getPrimaryBillingAddressHtml()?><br/>
            <a href="<?=$this->getPrimaryBillingAddressEditUrl()?>"><?=$this->__('Edit Address')?></a>
        </address>
    </div>
    <div class="col-2">
        <h6><?=$this->__('Primary Shipping Address')?></h6>
        <address>
            <?=$this->getPrimaryShippingAddressHtml()?><br/>
            <a href="<?=$this->getPrimaryShippingAddressEditUrl()?>"><?=$this->__('Edit Address')?></a>
        </address>
    </div>
</div><br/>
