<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="head">
    <h4><?=$this->__('Product Tags')?></h4>
</div>
    <?if( $this->getCount() ):?>
    <h5><?=$this->__('Other people marked this product with these tags:')?></h5>
        <ul class="tags-list">
            <?$_iterator = 0;?>
            <?foreach( $this->getTags() as $_tag ):?>
                <li <?if( 1 == ++$_iterator && $this->getCount() != 1 ):?>class="first"<?elseif($_iterator == $this->getCount()):?>class="last"<?endif;?>><a href="<?=$_tag->getTaggedProductsUrl()?>"><?=$_tag->getName()?></a> (<?=$_tag->getPopularity()?>)</li>
            <?endforeach;?>
        </ul>
    <?endif;?>
<h5><?=$this->__('Add Your Tags:')?></h5>
<div class="add-tag-box">
    <form name="addTagForm" id="addTagForm" action="<?=$this->getFormAction();?>"  method="get">
        <div class="input-box">
            <input type="text" class="input-text required-entry" name="tagName" />
        </div>
        <button class="form-button-alt" onclick="submitTagForm()"><span><?=$this->__('Add Tags')?></span></button>
    </form>
    <script type="text/javascript">
        var addTagFormJs = new VarienForm('addTagForm');
        function submitTagForm(){
            if(addTagFormJs.validator.validate()) {
                addTagFormJs.form.submit();
            }
        }
    </script>
    <div class="clear"></div>
    <small><?=$this->__("Use spaces to separate tags. Use single quotes (') for phrases.")?></small>
</div>