<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="box base-mini mini-product-tags">
    <div class="head">
        <h4><?=$this->__('Popular Tags');?></h4>
    </div>
    <div class="content">
    <ul>
        <?foreach ($this->getTags() as $_tag):?>
            <li><a href="<?=$_tag->getTaggedProductsUrl()?>" style="font-size:<?=$_tag->getRatio()*70+75?>%;"><?=$_tag->getName()?></a></li>
        <?endforeach;?>
    </ul>
    </div>
    <div class="actions">
        <a href="<?=$this->getUrl('tag/list')?>"><small><?=$this->__('View All Tags')?></small></a>
    </div>
</div>
