<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>


<?if($this->getCount()):?>
<div class="graph-table col3">
	<div class="tab-right">
	<div class="tab-head">
		<?foreach ($this->getColumns() as $yKey => $_column):?>
		<div class="header" style="<?=($yKey % 2 ? 'background:none;' : '')?> <?=( $_column->getWidth() ? 'width:' . ($_column->getWidth()+6) . 'px' : '')?>"><?=$_column->getHeader()?></div>
		<?endforeach;?>
	</div><div class="clear"></div>
	<?$_scrollIndex = $this->getScrollIndex()?>
		
		<div class="tab-body">
		<?if($this->getCount()>10):?>
		<div class="scroll">
		<?endif;?>
		<?foreach ($this->getCollection() as $gKey => $row):?>
			<div class="row<?=( $gKey % 2 ? '2': '')?>">
			<?foreach ($this->getColumns() as $k => $_column) :?>
				<div class="tab-item" <?=( $k=='1' ? ' style="text-align:right;"' : '')?>><?=$this->getRowValue($_column, $row)?></div>
			<?endforeach;?>
			</div>
		<?endforeach;?>
		<?if($this->getCount()>10):?>
		</div>
		<?endif;?>
		</div>
	<div class="clear"></div>
	<div class="tab-footer">
	<?if($this->getCount()):?>
	  <table cellpadding="0" cellspacing="0" border="0" class="totals" align="right">
         <?foreach ($this->getTotals() as $_total):?>
	  	<tr>
         		<td class="label"><?=$_total['label']?>:</td>
			<td class="value"><div><?=$_total['value']?></div></td>
         	</tr>
	  <?endforeach;?>
         </table><div class="clear"></div>
     <?endif;?>
	</div><div class="clear"></div>
</div></div>
<div class="tab-footer-bottom"><div class="tab-footer-right"></div><div class="tab-footer-left"></div></div>
<div class="clear"></div><br/>
<?else:?>
<div align="center" style="margin-top:180px;"><?=$this->__('No Data Found')?></div>
<?endif;?>