<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?
/**
 * Template for block Mage_Adminhtml_Block_Catalog_Product_Edit_Tab_Alerts
 */
?>
<script type="text/javascript" language="javascript">
    var Queue = Class.create();
    var url = '<?=$this->getAddToQueueUrl();?>';
    
    function setMessages(messages) {
        messageObject = $('alert_messages_block');
        messageObject.update(messages);        
    }
    
    Queue.prototype = {
        initialize:
            function() {
            },
        add: function(productId, storeId) {
            new Ajax.Request ( url, {   
                    param :
                        { 
                            'store_id':storeId,
                            'peoduct_id':productId
                        },
                    onSuccess : function(req) 
                        {
                            setMessages(req.responseText);
                        },
                    onFailure : function()
                        {
                           alert('<?=Mage::helper('customeralert')->__('Error in using AJAX while saving customers to queue alert')?>');
                        }
                           
                    })
        }
    }
queue = new Queue();
</script>
<div id="alert_messages_block"><?=$this->getMessageHtml()?></div>
<div>
	<h4 class="icon-head head-edit-form"><?=Mage::helper('customeralert')->__('Product Alerts')?></h4>
</div>
<div class="clear"></div>
<br />
    <?=$this->getAccordionHtml()?>
<br />
<div class="right">
    <?=$this->getAddToQueryButtonHtml()?>
</div>

