<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   Mage
 * @package    Mage_Adminhtml
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?=Mage::helper('catalog')->__('Inventory')?></h4>
    </div>
    <fieldset>

        <legend><?=Mage::helper('catalog')->__('Inventory')?></legend>
        <table cellspacing="0" class="form-list">
<?if(!$this->getProduct()->isConfigurable() && !$this->getProduct()->isGrouped()):?>
        <tr>
            <td class="label"><label for="inventory_qty"><?=Mage::helper('catalog')->__('Qty')?><span class="required">*</span></label></td>
            <td class="value"><input type="text" class="input-text required-entry validate-number" id="inventory_qty" name="<?=$this->getFieldSuffix()?>[stock_data][qty]" value="<?=$this->getFieldValue('qty')*1?>"/>
            </td>
            <td class="value scope-label"><?=Mage::helper('catalog')->__('[GLOBAL]')?></td>
        </tr>

        <tr>
            <td class="label"><label for="inventory_min_qty"><?=Mage::helper('catalog')->__('Minimum Qty for Item\'s Status to be Out of Stock')?></label></td>
            <td class="value"><input type="text" class="input-text validate-number" id="inventory_min_qty" name="<?=$this->getFieldSuffix()?>[stock_data][min_qty]" value="<?=$this->getFieldValue('min_qty')*1?>"/>

            <?$_checked = ($this->getFieldValue('use_config_min_qty') || $this->IsNew()) ? 'checked' : ''?>
            <input type="checkbox" id="inventory_use_config_min_qty" name="<?=$this->getFieldSuffix()?>[stock_data][use_config_min_qty]" value="1" <?=$_checked?> onclick="toggleValueElements(this, this.parentNode);"/>
            <label for="inventory_use_config_min_qty" class="normal"><?=Mage::helper('catalog')->__('Use Config Settings')?></label>
            <script type="text/javascript">toggleValueElements($('inventory_use_config_min_qty'), $('inventory_use_config_min_qty').parentNode);</script></td>
            <td class="value scope-label"><?=Mage::helper('catalog')->__('[GLOBAL]')?></td>
        </tr>

        <tr>
            <td class="label"><label for="inventory_min_sale_qty"><?=Mage::helper('catalog')->__('Minimum Qty Allowed in Shopping Cart')?></label></td>
            <td class="value"><input type="text" class="input-text validate-number" id="inventory_min_sale_qty" name="<?=$this->getFieldSuffix()?>[stock_data][min_sale_qty]" value="<?=$this->getFieldValue('min_sale_qty')*1?>"/>

            <?$_checked = ($this->getFieldValue('use_config_min_sale_qty') || $this->IsNew()) ? 'checked' : ''?>
            <input type="checkbox" id="inventory_use_config_min_sale_qty" name="<?=$this->getFieldSuffix()?>[stock_data][use_config_min_sale_qty]" value="1" <?=$_checked?> onclick="toggleValueElements(this, this.parentNode);"/>
            <label for="inventory_use_config_min_sale_qty" class="normal"><?=Mage::helper('catalog')->__('Use Config Settings')?></label>
            <script type="text/javascript">toggleValueElements($('inventory_use_config_min_sale_qty'), $('inventory_use_config_min_sale_qty').parentNode);</script></td>
            <td class="value scope-label"><?=Mage::helper('catalog')->__('[GLOBAL]')?></td>
        </tr>

        <tr>
            <td class="label"><label for="inventory_max_sale_qty"><?=Mage::helper('catalog')->__('Maximum Qty Allowed in Shopping Cart')?></label></td>
            <td class="value"><input type="text" class="input-text validate-number" id="inventory_max_sale_qty" name="<?=$this->getFieldSuffix()?>[stock_data][max_sale_qty]" value="<?=$this->getFieldValue('max_sale_qty')*1?>"/>

            <?$_checked = ($this->getFieldValue('use_config_max_sale_qty') || $this->IsNew()) ? 'checked' : ''?>
            <input type="checkbox" id="inventory_use_config_max_sale_qty" name="<?=$this->getFieldSuffix()?>[stock_data][use_config_max_sale_qty]" value="1" <?=$_checked?> onclick="toggleValueElements(this, this.parentNode);"/>
            <label for="inventory_use_config_max_sale_qty" class="normal"><?=Mage::helper('catalog')->__('Use Config Settings')?></label>
            <script type="text/javascript">toggleValueElements($('inventory_use_config_max_sale_qty'), $('inventory_use_config_max_sale_qty').parentNode);</script></td>
            <td class="value scope-label"><?=Mage::helper('catalog')->__('[GLOBAL]')?></td>
        </tr>

        <tr>
            <td class="label"><label for="inventory_is_qty_decimal"><?=Mage::helper('catalog')->__('Qty Uses Decimals')?></label></td>
            <td class="value"><select id="inventory_is_qty_decimal" name="<?=$this->getFieldSuffix()?>[stock_data][is_qty_decimal]" class="select">
                <option value="0"><?=Mage::helper('catalog')->__('No')?></option>
                <option value="1"<?if($this->getFieldValue('is_qty_decimal')==1):?> selected<?endif;?>><?=Mage::helper('catalog')->__('Yes')?></option>
            </select>
            </td>
            <td class="value scope-label"><?=Mage::helper('catalog')->__('[GLOBAL]')?></td>
        </tr>

        <tr>
            <td class="label"><label for="inventory_backorders"><?=Mage::helper('catalog')->__('Backorders')?></label></td>
            <td class="value"><select id="inventory_backorders" name="<?=$this->getFieldSuffix()?>[stock_data][backorders]" class="select">
            <?foreach ($this->getBackordersOption() as $option):?>
                <?$_selected = ($option['value'] == $this->getFieldValue('backorders')) ? 'selected' : ''?>
                <option value="<?=$option['value']?>" <?=$_selected?>><?=$option['label']?></option>
            <?endforeach;?>
            </select>

            <?$_checked = ($this->getFieldValue('use_config_backorders') || $this->IsNew()) ? 'checked' : ''?>
            <input type="checkbox" id="inventory_use_config_backorders" name="<?=$this->getFieldSuffix()?>[stock_data][use_config_backorders]" value="1" <?=$_checked?> onclick="toggleValueElements(this, this.parentNode);"/>
            <label for="inventory_use_config_backorders" class="normal"><?=Mage::helper('catalog')->__('Use Config Settings')?></label>
            <script type="text/javascript">toggleValueElements($('inventory_use_config_backorders'), $('inventory_use_config_backorders').parentNode);</script></td>
            <td class="value scope-label"><?=Mage::helper('catalog')->__('[GLOBAL]')?></td>
        </tr>
        <tr>
            <td class="label"><label for="inventory_notify_stock_qty"><?=Mage::helper('catalog')->__('Notify for Qauntity Below')?></label></td>
            <td class="value"><input type="text" class="input-text validate-number" id="inventory_notify_stock_qty" name="<?=$this->getFieldSuffix()?>[stock_data][notify_stock_qty]" value="<?=$this->getFieldValue('notify_stock_qty')*1?>"/>

            <?$_checked = ($this->getFieldValue('use_config_notify_stock_qty') || $this->IsNew()) ? 'checked' : ''?>
            <input type="checkbox" id="inventory_use_config_notify_stock_qty" name="<?=$this->getFieldSuffix()?>[stock_data][use_config_notify_stock_qty]" value="1" <?=$_checked?> onclick="toggleValueElements(this, this.parentNode);"/>
            <label for="inventory_use_config_notify_stock_qty" class="normal"><?=Mage::helper('catalog')->__('Use Config Settings')?></label>
            <script type="text/javascript">toggleValueElements($('inventory_use_config_notify_stock_qty'), $('inventory_use_config_notify_stock_qty').parentNode);</script></td>
            <td class="value scope-label"><?=Mage::helper('catalog')->__('[GLOBAL]')?></td>
        </tr>
<?endif;?>
        <tr>
            <td class="label"><label for="inventory_stock_availability"><?=Mage::helper('catalog')->__('Stock Availability')?></label></td>
            <td class="value"><select id="inventory_stock_availability" name="<?=$this->getFieldSuffix()?>[stock_data][is_in_stock]" class="select">
                <option value="1"><?=Mage::helper('catalog')->__('In Stock')?></option>
                <option value="0"<?if($this->getFieldValue('is_in_stock')==0):?> selected<?endif;?>><?=Mage::helper('catalog')->__('Out of Stock')?></option>
            </select>
            </td>
            <td class="value scope-label"><?=Mage::helper('catalog')->__('[GLOBAL]')?></td>
        </tr>
        </table>
    </fieldset>
</div>