<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?
/**
 * Store switcher template
 *
 * @see Mage_Core_Block_Store_Switcher
 */
?>
<?if($this->getStoreCount()>1):?>
<fieldset class="store-switcher">
    <label for="select-store"><?=$this->__('Select Store')?>: </label>
    <select id="select-store" onchange="setStoreCode(this.value)">
    <?/*foreach ($this->getStores() as $_store):?>
        <option value="<?=$_store->getUrl('')?>"<?if($_store->getId()==$this->getCurrentStoreId()):?> selected="selected"<?endif;?>><?=$_store->getName()?></option>
    <?endforeach;*/?>
    <?foreach ($this->getStores() as $_store):?>
        <?$_selected = ($_store->getId()==$this->getCurrentStoreId()) ? 'selected="selected"' : ''?>
        <option value="<?=$_store->getCode()?>" <?=$_selected?>><?=$_store->getName()?></option>
    <?endforeach;?>    
    </select>
</fieldset>
<?endif;?>
