<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<form id="edit_form" method="post" action="<?=$this->getSaveUrl()?>">
    <? $_order = $this->getInvoice()->getOrder()?>
    <?=$this->getChildHtml('order_info')?>

    <div class="box-left">
        <div class="entry-edit">
            <h4 class="icon-head head-payment-method"><?=Mage::helper('sales')->__('Payment Information')?></h4>
            <fieldset>
                <div><?=$this->getChildHtml('payment_info')?></div>
            </fieldset>
        </div>
    </div>
    <div class="box-right">
        <div class="entry-edit">
            <h4 class="icon-head head-shipping-method"><?=Mage::helper('sales')->__('Shipping Information')?></h4>
            <fieldset>
                <strong><?=$_order->getShippingDescription()?></strong>
                (<?=$this->helper('sales')->__('Total Shipping Charges %s', $_order->formatPrice($_order->getShippingAmount()))?>)
            </fieldset>
        </div>
    </div>
    <div class="clear"></div>

    <div class="entry-view">
        <h4 class="icon-head head-products"><?=Mage::helper('sales')->__('Items to Invoice')?></h4>
    </div>
    <div id="invoice_item_container">
        <?=$this->getChildHtml('items')?>
    </div>
</form>