<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="grid">
    <table cellspacing="0" class="data" id="invoice_items_grid_table">
        <col/>
        <col width="100"/>
        <col width="100"/>
        <col width="60"/>
        <col width="100"/>
        <col width="100"/>
        <col width="100"/>
        <col width="100"/>
        <thead>
            <tr class="headings">
                <th><?=Mage::helper('sales')->__('Product')?></th>
                <th><?=Mage::helper('sales')->__('Price')?></th>
                <th><?=Mage::helper('sales')->__('Qty')?></th>
                <th><?=Mage::helper('sales')->__('Qty to Invoice')?></th>
                <th><?=Mage::helper('sales')->__('Subtotal')?></th>
                <th><?=Mage::helper('sales')->__('Tax Amount')?></th>
                <th><?=Mage::helper('sales')->__('Discount Amount')?></th>
                <th class="last"><?=Mage::helper('sales')->__('Row Total')?></th>
            </tr>
        </thead>
        <tbody>
            <?$_items = $this->getInvoice()->getAllItems()?>
            <?$_i=0;foreach ($_items as $_item):$_i++?>
                <?$this->setPriceDataObject($_item)?>
                <tr class="<?=$_i%2?'odd':'even'?>">
                    <td>
                        <?=$_item->getName()?>
                        <div class="nobr"><strong><?=$this->helper('sales')->__('SKU')?>:</strong> <?=$_item->getSku()?></div>
                        <?=$_item->getDescription()?>
                    </td>
                    <td class="price"><?=$this->displayPriceAttribute('price')?></td>
                    <td><?=$this->getQtyHtml($_item->getOrderItem())?></td>
                    <td class="a-center">
                    <?if ($this->canEditQty()) :?>
                        <input type="text" class="input-text qty-input" name="invoice[items][<?=$_item->getOrderItemId()?>]" value="<?=$_item->getQty()*1?>"/>
                    <?else :?>
                        <?=$_item->getQty()*1?>
                    <?endif;?>
                    </td>
                    <td class="price"><?=$this->displayPriceAttribute('row_total')?></td>
                    <td class="price"><?=$this->displayPriceAttribute('tax_amount')?></td>
                    <td class="price"><?=$this->displayPriceAttribute('discount_amount')?></td>
                    <td class="last price">
                        <?=$this->displayPrices(
                            $_item->getBaseRowTotal()+$_item->getBaseTaxAmount()-$_item->getBaseDiscountAmount(),
                            $_item->getRowTotal()+$_item->getTaxAmount()-$_item->getDiscountAmount()
                        )?>
                    </td>
                </tr>
            <?endforeach;?>
        </tbody>
        <?if ($this->canEditQty()):?>
        <tfoot>
            <tr>
                <td colspan="2"></td>
                <td colspan="3" class="a-center">
                    <?=$this->getUpdateButtonHtml()?>
                </td>
                <td colspan="3"></td>
            </tr>
        </tfoot>
        <?endif;?>
    </table>
</div>

<div class="clear"></div>
<?=$this->getChildHtml('totals_bar')?>
<div class="clear"></div>

<div class="box-left entry-edit">
    <div class="entry-edit-head"><h4><?=$this->__('Invoice History')?></h4></div>
    <fieldset>
        <div id="history_form" class="order-history-form">
            <span class="field-row">
                <label class="normal" for="history_comment"><?=Mage::helper('sales')->__('Invoice Comments')?></label>
                <textarea name="invoice[comment_text]" class="input-text" style="height: 10em; width: 99%;"></textarea>
            </span>
            <div class="clear"></div>
        </div>
    </fieldset>
</div>

<div class="box-right entry-edit" id="history_form">
    <div class="entry-edit-head"><h4><?=$this->__('Invoice Totals')?></h4></div>
    <div class="order-totals">
        <?=$this->getChildHtml('totals')?>
        <div class="divider"></div>

        <?if ($this->getInvoice()->canCapture()):?>
        <p>
            <label for="invoice_do_capture" class="normal"><?=Mage::helper('sales')->__('Capture Amount')?></label>
            <input type="checkbox" name="invoice[do_capture]" id="invoice_do_capture" value="1" checked/>
        </p>
        <?endif;?>
        <p>
            <label class="normal" for="notify_customer"><?=Mage::helper('sales')->__('Append Comments')?></label>
            <input id="notify_customer" name="invoice[comment_customer_notify]" value="1" type="checkbox">
        </p>
        <p>
            <label class="normal" for="send_email"><?=Mage::helper('sales')->__('Email Copy of Invoice')?></label>
            <input id="send_email" name="invoice[send_email]" value="1" type="checkbox">
        </p>
        <div class="a-right">
        <?=$this->getChildHtml('submit_button')?>
        </div>
    </div>
</div>
<div class="clear"></div>

<table class="order-info-foot" cellpadding="10" cellspacing="0" width="100%">
    <tbody>
        <tr>
            <td class="section">
                <table id="comments_block" cellpadding="0" width="100%">
                    <tbody>
                        <tr>
                            <td style="padding-right: 30px;" width="50%"></td>
                            <td>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </td>

            <td class="document-totals section">
            </td>
        </tr>
    </tbody>
</table>

<script type="text/javascript">
var submitButtons = document.getElementsByClassName('submit-button');
var updateButtons = document.getElementsByClassName('update-button');
var fields = document.getElementsByClassName('qty-input');

updateButtons.each(function (elem) {elem.disabled=true;elem.addClassName('disabled');});

for(var i=0;i<fields.length;i++){
    fields[i].observe('change', checkButtonsRelation)
    fields[i].baseValue = fields[i].value;
}

function checkButtonsRelation() {
    var hasChanges = false;
    fields.each(function (elem) {
        if (elem.baseValue != elem.value) {
            hasChanges = true;
        }
    }.bind(this));
    if (hasChanges) {
        submitButtons.each(function (elem) {elem.disabled=true;elem.addClassName('disabled');});
        updateButtons.each(function (elem) {elem.disabled=false;elem.removeClassName('disabled');});
    }
    else {
        submitButtons.each(function (elem) {elem.disabled=false;elem.removeClassName('disabled');});
        updateButtons.each(function (elem) {elem.disabled=true;elem.addClassName('disabled');});
    }
}
</script>