<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?
/**
 * Multishipping checkout billing information
 *
 * @see Mage_Checkout_Block_Multishipping_Billing
 */
?>
<div class="page-head">
    <h3><?=$this->__('Billing Information')?></h3>
</div>
<?=$this->getMessagesBlock()->getGroupedHtml()?>
<script src="<?=Mage::getBaseUrl('js')?>varien/payment.js" type="text/javascript"></script>
<form action="<?=$this->getPostActionUrl()?>" method="post" id="multishipping-billing-form">
<div class="multi-address-checkout-box">
    <div class="box">
        <div class="content col2-set">
            <div class="col-1">
                <div class="head">
                    <h5>
                        <?=$this->__('Billing Address')?>
                        <span class="pipe">|</span>
                        <a href="<?=$this->getSelectAddressUrl()?>"><?=$this->__('Change Billing Address')?></a>
                    </h5>
                 </div>
                <?$_address=$this->getAddress()?>
                <address>
                    <?=$_address->format('html')?>
                </address>
            </diV>
            <div class="col-2">
                <div class="head">
                    <h5><?=$this->__('Payment Method')?></h5>
                </div>
                <div class="tool-tip" id="payment-tool-tip" style="left:0;position:absolute;display:none;padding-top:15px;">
                    <a href="#" id="payment-tool-tip-close" class="btn-close">
                        <img src="<?=$this->getSkinUrl('images/btn_window_close.gif')?>" alt="<?=$this->__('Close')?>"/>
                    </a>
                    <div class="block-content">
                    <img src="<?=$this->getSkinUrl('images/cvv.gif')?>" alt="<?=$this->__('Card Verification Number Visual Reference')?>"/>
                    </div>
                </div>

                <!-- Payment methods forms list -->
                <dl class="payment-methods">
                <?foreach ($this->getMethods() as $_method): $_code = $_method->getCode()?>
                    <dt>
                        <input id="p_method_<?=$_code?>" value="<?=$_code?>" type="radio" name="payment[method]" title="<?=$this->htmlEscape($_method->getTitle())?>" onclick="payment.switchMethod('<?=$_code?>')"<?if($this->getSelectedMethodCode()==$_code):?> checked<?endif;?>/>
                        <label for="p_method_<?=$_code?>"><?=$_method->getTitle()?></label>
                    </dt>
                    <dd>
                        <?=$this->getChildHtml('payment.method.'.$_code)?>
                    </dd>
                <?endforeach;?>
                </dl>
            </div>
        </div>
      </div>
</div>
<div class="button-set">
    <a href="<?=$this->getBackUrl()?>" class="left">&laquo;<?=$this->__('Back to Shipping Information')?></a>
    <button  class="form-button" type="submit"><span><?=$this->__('Continue to Review Your Order')?></span></button>
</div>
<script type="text/javascript">
    // Need to fix payment JS
    var payment = new paymentForm('multishipping-billing-form');
    function toggleToolTip(event){
        if($('payment-tool-tip')){
            $('payment-tool-tip').setStyle({
                top: (Event.pointerY(event)-500)+'px',
                left: (Event.pointerX(event)-800)+'px'
            })
            $('payment-tool-tip').toggle();
        }
        Event.stop(event);
    }
    if($('payment-tool-tip-close')){
        Event.observe($('payment-tool-tip-close'), 'click', toggleToolTip);
    }
    $$('.cvv-what-is-this').each(function(element){
        Event.observe(element, 'click', toggleToolTip);
    });
</script>
