<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<?
$_oldRates = $this->getOldRates();
$_newRates = $this->getNewRates();
$_rates = ( $_newRates ) ? $_newRates : $_oldRates;
?>
<form name="rateForm" id="rateForm" method="POST" action="<?=$this->getRatesFormAction();?>">
    <table class="rate-table data-table" cellpadding="0" cellspacing="0" border="0" style="border-top:0px;">
        <thead>
        <tr>
            <td class="thead">&nbsp;</td>
            <?$_i = 0; foreach( $this->getAllowedCurrencies() as $_currencyCode ):?>
                <td class="<?=(( ++$_i == (sizeof($this->getAllowedCurrencies())) ) ? 'thead-last' : 'thead' )?>"><strong><?=$_currencyCode?><strong></td>
            <?endforeach;?>
        </tr>
        </thead>
        <?$_j = 0; foreach( $this->getDefaultCurrencies() as $_currencyCode ):?>
        <tr>
            <?foreach( $_rates[$_currencyCode] as $_rate => $_value ):?>
                <?if( ++$_j == 1 ):?>
                    <td class="thead"><strong><?=$_currencyCode?></strong></td>
                    <td>
                        <input type="text" name="rate[<?=$_currencyCode?>][<?=$_rate?>]" value="<?=( $_currencyCode == $_rate ) ? '1.0000' : $_value?>" <?=( $_currencyCode == $_rate ) ? 'class="input-text input-text-disabled" readonly="true"' : 'class="input-text"'?> />
                        <?if( isset($_newRates) && $_currencyCode != $_rate && isset($_oldRates[$_currencyCode][$_rate]) ):?>
                        <br /><span class="old-rate"><?=$this->__('Old rate:')?> <?=$_oldRates[$_currencyCode][$_rate]?></span>
                        <?endif;?>
                    </td>
                <?else:?>
                    <td>
                        <input type="text" name="rate[<?=$_currencyCode?>][<?=$_rate?>]" value="<?=( $_currencyCode == $_rate ) ? '1.0000' : $_value?>" <?=( $_currencyCode == $_rate ) ? 'class="input-text input-text-disabled" readonly="true"' : 'class="input-text"'?> />
                        <?if( isset($_newRates)  && $_currencyCode != $_rate && isset($_oldRates[$_currencyCode][$_rate]) ):?>
                        <br /><span class="old-rate"><?=$this->__('Old rate:')?> <?=$_oldRates[$_currencyCode][$_rate]?></span>
                        <?endif;?>
                    </td>
                <?endif;?>
            <?endforeach; $_j = 0;?>
        </tr>
        <?endforeach;?>
    </table>
</form>
<script type="text/javascript">
    currencyForm = new varienForm('rateForm');
</script>