<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="grid">
    <table cellspacing="0" class="data">
        <col/>
        <col width="100"/>
        <col width="100"/>
        <thead>
            <tr class="headings">
                <th><?=$this->helper('sales')->__('Product')?></th>
                <th><?=$this->helper('sales')->__('Qty')?></th>
                <th class="last"><?=$this->helper('sales')->__('Qty to Ship')?></th>
            </tr>
        </thead>
        <tbody>
            <?$_items = $this->getShipment()->getAllItems()?>
            <?$_i=0;foreach ($_items as $_item):$_i++?>
                <tr class="<?=$_i%2?'odd':'even'?>">
                    <td>
                        <?=$_item->getName()?>
                        <div class="nobr"><strong><?=$this->helper('sales')->__('SKU')?>:</strong> <?=$_item->getSku()?></div>
                        <?=$_item->getDescription()?>
                    </td>
                    <td><?=$this->getQtyHtml($_item->getOrderItem())?></td>
                    <td class="last">
                        <input type="text" class="input-text" name="shipment[items][<?=$_item->getOrderItemId()?>]" value="<?=$_item->getQty()*1?>"/>
                    </td>
                </tr>
            <?endforeach;?>
        </tbody>
    </table>
</div>

<div class="box-left entry-edit">
    <div class="entry-edit-head"><h4><?=$this->__('Shipment Comments')?></h4></div>
    <fieldset>
        <div id="history_form" class="order-history-form">
            <span class="field-row">
                <label class="normal" for="history_comment"><?=Mage::helper('sales')->__('Shipment Comments')?></label>
                <textarea name="shipment[comment_text]" class="input-text" style="height: 6em; width: 99%;"></textarea>
            </span>
            <div class="clear"></div>
        </div>
    </fieldset>
</div>

<div class="box-right entry-edit" id="history_form">
    <div class="order-totals">
        <p>
            <label class="normal" for="notify_customer"><?=Mage::helper('sales')->__('Append Comments')?></label>
            <input id="notify_customer" name="shipment[comment_customer_notify]" value="1" type="checkbox">
        </p>
        <p>
            <label class="normal" for="send_email"><?=Mage::helper('sales')->__('Email Copy of Shipment')?></label>
            <input id="send_email" name="shipment[send_email]" value="1" type="checkbox">
        </p>
        <div class="a-right">
        <?=$this->getChildHtml('submit_button')?>
        </div>
    </div>
</div>
<div class="clear"></div>