<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<h2>Address Book</h2>
<?=$this->getMessagesBlock()->getGroupedHtml()?>
<table cellspacing="0" width="100%">
    <tr>
        <td style="width:50%;"><h3>Primary</h3>
            <table width="100%" cellspacing="0"> 
            <?if(!empty($primaryAddresses)):?>    
                <?foreach($primaryAddresses as $_address):?>
                <tr>
                    <td>
                    <address>
                        <?=nl2br($_address->toString("{{firstname}} {{lastname}}\n{{street}}\n{{city}}, {{regionName}} {{postcode}}\nT: {{telephone}}"))?>
                    </address>
                    <p>
                        <strong><a href="<?=$this->getUrl('customer/address/form', array('address'=>$_address->getAddressId()))?>" class="red-link"><?=$this->__('Edit Address')?></a></strong>
                    </p>
                    </td>
                </tr>
                <?endforeach;?>
            <?else:?>
                <tr>
                    <td>
                        <p><?=$this->__('You have no primary entries in your address book.')?></p>
                    </td>
                </tr>
            <?endif?>
            </table>
        </td>
        <td style="width:50%;"><h3><?=$this->__('Additional Address Entries')?></h3>
            <table width="100%" cellspacing="0"> 
            <?if(!empty($alternativeAddresses)):?>    
                <?foreach($alternativeAddresses as $_address):?>
                <tr>
                    <td>
                    <address>
                        <?=nl2br($_address->toString("{{firstname}} {{lastname}}\n{{street}}\n{{city}}, {{regionName}} {{postcode}}\nT: {{telephone}}"))?>
                    </address>
                    <p>
                        <strong><a href="<?=$this->getUrl('customer/address/form', array('address'=>$_address->getAddressId()))?>" class="red-link"><?=$this->__('Edit Address')?></a></strong><span class="separator">&nbsp;|&nbsp;</span><strong><a href="#" onclick="return deleteAddress('<?=$_address->getAddressId()?>');" class="red-link"><?=$this->__('Delete Address')?></a></strong>
                    </p>
                    </td>
                </tr>
                <?endforeach;?>
            <?else:?>
                <tr>
                    <td>
                        <p><?=$this->__('You have no additional entries in your address book.')?></p>
                    </td>
                </tr>
            <?endif?>
            </table>
        </td>
    </tr>
</table>
<div class="buttons-container">
    <a href="<?=$this->getUrl('customer/account')?>" class="float-left">&laquo; <?=$this->__('Back')?></a>
    <input type="button" onclick="window.location='<?=$this->getUrl('customer/address/form')?>';" value="<?=$this->__('New Address')?>" class="input-button">
</div>
<script type="text/javascript">
    function deleteAddress(addressId) {
        if(confirm('<?=$this->__('Are you sure you want to delete this address?')?>')) {
            window.location='<?=$this->getUrl("customer/address/delete")?>address/'+addressId;
        }
        return false;
    }
</script>