<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

    <div class="page-head">
            <h3><?=$this->__('My Orders')?></h3>
        </div>

<?if($orders->getSize()):?>
    <table cellspacing="0" width="100%" class="data-table" id="my-orders-table" >
        <thead>
            <tr>
                <th><?=$this->__('Order #')?></th>
                <th><?=$this->__('Date')?></th>
                <!--<th class="align-center">Shipped To</th>-->
                <th class="a-right"><?=$this->__('Total')?></th>
                <th class="a-center"><?=$this->__('Status')?></th>
                <th ><?=$this->__('Details')?></th>
            </tr>
        </thead>
        <tbody>
        <?foreach ($orders as $order):?>
            <tr>
                <td><?=$order->getRealOrderId()?>&nbsp;</td>
                <td><?=date("D, j M, Y", strtotime($order->getCreatedAt()))?>&nbsp;</td>
                <!--<td class="align-center">{$page.orders[io].customer}</td>-->
                <td class="a-right"><?=$order->getGrandTotal()?>&nbsp;</td>
                <td class="a-center"><?=$order->getStatus()?>&nbsp;</td>
                <td><a href="<?=$this->getUrl('customer/order/view', array('order'=>$order->getOrderId()))?>"><?=$this->__('View Order')?></a>&nbsp;</td>
            </tr>
        <?endforeach?>
        </tbody>
    </table>
<script type="text/javascript">decorateTable('my-orders-table')</script>
<?else:?>
    <p><?=$this->__('You have placed no orders yet.')?></p>
<?endif?>
    <div class="buttons-container">
        <a href="<?=$this->getUrl('customer/account')?>" class="float-left">&laquo; <?=$this->__('Back')?></a>
    </div>