<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<h2><?=$this->__('Wishlist')?></h2>
<?if($wishlist->getSize()):?>
<form action="<?=$this->getUrl('customer/wishlist/updatePost')?>" method="post">
    <table cellspacing="0" width="100%" class="data-table">
        <tr>
            <th class="align-left"><?=$this->__('Product')?></th>
            <th style="width:60px;" class="align-center"><?=$this->__('Status')?></th>
            <th style="width:60px;" class="align-center"><?=$this->__('To Cart')?></th>
            <th style="width:60px;" class="align-center"><?=$this->__('Remove')?></th>
        </tr>
        <?foreach($wishlist as $item):?>
        <tr>
            <td>
                <input type="hidden" value="1" name="wishlist[<?=$item->getItemId()?>]"/>
                <a href="<?=$this->getUrl('catalog/product/view/id/'.$item->getProduct()->getId())?>"><?=$item->getProduct()->getName()?></a>
            </td>
            <td class="align-center"><?=$item->getStatus()?></td>
            <td class="align-center"><input type="checkbox" value="1" name="to_cart[<?=$item->getItemId()?>]"/></td>
            <td class="align-center"><input type="checkbox" value="1" name="remove[<?=$item->getItemId()?>]"/></td>
        </tr>
        <?endforeach?>
    </table>
    <div class="buttons-container">
        <a href="<?=Mage::getBaseUrl()?>" class="float-left">&laquo; <?=$this->__('Continue Shopping')?></a>
        <input type="submit" value="<?=$this->__('Update')?>" class="input-button" name="do"/>
    </div>
</form>
<?else:?>
    <p><?=$this->__('You have placed no products yet.')?></p>
<?endif?>
