<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
            <td><h3><?=$this->getHeaderText()?></h3></td>
            <td class="form-buttons">
            	  <?=$this->getBackButtonHtml()?>
            	  <?if(!$this->getIsPreview()):?>
            	  <?=$this->getResetButtonHtml()?>
            	  <?if(!$this->getIsTextType()):?>
            	  <?endif?>
                  <?=$this->getSaveButtonHtml()?>
				  <?endif?>
				  <?if($this->getCanResume()):?>
				  <?=$this->getResumeButtonHtml()?>
				  <?endif?>
            </td>
        </tr>
    </table>
</div>
<form action="<?=$this->getSaveUrl()?>" method="POST" id="queue_edit_form">
<input type="hidden" name="_resume" id="_resume_flag" value="">
<?=$this->getChildHtml('form')?>
</form>
<script type="text/javascript">
<!--
var queueForm = new varienForm('queue_edit_form');

var queueControl = {
	save: function() {
		$('_resume_flag').value = '';
		queueForm.submit();
	},
	resume: function() {
		$('_resume_flag').value = '1';
		queueForm.submit();
	}
};
//-->
</script>