<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="entry-edit">
	<div class="entry-edit-head"><h4 class="icon-head head-customer-sales-statistics"><?=Mage::helper('customer')->__('Sales Statistics')?></h4></div>
    <div class="grid">
        <table cellspacing="0" class="data">
            <thead>
                <tr class="headings">
                    <th><?=Mage::helper('customer')->__('Website')?></th>
                    <th><?=Mage::helper('customer')->__('Store')?></th>
                    <th><?=Mage::helper('customer')->__('Store View')?></th>
                    <th><?=Mage::helper('customer')->__('Lifetime Sales')?></th>
                    <th><?=Mage::helper('customer')->__('Average Sale')?></th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <td colspan="3" class="label"><strong><big><?=Mage::helper('customer')->__('All Store Views')?></big></strong></td>
                    <td class="emph"><strong><big><?=$this->getPriceFormatted($this->getTotals()->getLifetime())?></big></strong></td>
                    <td class="emph"><strong><big><?=$this->getPriceFormatted($this->getTotals()->getAvgsale())?></big></strong></td>
                </tr>
            </tfoot>
            <?if ($this->getRows()):?>
            <tbody>
                <?$_i = 0;?>
                <?foreach ($this->getRows() as $_websiteId => $_groups):?>
                    <?$_websiteRow = false;?>
                    <?foreach ($_groups as $_groupId => $_stores):?>
                        <?$_groupRow = false;?>
                        <?foreach ($_stores as $_row):?>
                        <?if ($_row->getStoreId() == 0):?>
                        <td colspan="3" class="label"><?=$_row->getStoreName()?></td>
                        <?else:?>
                <tr <?=($_i++ % 2 ? 'class="even"' : '')?>>
                        <?if (!$_websiteRow):?>
                    <td rowspan="<?=$this->getWebsiteCount($_websiteId)?>"><?=$_row->getWebsiteName()?></td>
                            <?$_websiteRow = true;?>
                        <?endif;?>
                        <?if (!$_groupRow):?>
                    <td rowspan="<?=count($_stores)?>"><?=$_row->getGroupName()?></td>
                            <?$_groupRow = true;?>
                        <?endif;?>
                    <td class="label"><?=$_row->getStoreName()?></td>
                        <?endif;?>
                    <td><?=$this->getPriceFormatted($_row->getLifetime())?></td>
                    <td><?=$this->getPriceFormatted($_row->getAvgsale())?></td>
                </tr>
                        <?endforeach;?>
                    <?endforeach;?>
                <?endforeach;?>
            </tbody>
            <?endif;?>
        </table>
    </div>
</div>




















