<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?if ($_products = $this->getRecentlyComparedProducts()):?>
<div class="box base-mini mini-poll">
    <div class="head">
        <h4><span><?=$this->__('Recently Compared Products')?></span></h4>
    </div>
    <div class="content">
        <ol  id="recently-compared-items">
        <?foreach ($_products as $_item):?>
            <li><a href="<?=$_item->getProductUrl()?>"><?=$_item->getName()?></a></li>
        <?endforeach;?>
        </ol>
    </div>
    <script type="text/javascript">
    decorateList('recently-compared-items')
    </script>
</div>
<?endif;?>