<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?if (!($_shippingRateGroups = $this->getShippingRates())):?>
    <strong><?=$this->__('Sorry, no quotes are available for this order at this time.')?></strong>
<?else:?>
<dl class="shipment-methods">
    <?foreach ($_shippingRateGroups as $code => $_rates):?>
        <dt><?=$this->getCarrierName($code)?></dt>
        <dd>
            <ul>
            <?foreach ($_rates as $_rate):?>
                <li>
                   <?if ($_rate->getErrorMessage()):?>
	                <ul class="messages"><li class="error-msg"><ul><li><?=$_rate->getErrorMessage()?></li></ul></li></ul>
                   <?else:?>
                        <input name="shipping_method" type="radio" value="<?=$_rate->getCode()?>" id="s_method_<?=$_rate->getCode()?>"<?if($_rate->getCode()===$this->getAddressShippingMethod()) echo ' checked'?>/>
                        <label for="s_method_<?=$_rate->getCode()?>"><?=$_rate->getMethodDescription()?> - <strong><?=$_rate->getPrice()?></strong></label>
                   <?endif?>
                </li>
            <?endforeach;?>
            </ul>
        </dd>
    <?endforeach;?>
</dl>
<?endif;?>