<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div id="invoice_items_grid">
    <div class="grid">
        <table cellspacing="0" class="data" id="invoice_items_grid_table">
            <thead>
                <tr class="headings">
                    <th class="no-link"><nobr><?=Mage::helper('sales')->__('Product ID')?></nobr></th>
                    <th class="no-link"><nobr><?=Mage::helper('sales')->__('SKU')?></nobr></th>
                    <th class="no-link"><nobr><?=Mage::helper('sales')->__('Product Name')?></nobr></th>
                    <th class="no-link"><nobr><?=Mage::helper('sales')->__('Qty Shipped')?></nobr></th>
                </tr>
            </thead>
            <tbody>
                <?$_items = $this->getInvoice()->getItemsCollection()?>
                <?foreach ($_items as $_item):?>
                    <tr>
                        <td class="a-center"><?=$_item->getProductId()?></td>
                        <td><?=$_item->getSku()?></td>
                        <td><?=$_item->getName()?></td>
                        <td><?=$_item->getQty()?></td>
                    </tr>
                <?endforeach;?>
            </tbody>
        </table>
    </div>
</div>