<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div>
    <? $_order = $this->getOrder() ?>
    <div class="box-left">
        <div class="entry-view">
            <h4 class="icon-head head-order-date"><?=Mage::helper('sales')->__('Invoice Date: %s', $this->getOrderDateFormatted())?></h4>
        </div>
        <div class="entry-view">
            <h4 class="icon-head head-shipping-address"><?=Mage::helper('sales')->__('Shipping Address')?></h4>
            <div class="box customer-personal-brief">
                <?$_shipping = $_order->getShippingAddress()?>
                <address><?=$_shipping->getFirstname()?> <?=$_shipping->getLastname()?><br/>
                <?=$_shipping->getCompany()?><br/>
                <?=$_shipping->getStreet()?><br/>
                <?=$_shipping->getCity()?>, <?=$_shipping->getRegion()?> <?=$_shipping->getPostcode()?><br/>
                <strong>T</strong> | <?=$_shipping->getTelephone();
                if ($_shipping->getFax()):?><br /><strong>F</strong> | <?=$_shipping->getFax()?><?endif;?>
                </address>
            </div>
        </div>
        <div class="entry-view">
            <h4 class="icon-head head-shipping-method"><?=Mage::helper('sales')->__('Shipping Method')?></h4>
            <div class="box customer-personal-brief">
                <?=$_order->getShippingDescription()?>
            </div>
        </div>
    </div>
    <div class="box-right">
        <div class="entry-view">
            <h4 class="icon-head head-customer-view"><?=Mage::helper('sales')->__('Invoice Status: Paid')?></h4>
        </div>
        <div class="entry-view">
            <h4 class="icon-head head-billing-address"><?=Mage::helper('sales')->__('Billing Address')?></h4>
            <div class="box customer-personal-brief">
                <?$_billing = $_order->getbillingAddress()?>
                <address><?=$_billing->getFirstname()?> <?=$_billing->getLastname()?><br/>
                <?=$_billing->getCompany()?><br/>
                <?=$_billing->getStreet()?><br/>
                <?=$_billing->getCity()?>, <?=$_billing->getRegion()?> <?=$_billing->getPostcode()?><br/>
                <strong>T</strong> | <?=$_billing->getTelephone();
                if ($_billing->getFax()):?><br /><strong>F</strong> | <?=$_billing->getFax()?><?endif;?></address>
            </div>
        </div>
        <div class="entry-view">
            <h4 class="icon-head head-payment-method"><?=Mage::helper('sales')->__('Payment Method')?></h4>
            <div class="box customer-personal-brief">
                <?$_payment = $_order->getPayment()?>
                <?=$_payment->getMethod()?>: <?=$_payment->getCcType()?> xxxx<?=$_payment->getCcLast4()?>
            </div>
        </div>
    </div>
    <div class="clear"></div>
    <div class="entry-view">
        <h4 class="icon-head head-order-items"><?=Mage::helper('sales')->__('Items Ordered')?></h4>
    </div>
    <div>
        <?=$this->getItemsHtml()?>
    </div>
</div>