<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<p class="bug-report">
    <a href="http://www.magentocommerce.com/bug-tracking"><?=$this->__('Help Us Keep Magento Healthy - Report All Bugs')?></a><br/>
    <?=$this->__('Interface Locale: %s', $this->getLanguageSelect())?>
</p>
<p class="legality">
    <a href="http://www.magentocommerce.com" target="varien_external"><?=$this->__('Connect with the Magento Community')?></a><br/>
    <img src="<?=$this->getSkinUrl('images/varien_logo.gif')?>" class="v-middle">&nbsp;&nbsp;
    <?=$this->__('Magento &trade; is a registered Trademark of Irubin Consulting Inc. DBA Varien. &copy; Copyright 2007.')?>
</p>
<?=$this->__('Magento ver. %s', Mage::getVersion())?>
<script type="text/javascript">
    function setInterfaceLanguage(evt){
        var elem = Event.element(evt);
        if(elem){
            setLocation('<?=$this->getChangeLocaleUrl()?>locale/'+elem.value+'/<?=$this->getRefererParamName()?>/<?=$this->getUrlForReferer()?>');
        }
    }
    Event.observe('interface_locale', 'change', setInterfaceLanguage)
</script>