<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="header-top">
    <a href="<?=$this->getHomeLink()?>"><img src="<?=$this->getSkinUrl($this->__('images/logo.gif'))?>" alt="<?=$this->__('Magento Logo')?>" class="logo"/></a>
    <div class="header-right">
        <p class="super">
            <?=$this->__("Logged in as %s", $this->getUser()->getUsername())?><span class="separator">|</span><?=$this->__("Today is %s", $this->formatDate(null, 'long'))?><span class="separator">|</span><a href="<?=$this->getLogoutLink()?>" class="link-logout"><?=$this->__('Log Out')?></a><br/>
            <a href="http://www.magentocommerce.com" target="varien_external"><?=$this->__('Connect with the Magento Community')?></a>
        </p> 
        <?php if ( Mage::getSingleton('admin/session')->isAllowed('admin/global_search') ): ?>
        <fieldset>                                                                                      
            <legend>Search</legend>
            <span id="global_search_indicator" class="autocomplete-indicator" style="display: none">
                <img src="<?=$this->getSkinUrl('images/ajax-loader.gif')?>" alt="<?=$this->__('Loading...')?>" align="absmiddle"/>
            </span>
            <?$defSearch = $this->__('Global Record Search')?>
            <input id="global_search" name="query" type="text" class="input-text" value="<?if(!empty($query)):?><?=$query?><?else:?><?=$defSearch?><?endif?>" onfocus="if(this.value=='<?=$defSearch?>')this.value=''; " onblur="if(this.value=='')this.value='<?=$defSearch?>';" />
            <div id="global_search_autocomplete" class="autocomplete"></div>
            <script type="text/javascript">
                new Ajax.Autocompleter(
                    'global_search',
                    'global_search_autocomplete',
                    '<?=$this->getUrl('*/index/globalSearch')?>',
                    {
                        paramName:"query",
                        minChars:2,
                        indicator:"global_search_indicator",
                        updateElement:getSelectionId
                    }
                );
                function getSelectionId(li) {
                    location.href = li.getAttribute('url');
                }
            </script>
        </fieldset>
        <?php endif;?>
    </div>
</div>
