<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?if ($_entity = $this->getEntity()):?>
<div id="comments_block">
    <ul class="note-list">
    <?foreach ($_entity->getCommentsCollection() as $_comment):?>
        <li>
            <strong><?=$this->helper('core')->formatDate($_comment->getCreatedAt(), 'medium')?></strong>
            <?=$this->helper('core')->formatTime($_comment->getCreatedAt(), 'medium')?><span class="separator">|</span><small><?=$this->helper('sales')->__('Customer')?>
            <strong class="subdue">
            <?if ($_comment->getIsCustomerNotified()):?>
            <?=$this->helper('sales')->__('Notified')?>
            <img src="<?=$this->getSkinUrl('images/ico_success.gif')?>" width="16" height="16"/>
            <?else:?>
            <?=$this->helper('sales')->__('Not Notified')?>
            <?endif;?>
            </strong></small>
            <br/>
            <?=$_comment->getComment()?>
        </li>
    <?endforeach;?>
    </ul>
    <span class="field-row">
        <label class="normal" for="history_comment"><?=Mage::helper('sales')->__('Comment Text')?></label>
        <textarea name="comment[comment]" class="input-text" style="height:6em;width:99%" id="history_comment"></textarea>
    </span>
    <div class="f-left">
        <input name="comment[is_customer_notified]" type="checkbox" id="history_notify" value="1"/>
        <label class="normal" for="history_notify"><?=Mage::helper('sales')->__('Notify Customer')?></label>
    </div>
    <div class="f-right">
        <?=$this->getChildHtml('submit_button')?>
    </div>
    <div class="clear"></div>
<script type="text/javascript">
function submitComment() {
    submitAndReloadArea($('comments_block').parentNode, '<?=$this->getSubmitUrl()?>')
}

if ($('submit_comment_buttom')) {
    $('submit_comment_buttom').observe('click', submitComment);
}
</script>
</div>
<?endif;?>