<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?$_items = $this->getCreditmemo()->getAllItems()?>
<?if (count($_items)) :?>
<div class="grid">
    <table cellspacing="0" class="data" id="creditmemo_items_grid_table">
        <col/>
        <col width="100"/>
        <col width="100"/>
        <col width="60"/>
        <col width="100"/>
        <col width="100"/>
        <col width="100"/>
        <col width="100"/>
        <thead>
            <tr class="headings">
                <th><?=$this->helper('sales')->__('Product')?></th>
                <th><?=$this->helper('sales')->__('Price')?></th>
                <th><?=$this->helper('sales')->__('Qty')?></th>
                <th><?=$this->helper('sales')->__('Qty to Refund')?></th>
                <th><?=$this->helper('sales')->__('Subtotal')?></th>
                <th><?=$this->helper('sales')->__('Tax Amount')?></th>
                <th><?=$this->helper('sales')->__('Discount Amount')?></th>
                <th class="last"><?=$this->helper('sales')->__('Row Total')?></th>
            </tr>
        </thead>
        <tbody>
            <?$_i=0;foreach ($_items as $_item):$_i++?>
                <tr class="<?=$_i%2?'odd':'even'?>">
                    <td>
                        <?=$_item->getName()?>
                        <div class="nobr"><strong><?=$this->helper('sales')->__('SKU')?>:</strong> <?=$_item->getSku()?></div>
                    </td>
                    <td class="price"><?=$this->formatPrice($_item->getPrice())?></td>
                    <td><?=$this->getQtyHtml($_item->getOrderItem())?></td>
                    <td class="a-center">
                    <?if ($this->canEditQty()) :?>
                        <input type="text" class="input-text qty-input" name="creditmemo[items][<?=$_item->getOrderItemId()?>]" value="<?=$_item->getQty()*1?>"/>
                    <?else :?>
                        <?=$_item->getQty()*1?>
                    <?endif;?>
                    </td>
                    <td class="price"><?=$this->formatPrice($_item->getRowTotal())?></td>
                    <td class="price"><?=$this->formatPrice($_item->getTaxAmount())?></td>
                    <td class="price"><?=$this->formatPrice(-$_item->getDiscountAmount())?></td>
                    <td class="last price">
                        <?=$this->formatPrice($_item->getRowTotal()+$_item->getTaxAmount()-$_item->getDiscountAmount())?>
                    </td>
                </tr>
            <?endforeach;?>
        </tbody>
        <?if ($this->canEditQty()):?>
        <tfoot>
            <tr>
                <td colspan="2"></td>
                <td colspan="3" class="a-center">
                    <?=$this->getUpdateButtonHtml()?>
                </td>
                <td colspan="3" class="last"></td>
            </tr>
        </tfoot>
        <?endif;?>
    </table>
</div>
<?else :?>
    <div class="entry-edit">
        <fieldset><center><?=$this->helper('sales')->__('No Items To Refund')?></center></fieldset>
    </div>
<?endif;?>

<div class="clear">&nbsp;</div>
<?=$this->getChildHtml('totals_bar')?>
<div class="clear">&nbsp;</div>

<input type="hidden" name="creditmemo[do_offline]" id="creditmemo_do_offline" value="0"/>

<table class="order-info-foot" cellpadding="10" cellspacing="0" width="100%">
    <tbody>
        <tr>
            <td class="section">
                <table id="comments_block" cellpadding="0" width="100%">
                    <tbody>
                        <tr>
                            <td style="padding-right: 30px;" width="50%"></td>
                            <td>
                                <div id="history_form" class="order-history-form">
                                    <span class="field-row">
                                        <label class="normal" for="history_comment"><?=Mage::helper('sales')->__('Credit Memo Comment')?></label>
                                        <textarea name="creditmemo[comment_text]" class="input-text" style="height: 6em; width: 99%;"></textarea>
                                    </span>
                                    <div class="left">
                                        <input name="creditmemo[comment_customer_notify]" id="notify_customer" value="1" type="checkbox">
                                        <label class="normal" for="notify_customer"><?=Mage::helper('sales')->__('Notify Customer')?></label>
                                    </div>
                                    <div class="clear"></div>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </td>

            <td class="document-totals section">
                <?=$this->getChildHtml('totals')?>
                <div class="divider"></div>
                <div class="a-right">
                    <?=$this->getChildHtml('submit_offline')?>
                    <?=$this->getChildHtml('submit_button')?>
                </div>
            </td>
        </tr>
    </tbody>
</table>

<script type="text/javascript">
var submitButtons = document.getElementsByClassName('submit-button');
var updateButtons = document.getElementsByClassName('update-button');
var fields = document.getElementsByClassName('qty-input');

updateButtons.each(function (elem) {elem.disabled=true;elem.addClassName('disabled');});

for(var i=0;i<fields.length;i++){
    fields[i].observe('change', checkButtonsRelation)
    fields[i].baseValue = fields[i].value;
}

function checkButtonsRelation() {
    var hasChanges = false;
    fields.each(function (elem) {
        if (elem.baseValue != elem.value) {
            hasChanges = true;
        }
    }.bind(this));
    if (hasChanges) {
        submitButtons.each(function (elem) {elem.disabled=true;elem.addClassName('disabled');});
        updateButtons.each(function (elem) {elem.disabled=false;elem.removeClassName('disabled');});
    }
    else {
        submitButtons.each(function (elem) {elem.disabled=false;elem.removeClassName('disabled');});
        updateButtons.each(function (elem) {elem.disabled=true;elem.addClassName('disabled');});
    }
}

function submitCreditMemo() {
    if ($('creditmemo_do_offline')) $('creditmemo_do_offline').value=0;
    editForm.submit()
}
function submitCreditMemoOffline() {
    if ($('creditmemo_do_offline')) $('creditmemo_do_offline').value=1;
    editForm.submit()
}
</script>