<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="content-header">
    <div class="grid-header">
		<h3><?=Mage::helper('tax')->__('Tax Rates Import / Export')?></h3>
	</div>
</div>

<div class="entry-edit">
	<table cellspacing="10" border="0" width="100%">
		<tr><td width="50%">
			<form id="import_form" action="<?=$this->getUrl('*/*/importPost')?>" method="POST" enctype="multipart/form-data">
			<h4 class="icon-head head-edit-form fieldset-legend"><?=Mage::helper('tax')->__('Import Tax Rates')?></h4>
			<fieldset>
				<legend><?=Mage::helper('tax')->__('Import Tax Rates')?></legend>
				<input type="file" name="import_rates_file" class="input-file required-entry"/>
		    	<?=$this->getButtonHtml('Import Tax Rates', "this.form.submit()")?>
			</fieldset>
			</form>
			<script>
				var importForm = new varienForm('import_form');
			</script>
		</td><td width="50%">
			<form id="export_form" action="<?=$this->getUrl('*/*/exportPost')?>" method="POST" enctype="multipart/form-data">
			<h4 class="icon-head head-edit-form fieldset-legend"><?=Mage::helper('tax')->__('Export Tax Rates')?></h4>
			<fieldset>
				<legend><?=Mage::helper('tax')->__('Export Tax Rates')?></legend>
		        <?=$this->getButtonHtml('Export Tax Rates', "this.form.submit()")?>
		    </fieldset>	
			</form>
    	</td></tr>
    </table>
</div>