<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<script type="text/javascript" language="javascript">

var countryModel = Class.create();
countryModel.prototype = {
    initialize : function()
    {
        this.reload = false;
        this.bindSpecificCountryRelation();
    },
    bindSpecificCountryRelation : function(parentId)
    {
        if(parentId) {
            // todo: fix bug in IE
            var applyCountryElements = $$('#'+parentId+' .shipping-applicable-country');
        } else {
            var applyCountryElements = $$('.shipping-applicable-country');
        }
        for(var i in applyCountryElements) {
            Event.observe(applyCountryElements[i], 'change', this.checkSpecificCountry.bind(this));
            this.initSpecificCountry(applyCountryElements[i]);
        }
        
    },
    initSpecificCountry : function(element){
        var applyCountryElement = element;
        if (applyCountryElement && applyCountryElement.id) {
            var specifCountryElement  = $(applyCountryElement.id.replace(/allowall/, 'specificcountry'));    
            var showMethodElement  = $(applyCountryElement.id.replace(/allowall/, 'showmethod'));
            var specifErrMsgElement  = $(applyCountryElement.id.replace(/allowall/, 'specificerrmsg'));   
            if (specifCountryElement) {
                if (applyCountryElement.value == 1) {                   
                   specifCountryElement.disable(); 
                   showMethodElement.up(1).hide();   
                   specifErrMsgElement.up(1).hide();                   
                } else {
                   specifCountryElement.enable(); 
                   showMethodElement.up(1).show();   
                   specifErrMsgElement.up(1).show();   
                }
            }
        }
    },    
    
    checkSpecificCountry : function(event)
    {
        var applyCountryElement = Event.element(event);
        if (applyCountryElement && applyCountryElement.id) {
            var specifCountryElement  = $(applyCountryElement.id.replace(/allowall/, 'specificcountry'));
            var showMethodElement  = $(applyCountryElement.id.replace(/allowall/, 'showmethod'));
            var specifErrMsgElement  = $(applyCountryElement.id.replace(/allowall/, 'specificerrmsg'));
            if (specifCountryElement) {            
                if (applyCountryElement.value == 1) {
                    this.unselectSpecificCountry(specifCountryElement); 
                    specifCountryElement.disable();  
                    showMethodElement.up(1).hide();   
                    specifErrMsgElement.up(1).hide(); 
                } else {
                   specifCountryElement.enable();  
                   showMethodElement.up(1).show();   
                   specifErrMsgElement.up(1).show();                   
                }
            }
        }
    },
    
    unselectSpecificCountry : function(element)
    {
        for (var i=0; i<element.options.length; i++) {
            if (element.options[i].selected) {
              element.options[i].selected=false;;
            }
        }        
    }
    
}
countryApply = new countryModel();
</script>
