<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?
/**
 * @see Mage_Page_Block_Template_Links
 */
?>
<?$_links = $this->getLinks();?>
<?if(count($_links)>0):?>
    <div>
        <ul id="<?=$this->getName()?>">
            <?foreach($_links as $_link):?>
                <li<?if($_link->getIsFirst()):?> class="first"<?elseif($_link->getIsLast()):?> class="last"<?endif;?><?=$_link->getLiParams()?>><?=$_link->getBeforeText()?><a href="<?=$_link->getUrl()?>" title="<?=$_link->getTitle()?>" <?=$_link->getAParams()?>><?=$_link->getLabel()?><?=$_link->getAfterText()?></a></li>
            <?endforeach;?>
        </ul>
   </div>
<?endif;?>
