<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?
/**
 * Super product options
 * 
 * @see Mage_Catalog_Block_Product_View_Super_Config
 */
?>
<div class="product-attributes">
    <table cellspacing="0">
    <?foreach($this->getAllowAttributes() as $_attribute):?>
        <tr>
            <td class="label">
                <?=$_attribute['label']?>:
            </td>
            <td>
                <select name="super_attribute[<?=$_attribute['attribute_id']?>]" id="attribute<?=$_attribute['attribute_id']?>" class="required-entry super-attribute select super-attribute-select">
                    <option><?=$this->__('Choose an Option...')?></option>
                </select>
            </td>
        </tr>
    <?endforeach;?>
    </table>
    <input type="hidden" name="" id=""/>
</div>
<script type="text/javascript">
var spConfig = new Product.Config(<?=$this->getJsonConfig()?>);
</script>
