<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<table cellspacing="0" class="data-table" id="super-product-table">
    <thead>
        <tr>
            <th><?=$this->__('Product Name')?></th>
            <th><?=$this->__('SKU')?></th>
            <th class="a-right"><?=$this->__('Price')?></th>
            <th class="a-center"><?=$this->__('Qty')?></th>
        </tr>
    </thead>
    <tbody>
    <?if ($this->getItems()->getSize()):?>
    <?foreach ($this->getItems() as $_item):?>
        <tr>
            <td><?=$_item->getName()?></td>
            <td><?=$_item->getSku()?></td>
            <td class="a-right"><?=$_item->getFormatedPrice()?></td>
            <td class="a-center"><input type="text" class="input-text qty" name="super_group[<?=$_item->getLinkedProductId()?>]" value="<?=$this->filterQty($_item->getQty())?>"/></td>
        </tr>
    <?endforeach;?>
    <?else:?>
       <tr>
           <td colspan="4"><?=$this->__('No options of this product are available.')?></td>
       </tr>
    <?endif;?>
    </tbody>
</table>
<script type="text/javascript">decorateTable('super-product-table')</script>
