<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?
/**
 * Template for Mage_Page_Block_Html
 */
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <title><?=$this->__('Magento Installation Wizard')?></title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link rel="icon" href="<?=$this->getBaseUrl()?>favicon.ico" type="image/x-icon"/>
    <link rel="shortcut icon" href="<?=$this->getBaseUrl()?>favicon.ico" type="image/x-icon"/>
    <script type="text/javascript" src="<?=$this->getJsUrl()?>prototype/prototype.js" ></script>
    <script type="text/javascript" src="<?=$this->getJsUrl()?>prototype/validation.js" ></script>
    <script type="text/javascript" src="<?=$this->getJsUrl()?>mage/translate.js" ></script>
    <script type="text/javascript" src="<?=$this->getJsUrl()?>varien/js.js" ></script>
    <script type="text/javascript" src="<?=$this->getJsUrl()?>varien/form.js" ></script>
    <link rel="stylesheet" href="<?=$this->getSkinUrl('css/styles.css')?>" type="text/css" media="all"/>
    <!--[if IE]><link rel="stylesheet" href="<?=$this->getSkinUrl('css/iestyles.css')?>" type="text/css" media="all"/><![endif]-->
    <!--[if lt IE 7]>
        <link rel="stylesheet" href="<?=$this->getSkinUrl('css/ie7minus.css')?>" type="text/css" media="all"/>
        <script type="text/javascript" src="<?=$this->getJsUrl()?>lib/ds-sleight.js" ></script>
        <script type="text/javascript" src="<?=$this->getJsUrl()?>varien/iehover-fix.js" ></script>
    <![endif]-->

    <link rel="stylesheet" href="<?=$this->getSkinUrl('css/clears.css')?>" type="text/css" media="print" />
    <link rel="stylesheet" href="<?=$this->getSkinUrl('css/print.css')?>" type="text/css" media="all" />
</head>

<body>
<!-- [start] header -->
    <div class="header">
        <div class="header-top-container">
            <div class="header-top">
                <h1 id="logo">
                    <a href="<?=$this->getUrl('')?>"><img src="<?=$this->getSkinUrl('images/logo.gif')?>" alt="<?=$this->__('Magento')?>"/></a>
                </h1>

                <?=$this->getChildHtml('topSearch')?>

                <div class="quick-access">
                    <div class="account-access">
                       <strong><?=$this->getWelcome()?></strong> <?=$this->getChildHtml('topLeftLinks')?>
                    </div>
                    <div class="shop-access">
                        <?=$this->getChildHtml('topRightLinks')?>
                    </div>
                </div>

            </div>
        </div>
        <?=$this->getChildHtml('topMenu')?>
    </div>
<!-- [end] header -->

        <!-- [start] middle -->
       <?=$this->getChildHtml('store')?>
    <div class="middle-container">
        <div class="middle col-2-left-layout">
            <?=$this->getChildHtml('breadcrumbs')?>



            <!-- [start] left -->
            <div class="col-left side-col">
                <?=$this->getChildHtml('left')?>&nbsp;
            </div>
            <div id="main" class="col-main">
            <!-- [start] global messages -->
                <?=$this->getChildHtml('global_messages')?>
            <!-- [end] global messages -->
            <!-- [start] content -->
                <?=$this->getChildHtml('content')?>
            <!-- [end] content -->
            </div>
        </div>
            <!-- [end] center -->
    </div>
        <!-- [end] middle -->

        <!-- [start] footer -->
    <div class="footer-container">
        <div class="footer">
        <p class="legality">
            <?=$this->__('Help Us to Keep Magento Healthy')?> - <a href="http://www.magentocommerce.com/bug-tracking" target="varien_external"><strong><?=$this->__('Report All Bugs')?></strong></a> <?=$this->__('(ver. %s)', Mage::getVersion())?><br/>
            <?=$this->__('Magento&trade; is a registered Trademark of Irubin Consulting Inc. DBA Varien. &copy; Copyright 2007')?>
        </p>
        </div>
    </div>
        <!-- [end] footer -->
    </body>
</html>