<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?if($this->canDisplayContainer()):?>
<div id="<?=$this->getHtmlId()?>" class="item-container left">
<?endif;?>
<?if($this->canDisplayGiftmessage()):?>
<div class="item-text">
    <div><?=$this->htmlEscape($this->getEntity()->getName())?></div>
    <div><strong><?=$this->helper('sales')->__('SKU')?>:</strong> <?=$this->getEntity()->getSku()?></div>
    <div>
        <a class="action-link" href="#" onclick="return giftMessagesController.toogleGiftMessage('<?=$this->getHtmlId()?>')">
        <span class="default-text">
            <?if(!$this->getMessage()->getId()):?>
                <?=$this->helper('sales')->__('Add Gift Messsage')?>
            <?else:?>
                <?=$this->helper('sales')->__('Edit Gift Messsage')?>
            <?endif?>
        </span>
        <span class="close-text" style="display:none">
            <?=$this->helper('sales')->__('Save and Close Message')?>
        </span>
        </a>
    </div>
</div>
<div class="gift-form" style="display:none;" id="<?=$this->getFieldId('edit')?>">
<form id="<?=$this->getFieldId('form')?>" action="<?=$this->getSaveUrl()?>">
    <div class="entry-edit">
        <fieldset>
            <input type="hidden" id="<?=$this->getFieldId('type')?>" name="<?=$this->getFieldName('type')?>" value="order_item"/>
            <span class="field-row left">
                <label><?=$this->helper('sales')->__('From Name')?></label><br />
                <input class="input-text" type="text" id="<?=$this->getFieldId('sender')?>" name="<?=$this->getFieldName('sender')?>" value="<?=$this->htmlEscape($this->getMessage()->getSender())?>"/>
            </span>
            <span class="field-row left last">
                <label><?=$this->helper('sales')->__('To Name')?></label><br />
                <input class="input-text" type="text" id="<?=$this->getFieldId('recipient')?>" name="<?=$this->getFieldName('recipient')?>"  value="<?=$this->htmlEscape($this->getMessage()->getRecipient())?>"/>
            </span>
            <div class="clear"></div>
            <span class="field-row">
                <label><?=$this->helper('sales')->__('Gift Message')?></label><br />
                <textarea class="input-text" id="<?=$this->getFieldId('message')?>" onchange="giftMessagesController.toogleRequired('<?=$this->getFieldId('message')?>', ['<?=$this->getFieldId('sender')?>','<?=$this->getFieldId('recipient')?>']);" name="<?=$this->getFieldName('message')?>"><?=$this->htmlEscape($this->getMessage()->getMessage())?></textarea>
            </span>
        </fieldset>
    </div>
</form>
</div>
<?else:?>
<div class="item-text"><?=$this->htmlEscape($this->getEntity()->getName())?></div>
<?endif;?>
<?if($this->canDisplayContainer()):?>
</div>
<?endif?>