<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?foreach ($this->getWebsiteCollection() as $_website):?>
    <?$_storesCollection=$_website->getStoreCollection()->load()?>
    <?if($_storesCollection->getSize()):?>
    <h3><?=$_website->getName()?></h3>
    <?foreach ($_storesCollection as $_store):?>
        <span class="field-row">
            <input type="radio" id="store_<?=$_store->getId()?>" class="new-store" onclick="order.setStoreId('<?=$_store->getId()?>')"/>
            <label for="store_<?=$_store->getId()?>" class="normal"><?=$_store->getName()?></label>
        </span>
    <?endforeach;?>
    <?endif;?>
<?endforeach;?>