<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
    <?=$this->getMessagesBlock()->getGroupedHtml()?>
    <form action="<?=$action?>" method="post" id="form-validate">
    <fieldset class="group-select">
        <legend><?=$this->__('Change Account Password')?></legend>
        <ul>
            <li>
                <div class="input-box">
                    <label for="current_password"><?=$this->__('Current Password')?> <span class="required">*</span></label><br/>
                    <input type="password" class="required-entry input-text" name="current_password" id="current_password"/>
                </div>
                        </li>
            <li>
                <div class="input-box">
                    <label for="password"><?=$this->__('New Password')?> <span class="required">*</span></label><br/>
                    <input type="password" class="required-entry validate-password input-text" name="password" id="password"/>
                </div>
                <div class="input-box">
                    <label for="confirmation"><?=$this->__('Confirm New Password')?> <span class="required">*</span></label><br/>
                    <input type="password" class="required-entry validate-cpassword input-text" name="confirmation" id="confirmation"/>
                </div>
            </li>
        </ul>
    </fieldset>
    <div class="form-buttons">
        <p class="required"><?=$this->__('* Required Fields')?></p>
        <a href="<?=$this->getUrl('customer/account')?>" class="float-left">&laquo; <?=$this->__('Back')?></a>
        <button class="form-button" type="submit"><span><?=$this->__('Save Password')?></span></button>
    </div>
    </form>
    <script type="text/javascript">
        var dataForm = new VarienForm('form-validate');
    </script>