<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?
/**
 * Customer login form template
 * 
 * @see Mage_Customer_Block_Form_Login
 */
?>
<div class="page-head">
    <h3><?=$this->__('Login or Create an Account')?></h3>
</div>
<?=$this->getMessagesBlock()->getGroupedHtml()?>
<form action="<?=$this->getPostActionUrl()?>" method="post" id="login-form">
<div class="col2-set login-box">
    <div class="col-1 new-users">
        <div class="content">
            <h4><?=$this->__('New Customers')?></h4>
            <p><?=$this->__('By creating an account with our store, you will be able to move through the checkout process faster, store multiple shipping addresses, view and track your orders in your account and more.')?></p>
        </div>
        <div class="button-set">
            <button class="form-button right" onclick="window.location='<?=$this->getCreateAccountUrl()?>';" type="button"><span><?=$this->__('Create an Account')?></span></button>
        </div>
    </div>
    <div class="col-2 registered-users">
        <div class="content">
            <h4><?=$this->__('Registered Customers')?></h4>
            <p><?=$this->__('If you have an account with us, please log in.')?></p>
            <ul class="form-list">
                    <li>
                        <label for="email"><?=$this->__('Email Address')?> <span class="required">*</span></label><br/>
                        <input name="login[username]" value="<?=$this->htmlEscape($this->getUsername())?>" title="<?=$this->__('Email Address')?>" id="email" type="text" class="input-text required-entry" style="width:250px;"/>
                    </li>
                    <li>
                        <label for="pass"><?=$this->__('Password')?> <span class="required">*</span></label><br/>
                        <input name="login[password]" type="password" class="input-text required-entry validate-password" id="pass" style="width:250px;"/>
                    </li>
                </ul>
                <p class="required"><?=$this->__('* Required Fields')?></p>
    </div>
    <div class="button-set">
        <a href="<?=$this->getForgotPasswordUrl()?>" class="left"><?=$this->__('Forgot Your Password?')?></a>
        <button class="form-button" type="submit" name="send" id="send2"><span><?=$this->__('Login')?></span></button>
    </div>
</div>
</div>
</form>
<script type="text/javascript">
    var dataForm = new VarienForm('login-form', true);
</script>