<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?
/**
 * Template for block Mage_Adminhtml_Block_Customer_Edit_Tab_View
 */
?>
<div class="box-left">
	<h4 class="icon-head head-customer-view"><?=Mage::helper('customer')->__('Personal Information')?></h4>
	<div class="box customer-personal-brief">
		<p><?=Mage::helper('customer')->__('Last Log In: %s (%s)', $this->getLastLoginDate(), $this->getCurrentStatus())?><br/>
		<?=Mage::helper('customer')->__('Account Created on: %s', $this->getCreateDate())?><br/>
		<?=Mage::helper('customer')->__('Account Created in: %s', $this->getCreatedInStore())?><br/>
		<?=Mage::helper('customer')->__('Customer Group: %s', $this->getGroupName())?></p>
		<address>
		<strong><?=Mage::helper('customer')->__('Primary Billing Address')?></strong><br/>
		<?=$this->getBillingAddressHtml()?>
	</div>
</div>
<?=$this->getSalesHtml();?>
<div class="clear"></div>
<br/>
<?=$this->getAccordionHtml()?>