<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="entry-edit">
    <h4 class="icon-head head-edit-form fieldset-legend"><?=Mage::helper('catalog')->__('Product Categories')?></h4>
    <fieldset id="grop_fields">
        <input type="hidden" name="categories" id="product_categories" value="">
        <div id="tree-div" class="tree"></div>
    </fieldset>
</div>
<?if($this->getRootNode() && $this->getRootNode()->hasChildren()):?>
<script type="text/javascript">
Ext.EventManager.onDocumentReady(function() {
	var tree = new Ext.tree.TreePanel('tree-div', {
        animate:false, 
        loader: false,
        enableDD:false,
        containerScroll: true,
		rootUIProvider: Ext.tree.CheckboxNodeUI,
		selModel: new Ext.tree.CheckNodeMultiSelectionModel(),
		rootVisible: '<?=$this->getRootNode()->getIsVisible()?>'
	});
	
	tree.on('check', function() {
		$('product_categories').value = this.getChecked().join(',');
	}, tree);

	// set the root node
    var root = new Ext.tree.TreeNode({
        text: '<?=$this->getRootNode()->getName()?>',
        draggable:false,
        checked:'<?=$this->getRootNode()->getChecked()?>',
        id:'<?=$this->getRootNode()->getId()?>',
        uiProvider: Ext.tree.CheckboxNodeUI
    });

	tree.setRootNode(root);
	bildCategoryTree(root, <?=$this->getTreeJson()?>);
    tree.addListener('click', categoryClick.createDelegate(this));
	
    // render the tree
    tree.render();
    root.expand();
    tree.expandAll();
    
    $('product_categories').value = tree.getChecked().join(',');
});

function bildCategoryTree(parent, config){
    if (!config) return null;
	
    if (parent && config && config.length){
        for (var i = 0; i < config.length; i++){
            config[i].uiProvider = Ext.tree.CheckboxNodeUI;
            var node = new Ext.tree.TreeNode(config[i]);
            parent.appendChild(node);
            if(config[i].children){
                bildCategoryTree(node, config[i].children);
            }
        }
    }	    
}

function categoryClick(node, e){
    node.getUI().check(!node.getUI().checked())
    varienElementMethods.setHasChanges(Event.element(e), e);
};
</script>
<?endif;?>