<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?=Mage::helper('catalog')->__('Product In Websites')?></h4>
    </div>
    <fieldset id="grop_fields">
    <?if($this->getProductId()):?>
        <ul class="messages">
            <li class="notice-msg">
                <ul>
                    <li><?=Mage::helper('catalog')->__("Items that you don't want to show in the catalog or search results should have status 'Disabled' in the desired store.")?></li>
                </ul>
            </li>
        </ul>
    <?endif;?>
    <?foreach ($this->getWebsiteCollection() as $_website):?>
    <div>
        <div class="website-name">
            <input name="product[website_ids][]" value="<?=$_website->getId()?>" class="website-checkbox" id="product_website_<?=$_website->getId()?>" type="checkbox"<?if($this->hasWebsite($_website->getId())):?> checked<?endif;?>/>
            <big><strong><label for="product_website_<?=$_website->getId()?>"><?=$_website->getName()?></label></big></strong>
        </div>
        <div class="webiste-groups" id="product_website_<?=$_website->getId()?>_data">
        <?foreach ($this->getGroupCollection($_website) as $_group):?>
            <h4><?=$_group->getName()?></h4>
            <div class="group-stores">
            <table>
            <?foreach ($this->getStoreCollection($_group) as $_store):?>
                <tr>
                    <td><?=$_store->getName()?></td>
                    <td>
                    <?if($this->getWebsites() && !$this->hasWebsite($_website->getId())):?>
                        <span class="website-<?=$_website->getId()?>-select" style="display:none">
                        <?=Mage::helper('catalog')->__('(Copy data from: %s)', $this->getChooseFromStoreHtml($_store))?>
                        </span>
                    <?endif;?>
                    </td>
                </tr>
            <?endforeach;?>
            </table>
            </div>
        <?endforeach;?>
        </div>
    </div>
    <?endforeach;?>
</div>
<script type="text/javascript">
    var productWebsiteCheckboxes = $$('.website-checkbox');

    for(var i=0;i<productWebsiteCheckboxes.length;i++){
        Event.observe(productWebsiteCheckboxes[i], 'click', toggleStoreFromChoosers);
    }

    function toggleStoreFromChoosers(event){
        var element = Event.element(event);
        var selects = $('product_website_'+element.value+'_data').getElementsBySelector('select');
        var selectBlocks = $('product_website_'+element.value+'_data').getElementsByClassName('website-'+element.value+'-select');
        for (var i=0; i<selects.length; i++) {
            selects[i].disabled=!element.checked;
        }
        for (var i=0; i<selectBlocks.length; i++) {
            if (element.checked) {
                selectBlocks[i].show();
            }
            else {
                selectBlocks[i].hide();
            }
        }
    }
</script>