<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html lang="en">
<head>
    <title><?=Mage::helper('adminhtml')->__('Log into Magento Admin Page')?></title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" ></meta>
    <style type="text/css" media="all">
        /*<![CDATA[*/ @import "<?=$this->getSkinUrl('styles.css')?>"; /*]]>*/
    </style>
    <script type="text/javascript" src="<?=$this->getJsUrl()?>prototype/prototype.js"></script>
    <script type="text/javascript" src="<?=$this->getJsUrl()?>prototype/validation.js"></script>
    <script type="text/javascript" src="<?=$this->getSkinUrl('js/form.js')?>"></script>

    <!--[if IE]> <link rel="stylesheet" href="<?=$this->getSkinUrl('iestyles.css')?>" type="text/css" media="all" /> <![endif]-->
    <!--[if lt IE 7]> <link rel="stylesheet" href="<?=$this->getSkinUrl('below_ie7.css')?>" type="text/css" media="all" /> <![endif]-->
    <!--[if IE 7]> <link rel="stylesheet" href="<?=$this->getSkinUrl('ie7.css')?>" type="text/css" media="all" /> <![endif]-->
</head>
<body id="page-login">
    <div class="login-container">
        <div class="login-box">
            <form method="post" action="" id="loginForm">

                <fieldset class="login-form">
                    <h2><?=Mage::helper('adminhtml')->__('Log in to Admin Panel')?></h2>
                    <div id="messages">
                        <?=$this->getMessagesBlock()->getGroupedHtml()?>
                    </div>
                    <div class="input-box"><label for="#"><?=Mage::helper('adminhtml')->__('User Name:')?></label><br/>
                        <input type="text" name="login[username]" value="<?=$username?>" class="required-entry input-text"/></div>
                    <div class="input-box"><label for="#"><?=Mage::helper('adminhtml')->__('Password:')?></label><br/>
                        <input type="password" name="login[password]" type="password" class="required-entry input-text" value="" /></div>
                    <div class="clear"></div>
                    <div class="form-buttons">
                        <input onclick="loginForm.submit()" type="image" src="<?=$this->getSkinUrl('images/btn_login.gif')?>" value="<?=Mage::helper('adminhtml')->__('Login')?>"/>
                    </div>
                </fieldset>
                <p class="legal"><?=Mage::helper('adminhtml')->__('&copy; Copyright 2007 Varien. Magento is a trademark of Irubin Consulting Inc')?></p>
            </form>
            <div class="bottom"></div>
            <script type="text/javascript">
                 var loginForm = new varienForm('loginForm');
            </script>
        </div>
    </div>
</body>
</html>

