<?if($this->getIsShipping()):
    $_fieldsContainerId = 'order:shipping_address_fields';
    ?>
    <script type="text/javascript">
    order.shippingAddressContainer = '<?=$_fieldsContainerId?>';
    order.setAddresses(<?=$this->getAddressCollectionJson()?>);
    </script>
    <?
else:
    $_fieldsContainerId = 'order:billing_address_fields';
    ?>
    <script type="text/javascript">
    order.billingAddressContainer = '<?=$_fieldsContainerId?>';
    </script>
    <?
endif;?>
<div class="entry-edit">
    <h4 class="icon-head fieldset-legend <?=$this->getHeaderCssClass()?>"><?=$this->getHeaderText()?></h4>

    <fieldset class="np">
    <div class="order-choose-address">
        <?//if($this->getAddressCollection()->getSize()):?>
        <?=Mage::helper('sales')->__('Select from existing customer addresses:')?><br/>
        <?$_id = $this->getForm()->getHtmlIdPrefix() . 'customer_address_id'?>
        <select id="<?=$_id?>" style="width:95%;" onchange="order.selectAddress(this.value, '<?=$_fieldsContainerId?>')">
            <option value=""><?=Mage::helper('sales')->__('Add New Address')?></option>
            <?foreach ($this->getAddressCollection() as $_address):?>
            <option value="<?=$_address->getId()?>"<?if($_address->getId()==$this->getAddressId()):?> selected<?endif?>>
                <?=$this->getAddressAsString($_address)?>
            </option>
            <?endforeach;?>
        </select>
        <br/>
        <?//endif;?>
        <?if($this->getIsShipping()):?>
            <input type="checkbox" id="order:shipping_same_as_billing" name="shipping_same_as_billing" onchange="order.setShippingAsBilling(this.checked)" <?if($this->getIsAsBilling()):?>checked<?endif;?>/>
            <label for="order:shipping_same_as_billing" class="no-float"><?=Mage::helper('sales')->__('Same As Billing Address')?></label>
        <?else:?>
            &nbsp;
        <?endif;?>
    </div>

    <div class="content order-address" id="<?=$_fieldsContainerId?>">
        <?=$this->getForm()->toHtml()?>
    </div>
    <script type="text/javascript">
        order.bindAddressFields('<?=$_fieldsContainerId?>')
        <?if($this->getIsShipping() && $this->getIsAsBilling()):?>
        order.disableShippingAddress(true);
        <?endif;?>
    </script>
    </fieldset>
</div>