<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?if($this->getItems()->getSize()):?>
<div class="box base-mini cross-sell">
    <div class="head">
        <h4><span><?=$this->__('Cross-sell Products')?></span></h4>
    </div>
    <ol id="cross-sell-products">
     <?foreach($this->getItems() as $_item):?>
        <li>
            <div class="product-images">
                <a href="<?=$_item->getProductUrl()?>"><img src="<?=$_item->getThumbnailUrl()?>" alt="<?=$this->htmlEscape($_item->getName())?>" width="38" height="38"/></a>
            </div>
            <div class="product-details">
                <a href="#"><a href="<?=$_item->getProductUrl()?>"><?=$_item->getName()?></a>
                <?=$this->helper('catalog/product')->getPriceHtml($_item)?>
                <a href="<?=$this->getAddToCartUrl($_item)?>"><?=$this->__('Add to Cart')?></a>
                <?if ($this->helper('wishlist')->isAllow()) :?>
                <a href="<?=$this->getAddToWishlistUrl($_item)?>"><?=$this->__('Add to Wishlist')?></a>
                <?endif;?>
            </div>
        </li>
    <?endforeach;?>
    </ol>
    <script type="text/javascript">decorateList('cross-sell-products')</script>
</div>
<?endif?>
