<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?if($this->getItems()->getSize()):?>
<div class="box base-mini mini-related-items">
    <div class="head">
        <h4><?=$this->__('Related Products')?></h4>
    </div>
    <div class="content">
        <p><strong><?=$this->__('Check items to add to the cart or select all.')?></strong></p>
        <ol>
        <?foreach($this->getItems() as $_item):?>
        <li<?if($_item->isSuper() || !$_item->isSaleable()):?> class="super-products"<?endif;?>>
            <div class="product-images">
            <?if(!$_item->isSuper() && $_item->isSaleable()):?>
                <input type="checkbox" class="related-checkbox left" id="related-checkbox<?=$_item->getId()?>" name="related_products[]" value="<?=$_item->getId()?>"/>
            <?endif;?>
                <a href="<?=$_item->getProductUrl()?>"><img src="<?=$_item->getThumbnailUrl()?>" alt="<?=$_item->getName()?>" width="50" height="50"/></a>
            </div>
            <div class="product-details">
                    <a href="<?=$_item->getProductUrl()?>"><?=$_item->getName()?></a>
                    <?=$this->helper('catalog/product')->getPriceHtml($_item)?>
                    <?if($_item->isSuper()):?>
                        <a href="<?=$_item->getProductUrl()?>"><?=$this->__('View Details')?></a><br/>
                    <?else:?>
                        <?if ($this->helper('wishlist')->isAllow()) :?>
                        <a href="<?=$this->getAddToWishlistUrl($_item)?>" class="link-cart"><?=$this->__('Add to Wishlist')?></a>
                        <?endif;?>
                    <?endif;?>
            </div>
        </li>
        <?endforeach?>
        </ol>
    </div>
</div>
<script type="text/javascript">
$$('.related-checkbox').each(function(elem){
    Event.observe(elem, 'click', addRelatedToProduct)
});

function selectAllRelated(){
    $$('.related-checkbox').each(function(elem){
        elem.checked = true;
    });
    addRelatedToProduct();
}

function addRelatedToProduct(){
    var checkboxes = $$('.related-checkbox');
    var values = [];
    for(var i=0;i<checkboxes.length;i++){
        if(checkboxes[i].checked) values.push(checkboxes[i].value);
    }
    if($('related-products-field')){
        $('related-products-field').value = values.join(',');
    }
}
</script>
<?endif?>