<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?
/**
 * Product list toolbar
 *
 * @see Mage_Catalog_Block_Product_List_Toolbar
 */
?>
<?if($this->getCollection()->getSize()):?>
    <table class="pager" cellspacing="0">
        <tr>
            <td>
            <?if($this->getLastPageNum()>1):?>
                <?=$this->__('Items %s to %s of %s total', $this->getFirstNum(), $this->getLastNum(), $this->getTotalNum())?>
            <?else:?>
                <strong><?=$this->__('%s Item(s)', $this->getTotalNum())?></strong>
            <?endif;?>
            </td>
            <?if($this->getLastPageNum()>1):?>
            <td>
                <strong><?=$this->__('Page:')?></strong>
                <ol>
                <?if (!$this->isFirstPage()):?>
                    <li>
                        <a href="<?=$this->getPreviousPageUrl()?>"><img src="<?=$this->getSkinUrl('images/pager_arrow_left.gif')?>" alt="<?=$this->__('Previous')?>"/></a>
                    </li>
                <?endif?>
                <?foreach ($this->getPages() as $_page):?>
                    <?if ($this->isPageCurrent($_page)):?>
                        <li><span class="on"><?=$_page?></span></li>
                    <?else:?>
                        <li><a href="<?=$this->getPageUrl($_page)?>"><?=$_page?></a></li>
                    <?endif?>
                <?endforeach;;?>
                <?if (!$this->isLastPage()):?>
                    <li>
                        <a href="<?=$this->getNextPageUrl()?>"><img src="<?=$this->getSkinUrl('images/pager_arrow_right.gif')?>" alt="<?=$this->__('Next')?>"/></a>
                    </li>
                <?endif?>
                </ol>
            </td>
            <?endif;?>
            <td class="a-right">
                <?=$this->__('Show')?> <select name="" onchange="setLocation(this.value)">
                <?foreach ($this->getAvailableLimit() as  $_key=>$_limit):?>
                    <option value="<?=$this->getLimitUrl($_key)?>"<?if($this->isLimitCurrent($_key)):?> selected<?endif?>>
                        <?=$_limit?>
                    </option>
                <?endforeach;?>
                </select> <?=$this->__('per page')?>
            </td>
        </tr>
    </table>
    <?if( $this->isExpanded() ):?>
    <table class="view-by" cellspacing="0">
        <tr>
            <?if( $this->isEnabledViewSwitcher() ):?>
            <td>
                <?$_modes = $this->getModes();?>
                <?if($_modes && count($_modes)>1):?>
                <?=$this->__('View as')?>:
                <?foreach ($this->getModes() as $_code=>$_label):?>
                    <?if($this->isModeActive($_code)):?>
                        <strong><?=$_label?></strong>&nbsp;
                    <?else:?>
                        <a href="<?=$this->getModeUrl($_code)?>"><?=$_label?></a>&nbsp;
                    <?endif;?>
                <?endforeach;?>
                <?endif;?>
            </td>
            <?endif;?>
            <td class="a-right">
                <?=$this->__('Sort by')?> <select name="" onchange="setLocation(this.value)">
                <?foreach($this->getAvailableOrders() as $_key=>$_order):?>
                    <option value="<?=$this->getOrderUrl($_key, 'asc')?>"<?if($this->isOrderCurrent($_key)):?> selected<?endif;?>>
                        <?=$_order?>
                    </option>
                <?endforeach;?>
                </select>
                <?if($this->getCurrentDirection() == 'desc'):?>
                    <a href="<?=$this->getOrderUrl(null, 'asc')?>"><img src="<?=$this->getSkinUrl('images/sort_desc_arrow.gif')?>" alt="<?=$this->__('Set Ascending Direction')?>" class="v-middle"/></a>
                <?else:?>
                    <a href="<?=$this->getOrderUrl(null, 'desc')?>"><img src="<?=$this->getSkinUrl('images/sort_asc_arrow.gif')?>" alt="<?=$this->__('Set Descending Direction')?>" class="v-middle"/></a>
                <?endif;?>
            </td>
        </tr>
    </table>
    <?endif;?>
<?endif?>
