<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?if($_shippingRateGroups = $this->getShippingRates()):?>
    <div id="order:shipping-method-choose" style="display:none">
    <dl class="shipment-methods">
    <?foreach ($_shippingRateGroups as $code => $_rates):?>
        <dt><strong><?=$this->getCarrierName($code)?></strong></dt>
        <dd>
            <ul>
            <?foreach ($_rates as $_rate):?>
                <?$_radioProperty = 'name="order[shipping_method]" type="radio" onclick="order.setShippingMethod(this.value)"'?>
                <?$_code=$_rate->getCode()?>
                <li>
                   <?if ($_rate->getErrorMessage()):?>
                        <?=$_rate->getErrorMessage()?></strong>
                   <?else:?>
                        <?$_checked = $this->isMethodActive($_code) ? 'checked' : ''?>
                        <input <?=$_radioProperty?> value="<?=$_code?>" id="s_method_<?=$_code?>" <?=$_checked?>/>
                        <label class="normal" for="s_method_<?=$_code?>">
                            <?=$_rate->getMethodDescription()?> - <strong><?=$_rate->getPrice()?></strong>
                        </label>
                   <?endif?>
                </li>
            <?endforeach;?>
            </ul>
        </dd>
    <?endforeach;?>
    </dl>
    </div>
    <?if ($_rate = $this->getActiveMethodRate()):?>
        <div id="order:shipping-method-info">
            <strong><?=$this->getCarrierName($_rate->getCarrier())?></strong><br/>
            <?=$_rate->getMethodDescription()?> - <strong><?=$_rate->getPrice()?></strong>
            <!--input type="text" class="input-text" style="width:70px"/-->
            <br/>
            <a href="#" onclick="$('order:shipping-method-info').hide();$('order:shipping-method-choose').show();return false">
                <?=Mage::helper('sales')->__('Click to change shipping method')?></i>
            </a>
        </div>
    <?else:?>
        <script type="text/javascript">$('order:shipping-method-choose').show();</script>
    <?endif;?>
<?elseif($this->getIsRateRequest()):?>
    <strong><?=Mage::helper('sales')->__('Sorry, no quotes are available for this order at this time.')?></strong>
<?else:?>
    <div id="order:shipping-method-summary">
        <a href="#" onclick="order.loadShippingRates();return false">
            <?=Mage::helper('sales')->__('Get shipping methods and rates')?>
        </a>
    </div>
<?endif;?>