<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

    <div class="page-head">
        <h3><?php echo $this->__('Shipping Information') ?></h3>
    </div>
    <h4><?php echo $this->__('Shipping Address') ?> | <a href=""><?php echo $this->__('Change Shipping Address') ?></a></h4>
    <address>
            <strong><?php echo $address->getFirstname() ?> <?php echo $address->getLastname() ?></strong><br/>
            <?php echo $address->getCompany() ?><br/>
            <?php echo $address->getPostcode() ?>, <?php echo $address->getCity() ?><br/>
            <?php echo $address->getStreet() ?><br/>
            <?php if($address->getTelephone()): ?>T| <?php echo $address->getTelephone() ?><br/><?php endif ?>
            <?php if($address->getFax()): ?>F| <?php echo $address->getFax() ?><br/><?php endif ?>
    </address>
    <h4><?php echo $this->__('Shipping Method') ?></h4>
    <form action="<?php echo $action ?>" method="post">
            <fieldset>
                    <legend><?php echo $this->__('Shipping Method') ?></legend>
            </fieldset>
            <div class="button-set">
                    <a href="#" onclick="window.location='<?php echo $this->getUrl('checkout/cart') ?>'" class="left">&laquo;</a>
                    <button class="form-button" type="submit"><span><?php echo $this->__('Continue') ?></span></button>
            </div>
    </form>