<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

    <div class="page-head">
        <h3><?=$this->__('Shipping Information')?></h3>
    </div>
    <h4><?=$this->__('Shipping Address')?> | <a href=""><?=$this->__('Change Shipping Address')?></a></h4>
    <address>
            <strong><?=$address->getFirstname()?> <?=$address->getLastname()?></strong><br/>
            <?=$address->getCompany()?><br/>
            <?=$address->getPostcode()?>, <?=$address->getCity()?><br/>
            <?=$address->getStreet()?><br/>
            <?if($address->getTelephone()):?>T| <?=$address->getTelephone()?><br/><?endif?>
            <?if($address->getFax()):?>F| <?=$address->getFax()?><br/><?endif?>
    </address>
    <h4><?=$this->__('Shipping Method')?></h4>
    <form action="<?=$action?>" method="post">
            <fieldset>
                    <legend><?=$this->__('Shipping Method')?></legend>
            </fieldset>
            <div class="button-set">
                    <a href="#" onclick="window.location='<?=$this->getUrl('checkout/cart')?>'" class="left">&laquo;</a>
                    <button class="form-button" type="submit"><span><?=$this->__('Continue')?></span></button>
            </div>
    </form>