<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td><h3 class="icon-head head-system-email-template"><?=$this->getHeaderText()?></h3></td>
            <td class="form-buttons">
                <?=$this->getBackButtonHtml();?>
                <?=$this->getResetButtonHtml();?>
                <?if($this->getEditMode()):?>
                <?=$this->getDeleteButtonHtml();?>
                <?endif?>
                <?if(!$this->isTextType()):?>
                <?=$this->getToPlainButtonHtml();?>
                <?=$this->getToHtmlButtonHtml();?>
                <?endif?>
                <?=$this->getPreviewButtonHtml();?>
                <?=$this->getSaveButtonHtml();?>
            </td>
        </tr>
    </table>
</div>
<?if (!$this->getEditMode()):?>
<form action="<?=$this->getLoadUrl()?>" method="post" id="email_template_load_form">
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend">
            <?=Mage::helper('adminhtml')->__('Load default template')?>
            </h4>
            <div class="form-buttons"></div>
        </div>
        <fieldset>
            <table class="form-list" cellspacing="0">
                <tbody>
                    <tr>
                        <td class="label">
                            <label for="template_select">
                            <?=Mage::helper('adminhtml')->__('Template')?>
                            <span class="required">*</span>
                            </label>
                        </td>
                        <td class="value">
                            <select id="template_select" name="code" class="select required-entry">
                                <?foreach ($this->getTemplateOptions() as $_option):?>
                                <option value="<?=$_option['value']?>"><?=$_option['label']?></option>
                                <?endforeach;?>
                            </select>
                        </td>
                        <td></td>
                    </tr>
                    <tr>
                        <td class="label">
                            <label for="locale_select">
                            <?=Mage::helper('adminhtml')->__('Locale')?>
                            <span class="required">*</span>
                            </label>
                        </td>
                        <td class="value">
                            <select id="locale_select" name="locale" class="select required-entry">
                                <?foreach ($this->getLocaleOptions() as $_option):?>
                                <option value="<?=$_option['value']?>" <?if ($_option['value']==$this->getCurrentLocale()):?>selected<?endif;?>><?=$_option['label']?></option>
                                <?endforeach;?>
                            </select>
                        </td>
                        <td></td>
                    </tr>
                    <tr>
                        <td class="label">
                            <label ></label>
                        </td>
                        <td class="value">
                            <?=$this->getLoadButtonHtml()?>
                        </td>
                        <td></td>
                    </tr>
                </tbody>
            </table>
        </fieldset>
    </div>
</form>
<?endif?>
<form action="<?=$this->getSaveUrl()?>" method="post" id="email_template_edit_form">
<input type="hidden" id="change_flag_element" name="_change_type_flag" value="" />
<?=$this->getFormHtml()?>
</form>
<form action="<?=$this->getPreviewUrl()?>" method="post" id="email_template_preview_form" target="_blank">
<input type="hidden" id="preview_type" name="type" value="<?=$this->isTextType()?1:2?>" />
<input type="hidden" id="preview_text" name="text" value="" />
</form>
<script type="text/javascript" language="javascript">
    var templateForm = new varienForm('email_template_edit_form');
    var templatePreviewForm = new varienForm('email_template_preview_form');
    var templateControl = {
        unconvertedText: '',
        typeChange: false,
        init: function () {
        	if ($('convert_button_back')) {
        		$('convert_button_back').hide();
        	}
        },
        stripTags: function () {
            if(!window.confirm("<?=$this->__('Are you sure that you want to strip tags?')?>")) {
                return false;
            }
            this.unconvertedText = $('template_text').value;
            $('convert_button').hide();
            $('template_text').value =  $('template_text').value.stripScripts().replace(
                new RegExp('<style[^>]*>[\\S\\s]*?</style>', 'img'), ''
            ).stripTags().strip();
            $('convert_button_back').show();
            this.typeChange = true;
            return false;
        },
        unStripTags: function () {
            $('convert_button').show();
            $('convert_button_back').hide();
            $('template_text').value =  this.unconvertedText;
            this.typeChange = false;
            return false;
        },
        save: function() {
            if (this.typeChange) {
                $('change_flag_element').value = '1';
            }
            templateForm.submit();
            return false;
        },
        preview: function() {
            if (this.typeChange) {
                $('preview_type').value = 1;
            }
            if (typeof tinyMCE == 'undefined' || !tinyMCE.getInstanceById('template_text')) {
                $('preview_text').value = $('template_text').value;
            } else {
                 $('preview_text').value = tinyMCE.getInstanceById('template_text').getHTML();
            }
            templatePreviewForm.submit();
            return false;
        },

        deleteTemplate: function() {
            if(window.confirm("<?=$this->__('Are you sure that you want to delete this template?')?>")) {
               	window.location.href = '<?=$this->getDeleteUrl()?>';
            }
        },

        load: function() {
            var form = new varienForm('email_template_load_form');

            if (!form.validator.validate()) {
                return;
            }

            new Ajax.Request($('email_template_load_form').action, {
               parameters: Form.serialize($('email_template_load_form'), true),
               area: $('email_template_load_form'),
               onComplete: function (transport) {
                   if (transport.responseText.isJSON()) {
                       var fields = $H(transport.responseText.evalJSON());
                       fields.each(function(pair) {
                          if ($(pair.key)) {
                              $(pair.key).value = pair.value.strip();
                          }
                          if (pair.key == 'template_type') {
                              if (pair.value == 1) {
                                  this.typeChange = true;
                                  $('convert_button').hide();
                                  $('convert_button_back').hide();
                              } else {
                                  this.typeChange = false;
                                  $('convert_button_back').hide();
                                  $('convert_button').show();
                              }
                          }
                       }.bind(this));
                   }
               }.bind(this)
            });

        }
    };

    templateControl.init();
</script>
