<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

    <div class="page-head">
            <h3><?=$this->__('Order #%s (%s)', $order->getOrderId(), $order->getStatus())?></h3>
        </div>

    <div class="col2-set">
            <div class="col-1">
                <h4><?=$this->__('Billing Information')?></h4>
                <address>
                        <?=$order->getAddressByType('billing')->toString('{{firstname}} {{lastname}}<br/>{{street}}<br/>{{city}}, {{regionName}} {{postcode}}<br/>T: 
                        {{telephone}}')?>
                </address>
            </div>
            <div class="col-2">
                <h4><?=$this->__('Payment Method')?></h4>
        <?=$this->getChildHtml('payment')?>
            </div>
        </div>
    <p></p>
        <div class="col2-set">
            <div class="col-1">
                <h4><?=$this->__('Shipping Information')?></h4>
                <address>
                        <?=$order->getAddressByType('shipping')->toString('{{firstname}} {{lastname}}<br/>{{street}}<br/>{{city}}, {{regionName}} {{postcode}}<br/>T: 
                        {{telephone}}')?>
                </address></div>
            <div class="col-2">
                <h4><?=$this->__('Shipping Method')?></h4>
                <?=$order->getShippingDescription()?>
            </div>
        </div>
    <p></p>
    <?$_items = $order->getEntitiesByType('item')?>
    <table cellspacing="0" width="100%" class="data-table" id="my-orders-table">
        <thead>
            <tr>
                <th><?=$this->__('Items Order')?></th>
                <th class="a-center"><?=$this->__('Qty')?></th>
                <th class="a-right"><?=$this->__('Price')?></th>
                <th class="a-right"><?=$this->__('Ext. Price')?></th>
            </tr>
        </thead>
        <tfoot>
            <tr>
                <td class="a-right" colspan="4">
                    <?=$this->__('Grand Total: %s', $order->getGrandTotal())?>
                </td>
            </tr>
        </tfoot>
        <tbody>
            <?foreach($_items as $_item):?>
            <tr>
                <td><?=$_item->getName()?></td>
                <td class="a-center"><?=$_item->getQty()?></td>
                <td class="a-right"><?=$_item->getPrice()?></td>
                <td class="a-right"><?=$_item->getRowTotal()?></td>
            </tr>   
            <?endforeach?> 
        </tbody>
    </table>
<script type="text/javascript">decorateTable('my-orders-table')</script>
    <div class="button-set">
            <a href="<?=$this->getUrl('customer/order/history')?>" class="left">&laquo; <?=$this->__('Back')?></a>
    </div>