<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="v-middle a-left" style="padding:20px;">

<?=$this->__('Number of visitors')?>: <?=$this->getDataHelper('adminhtml/dashboard_visitor')->getOnlineData('visitors')?><br/>
<?=$this->__('Number of customers')?>: <?=$this->getDataHelper('adminhtml/dashboard_visitor')->getOnlineData('customers')?><br/>
<?=$this->__('Total number of people on site')?>: <?=$this->getDataHelper('adminhtml/dashboard_visitor')->getOnlineData('total')?><br/>
<a href="<?=$this->getWhosOnlineUrl()?>"><?=$this->__('Who\'s Online')?></a><br/>

</div>