<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   Mage
 * @package    Mage_Adminhtml
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?$_element = $this->getElement()?>
<?$this->checkFieldDisable()?>
<tr>
    <?if ($_element->getType()=='hidden'):?>
    <td colspan="2"><?=trim($_element->getElementHtml())?></td>
    <?else:?>
    <td class="label"><?=trim($_element->getLabelHtml())?></td>
    <td class="value value"><?=trim($_element->getElementHtml())?></td>
    <?endif;?>
    <td class="value scope-label"><?=$this->getScopeLabel()?></td>
    <?if ($this->canDisplayUseDefault()):?>
    <td class="value use-default">
        <input type="checkbox" name="use_default[]" id="<?=$_element->getHtmlId()?>_default"<?if ($this->usedDefault()):?> checked<?endif;?> onclick="toggleValueElements(this, this.parentNode.parentNode)" value="<?=$this->getAttributeCode()?>"/>
        <label for="<?=$_element->getHtmlId()?>_default" class="normal"><?=$this->__('Use Default Value')?></label>
    </td>
    <?endif;?>
</tr>
