<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="box account-nav">
    <div class="head">
        <h3><?=$this->__('My Account');?></h3>
    </div>
            <ul>
                <?$_links = $this->getLinks();?>
                <?$_index = 1;?>
                <?$_count = count($_links);?>
                <?foreach ($_links as $_link):?>
                    <?$_last = ($_index++ >= $_count);?>
                    <?if ($this->isActive($_link)):?>
                        <li class="on<?=($_last ? ' last' : '')?>"><?=$_link->getLabel()?></li>
                    <?else:?>
                        <li<?=($_last ? ' class="last"' : '')?>><a href="<?=$_link->getUrl()?>"><?=$_link->getLabel()?></a></li>
                    <?endif;?>
                <?endforeach;?>
            </ul>
</div>