<?php
/** 
 * Magento 
 * 
 * NOTICE OF LICENSE 
 * 
 * This source file is subject to the Open Software License (OSL 3.0) 
 * that is bundled with this package in the file LICENSE.txt. 
 * It is also available through the world-wide-web at this URL: 
 * http://opensource.org/licenses/osl-3.0.php 
 * If you did not receive a copy of the license and are unable to 
 * obtain it through the world-wide-web, please send an email 
 * to license@magentocommerce.com so we can send you a copy immediately. 
 * 
 * @category   design_default 
 * @package    Mage 
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com) 
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0) 
 */
?>
<?
/**
 * Temlate for Mage_Customer_Block_Address_Book block
 * @var $test Mage_Customer_Block_Address_Book
 */
?>
<div class="page-head button-level">
    <h3><?=$this->__('Address Book')?></h3>
    <button class="form-button" onclick="window.location='<?=$this->getAddAddressUrl()?>';"><span><?=$this->__('Add New Address')?></span></button>
</div>
<?=$this->getMessagesBlock()->getGroupedHtml()?>
<div class="col2-set">
    <div class="col-1 primary-address-list">
        <h4><?=$this->__('Default Addresses')?></h4>
       <ol>
             <?if($_pAddsses = Mage::getSingleton('customer/session')->getCustomer()->getDefaultBilling()):?>
                <li>
                    <h5><?=$this->__('Default Billing Address')?></h5>
                    <address>
                    <?=$this->getAddressHtml(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses))?>
           <br/><strong><a href="<?=$this->getAddressEditUrl(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses))?>"><?=$this->__('Change Billing Address')?></a></strong></address></li>
           <?elseif($_pAddsses = Mage::getSingleton('customer/session')->getCustomer()->getDefaultShipping()):?>
           <li>
                <h5><?=$this->__('Default Billing Address')?></h5>
                <address>
                    <?=$this->getAddressHtml(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses))?><br/>
                    <strong><a href="<?=$this->getAddressEditUrl(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses))?>"><?=$this->__('Change Billing Address')?></a></strong>
                </address>
            </li>
            <?else:?>
                    <li>
                        <h5><?=$this->__('Default Billing Address')?></h5>
                        <?=$this->__('You have no default billing address in your address book.')?></li>
            <?endif?>
                <?if($_pAddsses = Mage::getSingleton('customer/session')->getCustomer()->getDefaultShipping()):?>
                 <li>
                    <h5><?=$this->__('Default Shipping Address')?></h5>
                    <address>
                            <?=$this->getAddressHtml(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses))?><br/>
                            <strong><a href="<?=$this->getAddressEditUrl(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses))?>"><?=$this->__('Change Shipping Address')?></a></strong>
                    </address>
                </li>
            <?elseif($_pAddsses = Mage::getSingleton('customer/session')->getCustomer()->getDefaultBilling()):?>
              <li>
                    <h5><?=$this->__('Default Shipping Address')?></h5><address>
                        <?=$this->getAddressHtml(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses))?><br/>
                        <strong><a href="<?=$this->getAddressEditUrl(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses))?>"><?=$this->__('Change Shipping Address')?></a></strong>
                    </address></li>
            <?else:?>
               <li>
                    <h5><?=$this->__('Default Shipping Address')?></h5><?=$this->__('You have no default shipping address in your address book.')?></li>
            <?endif?>
            </ol>

        </div>
        <div class="col-2 address-list">
            <h4><?=$this->__('Additional Address Entries')?></h4>
            <ol>
            <?if($_pAddsses = $this->getAdditionalAddresses()):?>
                <?foreach($_pAddsses as $_address):?>
                                <li>
                    <address>
                        <?=$this->getAddressHtml($_address)?><br/>
                                                <strong><a href="<?=$this->getUrl('customer/address/edit', array('id'=>$_address->getId()))?>"><?=$this->__('Edit Address')?></a></strong><span class="pipe">|</span><strong><a href="#" onclick="return deleteAddress('<?=$_address->getId()?>');" class="link-remove"><?=$this->__('Delete Address')?></a></strong>
                    </address>
                                </li>
                <?endforeach;?>
            <?else:?>
                        <li> <strong><?=$this->__('You have no additional address entries in your address book.')?></strong></li>
            <?endif?>
            </ol>
                    </div>
                </div>
<div class="button-set">
    <a href="<?=$this->getBackUrl()?>" class="left">&laquo; <?=$this->__('Back')?></a>
</div>
<script type="text/javascript">
    function deleteAddress(addressId) {
        if(confirm('<?=$this->__('Are you sure you want to delete this address?')?>')) {
            window.location='<?=$this->getDeleteUrl()?>id/'+addressId;
        }
        return false;
    }
</script>