<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
            <td><h3><?=$this->getHeaderText()?></h3></td>
            <td class="form-buttons">
                <?=$this->getBackButtonHtml();?>
                <?=$this->getResetButtonHtml();?>
                <?if(!$this->isTextType()):?>
                <?=$this->getToPlainButtonHtml();?>
                <?=$this->getToHtmlButtonHtml();?>
                <?endif?>
                <?=$this->getSaveButtonHtml();?>
                <?if($this->getEditMode()):?>
                <?=$this->getSaveAsButtonHtml();?>
                <?endif?>
                <?=$this->getPreviewButtonHtml();?>
                <?if($this->getEditMode()):?>
                <?=$this->getDeleteButtonHtml();?>
                <?endif?>
            </td>
        </tr>
    </table>
</div>
<form action="<?=$this->getSaveUrl()?>" method="post" id="newsletter_template_edit_form">
<input type="hidden" id="change_flag_element" name="_change_type_flag" value="" />
<input type="hidden" id="save_as_flag" name="_save_as_flag" value="<?=$this->getSaveAsFlag()?>" />
<?=$this->getForm()?>
</form>
<form action="<?=$this->getPreviewUrl()?>" method="post" id="newsletter_template_preview_form" target="_blank">
<input type="hidden" id="preview_type" name="type" value="<?=$this->isTextType()?1:2?>" />
<input type="hidden" id="preview_text" name="text" value="" />
</form>
<script type="text/javascript" language="javascript">
    var templateForm = new varienForm('newsletter_template_edit_form');
    var templatePreviewForm = new varienForm('newsletter_template_preview_form');
    var templateControl = {
        unconvertedText: '',
        typeChange: false,
        templateName: false,
        isEditor: false,
        init: function () {
        	if ($('convert_button_back')) {
        		$('convert_button_back').hide();
        	}
        },
        stripTags: function () {
            if(!window.confirm("<?=Mage::helper('newsletter')->__('Are you sure that you want to strip all tags?')?>")) {
                return false;
            }
            if(this.isEditor) {
            	tinyMCE.execCommand('mceRemoveControl', false, 'text');
            }
            this.unconvertedText = $('text').value;
            $('convert_button').hide();
            $('text').value =  $('text').value.stripScripts().stripTags();
            $('convert_button_back').show();
            this.typeChange = true;
            return false;
        },
        unStripTags: function () {
            $('convert_button').show();
            $('convert_button_back').hide();
            $('text').value =  this.unconvertedText;

            this.typeChange = false;
            return false;
        },
        save: function() {
            if (this.typeChange) {
                $('change_flag_element').value = '1';
            }
            if(this.isEditor) {
            	tinyMCE.triggerSave();
            }
            templateForm.submit();
            return false;
        },
        saveAs: function() {
            if (this.typeChange) {
                $('change_flag_element').value = '1';
            }

            if($F('code').blank() || $F('code')==templateControl.templateName) {
               value = prompt('<?=Mage::helper('newsletter')->__('Please enter new template name')?>', templateControl.templateName + '<?=Mage::helper('newsletter')->__(' Copy')?>');
               if(!value) {
                   if(value !== null) {
                       $('code').value = '';
                       templateForm.submit();
                   }
                   return false;
               } else {
                   $('code').value = value;
               }
            }

            $('save_as_flag').value = '1';

            if(this.isEditor) {
            	tinyMCE.triggerSave();
            }
            templateForm.submit();
            return false;
        },
        preview: function() {
            if (this.typeChange) {
                $('preview_type').value = 1;
            }
            if (typeof tinyMCE == 'undefined' || !tinyMCE.getInstanceById('text')) {
                $('preview_text').value = $('text').value;
            } else {
                 $('preview_text').value = tinyMCE.getInstanceById('text').getHTML();
            }
            templatePreviewForm.submit();
            return false;
        },

        deleteTemplate: function() {
            if(window.confirm("<?=Mage::helper('newsletter')->__('Are you sure that you want to delete this template?')?>")) {
               	window.location.href = '<?=$this->getDeleteUrl()?>';
            }
        }
    };

    templateControl.init();
    templateControl.templateName = "<?=$this->getJsTemplateName()?>";
</script>
