<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<div class="informational">
    <?=$this->getChildHtml()?>  
    <?if($this->hasSeoLinks()>0):?>
       <div>
        <ul id="footer:seo-links">
        <?foreach($this->getSeoLink() as $item):?>                                      
            <li><a href="<?=$item['url'];?>"><?=$item['title'];?></a></li>
        <?endforeach;?>
        </ul>
        <script type="text/javascript">decorateList('footer:seo-links')</script>
       </div>
    <?endif;?>       
</div>

<p class="legality">
<?=$this->__('Help Us to Keep Magento Healthy')?> - <a href="http://www.magentocommerce.com/bug-tracking" target="varien_external"><strong><?=$this->__('Report All Bugs')?></strong></a> <?=$this->__('(ver. %s)', Mage::getVersion())?><br />
<?=$this->__('Magento&trade; is a registered Trademark of Irubin Consulting Inc. DBA Varien. &copy; Copyright 2007')?></p>