<title><?=htmlspecialchars($this->getTitle())?></title>
<meta http-equiv="Content-Type" content="<?=$this->getContentType()?>"/>
<meta name="description" content="<?=htmlspecialchars($this->getDescription())?>"/>
<meta name="keywords" content="<?=htmlspecialchars($this->getKeywords())?>"/>
<meta name="robots" content="<?=htmlspecialchars($this->getRobots())?>"/>

<link rel="icon" href="<?=$this->getBaseUrl()?>favicon.ico" type="image/x-icon"/>
<link rel="shortcut icon" href="<?=$this->getBaseUrl()?>favicon.ico" type="image/x-icon"/>

<script type="text/javascript">
    var BLANK_URL = '<?=$this->getJsUrl()?>blank.html';
</script>

<?=$this->getAdditionalCssJs()?>
<?=$this->getChildHtml()?>

<?=$this->helper('core/js')->getTranslatorScript()?>
