<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<div class="header-top-container">
    <div class="header-top">
        <h1 id="logo"><a href="<?=$this->getUrl('')?>"><img src="<?=$this->getLogoSrc()?>" alt="<?=$this->getLogoAlt()?>"/></a></h1>
        <p class="no-display"><a href="#main"><strong><?=$this->__('Skip to Main Content')?> &raquo;</strong></a></p>


        <?=$this->getChildHtml('topSearch')?>


        <div class="quick-access">
            <div class="account-access">
               <strong><?=$this->getWelcome()?></strong><?=$this->getChildHtml('topLeftLinks')?>
            </div>
            <div class="shop-access">
                <?=$this->getChildHtml('topRightLinks')?>
            </div>
        </div>

    </div>
</div>
<?=$this->getChildHtml('topMenu')?>