<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?if($toplinks && is_array($toplinks)): ?>
<ul>
    <?=$this->getChildHtml()?>
    <?foreach($toplinks as $_toplink):?>
    <li<?if($_toplink['first']||$_toplink['last']):?> class="<?if($_toplink['first']):?>first <?endif;?><?if($_toplink['last']):?>last <?endif;?>"<?endif;?> <?=$_toplink['liParams']?>>        <?=$_toplink['beforeText']?><a <?=$_toplink['aParams']?>><?=$_toplink['innerText']?></a><?=$_toplink['afterText']?></li>
    <?endforeach;?>
</ul>

<?endif;?>