<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
            <td><h3><?=Mage::helper('catalog')->__('Update attributes')?></h3></td>
            <td class="a-right">
            <?=$this->getBackButtonHtml()?>
            <?=$this->getCancelButtonHtml()?>
            <?=$this->getSaveButtonHtml()?>
            </td>
        </tr>
    </table>
</div>
<form action="<?=$this->getSaveUrl()?>" method="post" id="attributes_edit_form" enctype="multipart/form-data">

</form>
<script type="text/javascript">
var onInitDisableFieldsList = [];

function toogleFieldEditMode(toogleIdentifier, fieldContainer) {
   if($(toogleIdentifier).checked) {
       enableFieldEditMode(fieldContainer);
   } else {
       disableFieldEditMode(fieldContainer);
   }
}

function disableFieldEditMode(fieldContainer) {
    $(fieldContainer).disabled = true;
    if($(fieldContainer + '_hidden')) {
        $(fieldContainer + '_hidden').disabled = true;
    }
}

function enableFieldEditMode(fieldContainer) {
    $(fieldContainer).disabled = false;
    if($(fieldContainer + '_hidden')) {
        $(fieldContainer + '_hidden').disabled = false;
    }
}

function initDisableFields(fieldContainer)
{
    onInitDisableFieldsList.push(fieldContainer);
}

function onCompleteDisableInited()
{
    onInitDisableFieldsList.each(function(item){
        disableFieldEditMode(item);
    });
}

var attributesForm = new varienForm('attributes_edit_form');

Event.observe(window, 'load', onCompleteDisableInited);
</script>