<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?
/**
 * Bachup of bundle display on product view
 */
?>
<?
/**
 * Product view template
 *
 * @see Mage_Catalog_Block_Product_View
 */
?>
<?=$this->getMessagesBlock()->getGroupedHtml()?>
<?$_product=$this->getProduct()?>
<div class="product-info-box">
    <div class="product-essential">
        <div class="product-img-box">
            <p class="main-product-img">
                <img id="image" src="<?=$_product->getImageUrl()?>" alt="<?=$_product->getName()?>"/>
            </p>
            <div class="image-zoom" id="track_outer">
                <img id="zoom_out" src="<?=$this->getSkinUrl('images/slider_btn_zoom_out.gif')?>" alt="<?=$this->__('Zoom Out')?>" class="btn-zoom-out"/>
                <div id="track">
                    <div id="handle"></div>
                </div>
                <img id="zoom_in" src="<?=$this->getSkinUrl('images/slider_btn_zoom_in.gif')?>" alt="<?=$this->__('Zoom Out')?>" class="btn-zoom-in"/>
            </div>
            <script type="text/javascript">
                Event.observe(window, 'load', function() {
                    product_zoom = new Product.Zoom('image', 'track', 'handle', 'zoom_in', 'zoom_out');
                });
            </script>
        <?if ($this->getGalleryImages() && $this->getGalleryImages()->getSize()):?>
            <div class="more-views">
                <h4><?=$this->__('More Views')?></h4>
                <ul>
                <?foreach ($this->getGalleryImages() as $_image):?>
                    <li>
                        <a href="#" onclick="popWin('<?=$this->getGalleryUrl($_image)?>', 'gallery', 'scrollbars=no,width=300,height=300');return false;">
                            <img src="<?=$_image->setType(2)->getSourceUrl();?>" width="68" alt=""/>
                        </a>
                    </li>
                <?endforeach;?>
                </ul>
            </div>
       <?endif;?>
       </div>
       <div class="product-shop">
       <h3 class="product-name"><?=$_product->getName()?></h3>
            <?=$this->getHelper('review/helper')->getSummaryHtml($_product, null, 1)?>
            <form action="<?=$this->getUrl('checkout/cart/add')?>" method="post" id="product_addtocart_form">
            <input type="hidden" name="product" value="<?=$_product->getId()?>">
            <input type="hidden" name="related_product" id="related-products-field" value="">
            
            <?if($_product->isBundle()):?>
                <div class="product-attributes">
                <?if($_product->isAvailableBundle()):?>
                    <table cellspacing="0" id="bundle-price-table">
                    <?foreach($_product->getBundleOptionCollection() as $_bundleOption):?>
                        <tr>
                            <td class="label"><?=$_bundleOption->getLabel()?>:</td>
                            <td>
                            <?if(sizeof($_bundleOption->getLinkCollection()->getItems())>1):?>
                                <select name="bundle_option[<?=$_bundleOption->getId()?>]">
                                    <?foreach ($_bundleOption->getLinkCollection() as $_option):?>
                                    <option value="<?=$_option->getProductId()?>"><?=$_option->getName()?></option>
                                    <?endforeach;?>
                                </select>
                            <?elseif(sizeof($_bundleOption->getLinkCollection()->getItems())==1):?>
                                <?$_option=$_bundleOption->getLinkCollection()->getFirstItem()?>
                                <input type="hidden" name="bundle_option[<?=$_bundleOption->getId()?>]" value="<?=$_option->getProductId()?>" /><?=$_option->getName()?>
                            <?else:?>
                                <?=$this->__('Out of Stock')?>
                            <?endif;?>
                            </td>
                        </tr>
                    <?endforeach;?>
                    </table>
                    <script type="text/javascript">decorateTable('bundle-price-table')</script>
                <?else:?>
                    <p><?=$this->__('This bundle is out of stock.')?></p>
                <?endif;?>
                </div>
                
            <?elseif($_product->isSuperConfig()):?>
                <?=$this->getChildHtml('super_config')?>
            <?endif;?>

            <?if($_product->getTierPriceCount()>1):?>
                <div class="product-pricing">
                    <ul class="bare">
                    <?foreach($_prices=$_product->getFormatedTierPrice() as $_price):?>
                        <li><?=$this->__('Buy %s for %s each', $_price['price_qty'], $_price['price'])?></li>
                    <?endforeach?>
                    </ul>
                </div>
            <?endif;?>
            
            <?if($_product->isSuperGroup()):?>
                <?=$this->getChildHtml('super_group')?>
            <?endif;?>
            
            <?if(!$_product->isSuperGroup()):?>
                <?if(!$_product->isBundle() || $_product->isAvailableBundle()):?>
                    <p><small><?=$this->__('Availability: In stock. Ships within 24 hours.')?></small></p>
                    <?=$this->helper('catalog/product')->getPriceHtml($_product)?>
                    <fieldset class="add-to-cart-box">
                        <legend><?=$this->__('Add Items to Cart')?> </legend>
                        <span class="qty-box"><label for="qty"><?=$this->__('Qty')?>:</label> 
                        <input name="qty" type="text" class="input-text qty" id="qty"/></span>
                        <button class="form-button" onclick="productAddToCartForm.submit()"><span><?=$this->__('Add to Cart')?></span></button>
                        <strong><?=$this->__('OR')?></strong>
                    </fieldset>
                    <div class="add-to-box">
                        <?if ($this->helper('wishlist')->isAllow()) :?>
                        <a href="<?=$this->getAddToWishlistUrl($_product)?>"><?=$this->__('Add to Wishlist')?></a><br/>
                        <?endif;?>
                        <a href="<?=$this->getAddToCompareUrl($_product)?>"><?=$this->__('Add to Compare')?></a>
                    </div>
                <?else:?>
                    <p><small><?=$this->__('Availability: Out of stock.')?></small></p>
                    <p>
                        <?if ($this->helper('wishlist')->isAllow()) :?>
                        <a href="<?=$this->getAddToWishlistUrl($_product)?>"><?=$this->__('Add to Wishlist')?></a> <br/>
                        <?endif;?>
                        <a href="<?=$this->getAddToCompareUrl($_product)?>"><?=$this->__('Add to Compare')?></a>
                    </p>
                <?endif;?>
            <?else:?>
                <p><small><?=$this->__('Availability: In stock. Ships within 24 hours.')?></small></p>
                <button class="form-button" onclick="productAddToCartForm.submit()"><span><?=$this->__('Add to Cart')?></span></button> <strong><?=$this->__('OR')?></strong>
                &nbsp;&nbsp;
                <?if ($this->helper('wishlist')->isAllow()) :?>
                <a href="<?=$this->getAddToWishlistUrl($_product)?>"><?=$this->__('Add to Wishlist')?></a>
                <span class="pipe">|</span>
                <?endif;?>
                <a href="<?=$this->getAddToCompareUrl($_product)?>"><?=$this->__('Add to Compare')?></a>
            <?endif;?>
            </form>
            <script type="text/javascript">
                var productAddToCartForm = new VarienForm('product_addtocart_form');
                productAddToCartForm.submit = function() {
                    if(this.validator.validate()) {
                        this.form.submit();
                    }
                }.bind(productAddToCartForm);
            </script>
            <div class="clear"></div>
            <div class="divider"></div>
            <h4><?=$this->__('Product Description')?></h4>
            <div class="product-specs"><?=$_product->getDescription()?></div>
        </div>
    </div>

    <div class="product-collateral">
        <?=$this->getChildHtml('upsell_products')?>
        <?if($_additional = $this->getAdditionalData()):?>
        <div class="collateral-box attribute-specs">
            <div class="head">
                <h4><?=$this->__('Product Attribute Specs')?></h4>
            </div>
            <table cellspacing="0" class="data-table" id="product-attribute-specs-table">
            <?foreach ($_additional as $_data):?>
            <tr>
                <td class="label"><?=$_data['label']?></td>
                <td class="data"><?=$_data['value']?></td>
            </tr>
            <?endforeach;?>
            </table>
            <script type="text/javascript">decorateTable('product-attribute-specs-table')</script>
        </div>
        <?endif;?>
        <div class="collateral-box" id="customer-reviews">
          <?=$this->getChildHtml('product_additional_data')?>
        </div>
    </div>
</div>
