<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="entry-edit" id="order_history_block">
    <fieldset>
        <ul class="note-list">
        <?php foreach ($this->getFullHistory() as $_history): ?>
            <li>
                <strong><?php echo $this->helper('core')->formatDate($_history->getCreatedAt(), 'medium') ?></strong>
                <?php echo $this->helper('core')->formatTime($_history->getCreatedAt(), 'medium') ?><span class="separator">|</span>
<strong><?php if($_history instanceof Mage_Sales_Model_Order_Status_History): ?>
    <?php echo $_history->getStatusLabel() ?>
<?php elseif ($_history instanceof Mage_Sales_Model_Order_Creditmemo): ?>
    <?php echo $this->__('Creditmemo #%s created', $_history->getIncrementId()) ?>
<?php elseif ($_history instanceof Mage_Sales_Model_Order_Shipment): ?>
    <?php echo $this->__('Shipment #%s created', $_history->getIncrementId()) ?>
<?php elseif ($_history instanceof Mage_Sales_Model_Order_Invoice): ?>
    <?php echo $this->__('Invoice #%s created', $_history->getIncrementId()) ?>
<?php elseif ($_history instanceof Mage_Sales_Model_Order_Shipment_Track ): ?>
    <?php echo $this->__('Tracking number %s for %s assigned', $_history->getNumber(), $_history->getTitle()) ?>
<?php else: ?>
                    <?php echo print_r($_history->getData(), true) ?>
                    <?php echo get_class($_history) ?>
                <?php endif; ?></strong>
                <span class="separator">|</span><small><?php echo $this->helper('sales')->__('Customer') ?>
                <strong class="subdue"><?php if ($_history->getIsCustomerNotified()): ?>
                <?php echo $this->helper('sales')->__('Notified') ?>
                <img src="<?php echo $this->getSkinUrl('images/ico_success.gif') ?>" width="16" height="16"/>
                <?php else: ?>
                <?php echo $this->helper('sales')->__('Not Notified') ?>
                <?php endif; ?>
                </strong></small>
                    <?php if($_history->getComment()): ?>
                        <br/><?php echo $_history->getComment() ?>
                    <?php endif; ?>
            </li>
        <?php endforeach; ?>
        </ul>
    </fieldset>
</div>