<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?$_order = $this->getOrder()?>
<div>
    <div id="order:messages">
        <?=$this->getChildHtml('messages')?>
    </div>
    <?=$this->getChildHtml('info')?>
    <input type="hidden" name="order_id" value="<?=$_order->getId()?>"/>
    <div class="box-left">
        <!--Payment Method-->
        <div class="entry-edit">
            <div class="entry-edit-head">
                <h4 class="icon-head head-payment-method"><?=Mage::helper('sales')->__('Payment Information')?></h4>
            </div>
            <fieldset>
                <?=$this->getPaymentHtml()?>
                <div><?=Mage::helper('sales')->__('Order was placed using %s', $_order->getOrderCurrencyCode())?></div>
            </fieldset>
        </div>
    </div>
    <div class="box-right">
        <!--Shipping Method-->
        <div class="entry-edit">
            <div class="entry-edit-head">
                <h4 class="icon-head head-shipping-method"><?=Mage::helper('sales')->__('Shipping &amp; Handling Information')?></h4>
            </div>
            <fieldset>
                 <? if ($_order->getTracksCollection()->count()) : ?>
<a href="#" id="linkId" onclick="popWin('<?=$this->helper('shipping')->getTrackingPopUpUrlByOrderId($_order->getId())?>','trackorder','width=800,height=600,resizable=yes,scrollbars=yes')" title="<?=$this->__('Track the order')?>"><?=$this->__('Track the order')?></a>
<br/>
<?endif;?>
                <strong><?=$_order->getShippingDescription()?></strong>
                ( <?=$this->displayPriceAttribute('shipping_amount', false, ' ')?> )
            </fieldset>
        </div>
    </div>
    <div class="clear"></div>

    <?=$this->getGiftmessageHtml()?>

    <div class="clear"></div>
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-products"><?=Mage::helper('sales')->__('Items Ordered')?></h4>
        </div>
    </div>
    <div>
        <?=$this->getItemsHtml()?>
    </div>
    <div class="clear"></div>
    <br/>
    <div class="box-left">
        <div class="entry-edit">
            <div class="entry-edit-head">
                <h4><?=Mage::helper('sales')->__('Comments History')?></h4>
            </div>
            <?=$this->getChildHtml('history')?>
        </div>
    </div>
    <div class="box-right entry-edit">
        <div class="entry-edit-head"><h4>Order Totals</h4></div>
        <div class="order-totals"><?=$this->getChildHtml('totals')?></div>
    </div>
    <div class="clear"></div>
</div>
