<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?
/**
 * Currency switcher
 *
 * @see Mage_Directory_Block_Currency
 */
?>
<?if($this->getCurrencyCount()>1):?>
<div class="box currency-switcher">
    <div class="head">
        <h4><?=$this->__('Select Your Currency')?></h4>
    </div>
        <select name="currency" onchange="changeCurrency(this)">
        <?foreach ($this->getCurrencies() as $_code => $_name):?>
            <option value="<?=$_code?>"<?if($_code==$this->getCurrentCurrencyCode()):?> selected="selected"<?endif;?>>
                <?=$_name?> - <?=$_code?>
            </option>
        <?endforeach;?>
        </select>
</div>
<script type="text/javascript">
function changeCurrency(sObject){
    if(sObject.value){
        setLocation('<?=$this->helper('directory/url')->getSwitchCurrencyUrl()?>currency/'+sObject.value);
    }
}
</script>
<?endif;?>