<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?=$this->helper('adminhtml/media_js')->includeScript('lib/flex.js')?>
<?=$this->helper('adminhtml/media_js')->includeSkinScript('js/image.js')?>
<?=$this->helper('adminhtml/media_js')->getTranslatorScript()?>
<div id="<?=$this->getHtmlId()?>" class="editor" style="width:100%; height:100%;">
    <div class="buttons" style="margin-bottom: 20px;">
        <?=$this->getRotatecwButtonHtml()?>
        <?=$this->getRotateccwButtonHtml()?>
        <input type="text" id="<?=$this->_getButtonId('width')?>" size="7"/>
        x
        <input type="text" id="<?=$this->_getButtonId('height')?>" size="7"/> px
        <?=$this->getResizeButtonHtml()?>
        <?=$this->getImageButtonHtml()?>
    </div>


</div>
<textarea id="<?=$this->_getButtonId('b64')?>" rows="10" cols="50"></textarea>
<script type="text/javascript">
<?=$this->getJsObjectName()?> = new Flex.ImageEditor('<?=$this->getHtmlId()?>', '<?=$this->getSkinUrl('media/editor.swf')?>', <?=$this->getConfigJson()?>);
</script>