<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?=$this->helper('adminhtml/media_js')->includeScript('lib/flex.js')?>
<?=$this->helper('adminhtml/media_js')->includeSkinScript('js/flexuploader.js')?>
<?=$this->helper('adminhtml/media_js')->getTranslatorScript()?>
<div id="<?=$this->getHtmlId()?>" class="uploader">
    <div class="buttons">
        <?=$this->getBrowseButtonHtml()?>
        <?=$this->getUploadButtonHtml()?>
    </div>
    <div class="clear"></div>
    <div class="no-display" id="<?=$this->getHtmlId()?>-template">
        <div id="{{id}}" class="file-row">
        <span class="file-info">{{name}} ({{size}})</span>
        <span class="delete-button"><?=$this->getDeleteButtonHtml()?></span>
        <span class="progress-text"></span>
        <div class="clear"></div>
        </div>
    </div>
    <div class="no-display" id="<?=$this->getHtmlId()?>-template-progress">
        {{percent}}% {{uploaded}} / {{total}}
    </div>
</div>
<script type="text/javascript">
<?=$this->getJsObjectName()?> = new Flex.Uploader('<?=$this->getHtmlId()?>', '<?=$this->getSkinUrl('media/uploader.swf')?>', <?=$this->getConfigJson()?>);
</script>