<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<script type="text/javascript" src="<?=$this->getSkinUrl('js/giftmessage.js')?>"></script>
<?if(!$this->getSaveMode()):?>
<div class="page-head button-level">
    <h3><?=$this->__('Gift Message')?></h3>
</div>
<form action="<?=$this->getSaveUrl()?>" id="message-form" method="post" >
    <ul class="form-list a-left">
        <li>
            <div class="input-box">
                <label for="sender"><?=$this->__('From')?> <span class="required">*</span></label><br/>
                <input type="text" name="sender" value="<?=$this->getEscaped($this->getMessage()->getSender())?>" title="<?=$this->__('From')?>"  class="required-entry input-text"/>
            </div>
        </li>
        <li>
            <div class="input-box">
                <label for="recipient"><?=$this->__('To')?> <span class="required">*</span></label><br/>
                <input type="text" name="recipient" value="<?=$this->getEscaped($this->getMessage()->getRecipient())?>" title="<?=$this->__('To')?>"  class="required-entry input-text" />
            </div>
        </li>
        <li>
            <div class="input-box">
                <label for="email_address"><?=$this->__('Message')?> <span class="required">*</span></label><br />
                <textarea name="messagetext" title="<?=$this->__('Message')?>" class="required-entry input-text" cols="60" rows="5"><?=$this->getEscaped($this->getMessage()->getMessage())?></textarea>
            </div>
        </li>
    </ul>
    <div class="button-set">
        <p class="required"><?=$this->__('* Required Fields')?></p>
        <button class="form-button" type="submit" name="send"><span><?=$this->__('Save')?></span></button> &nbsp;
        <button class="form-button listen-cancel" type="button"><span><?=$this->__('Cancel')?></span></button>
        <?if($this->getMessage()->getGiftMessageId()):?>
        <button class="form-button listen-remove" type="button"><span><?=$this->__('Remove')?></span></button>
        <?endif;?>
    </div>
</form>
<?elseif($this->getSaveMode()=='save'):?>
<h3><?=$this->__('Your gift message has been successfully saved')?></h3>
<br /><button class="form-button" type="button" onclick="giftMessageWindowObject.close()"><span><?=$this->__('Close')?></span></button>
<?else:?>
<h3><?=$this->__('Your gift message has been successfully removed')?></h3>
<br /><button class="form-button" type="button" onclick="giftMessageWindowObject.close()"><span><?=$this->__('Close')?></span></button>
<?endif;?>
<script type="text/javascript">
<!--
<?if(!$this->getSaveMode()):?>
    var giftMessageWindowObject = new GiftMessageWindow('<?=$this->getUniqueId()?>','message-form', '<?=$this->getRemoveUrl()?>');
    giftMessageWindowObject.confirmMessage = '<?=$this->getEscapedForJs($this->__('Are you sure?'))?>';
<?else:?>
    var giftMessageWindowObject = new GiftMessageWindow('<?=$this->getUniqueId()?>', null, '<?=$this->getRemoveUrl()?>');
    Event.observe(window, 'load', function(evt) {
        giftMessageWindowObject.updateParent('<?=$this->getEditUrl()?>', '<?=$this->getButtonUrl()?>');
    });
<?endif;?>
//-->
</script>