<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?if(!$this->getScriptIncluded() && $this->getCanDisplayContainer()):?>
<script type="text/javascript" src="<?=$this->getSkinUrl('js/giftmessage.js')?>"></script>
<?$this->setScriptIncluded(true);?>
<?endif;?>
<?if($this->getCanDisplayContainer()):?>
<div id="<?=$this->getId()?>">
<?endif;?>
<?switch ($this->getType()):?>
<?case 'item':?>
    <button class="form-button-alt listen-for-click" type="button"><span>
        <?if($this->hasGiftMessage()):?>
        <?=$this->__('Edit')?>
        <?else:?>
        <?=$this->__('Add')?>
        <?endif;?>
    </span></button>
    <?break;?>
<?case 'main':?>
    <a href="#" class="listen-for-click">
        <?if($this->hasGiftMessage()):?>
        <?=$this->__('Edit Gift Message')?>
        <?else:?>
        <?=$this->__('Add Gift Message')?>
        <?endif;?>
    </a>
    <?break;?>
<?case 'address':?>
    <a href="#" class="listen-for-click">
        <?if($this->hasGiftMessage()):?>
        <?=$this->__('Edit Gift Message')?>
        <?else:?>
        <?=$this->__('Add Gift Message')?>
        <?endif;?>
    </a>
    <?break;?>
<?case 'address_item':?>
    <button class="form-button-alt listen-for-click" type="button"><span>
        <?if($this->hasGiftMessage()):?>
        <?=$this->__('Edit')?>
        <?else:?>
        <?=$this->__('Add')?>
        <?endif;?>
    </span></button>
    <?break;?>
<?endswitch?>
<?if($this->getCanDisplayContainer()):?>
</div>
<script type="text/javascript">
<!--
var <?=$this->getJsObjectName()?> = new GiftMessage('<?=$this->getId()?>');
<?=$this->getJsObjectName()?>.url = '<?=$this->getEditUrl()?>';
//-->
</script>
<?endif;?>