<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?if(!$this->getDontDisplayContainer()):?>
<script type="text/javascript">
if(!window.toogleVisibilityOnObjects) {
    var toogleVisibilityOnObjects = function(source, objects) {
        if($(source) && $(source).checked) {
            objects.each(function(item){
                $(item).show();
                $(item).getElementsByClassName('input-text').each(function(item) {
                    item.removeClassName('validation-passed');
                });
            });


        } else {
            objects.each(function(item){
                $(item).hide();
                $(item).getElementsByClassName('input-text').each(function(sitem) {
                    sitem.addClassName('validation-passed');
                });

                 $(item).getElementsByClassName('giftmessage-area').each(function(sitem) {
                    sitem.value = '';
                });
            });

        }

    }
}
if(!window.toogleRequired) {
    var toogleRequired = function (source, objects)
    {
        if(!$(source).value.blank()) {
            objects.each(function(item) {
               $(item).addClassName('required-entry');
            });
        } else {
            objects.each(function(item) {
                if(shippingMethod && shippingMethod.validator) {
                   shippingMethod.validator.reset(item);
                }
                $(item).removeClassName('required-entry');
            });

        }
    }
}
if(window.shipping) {

shipping.onSave = function(evt){
    new Ajax.Updater('onepage-checkout-shipping-method-additional-load', '<?=$this->getAdditionalUrl();?>', {onSuccess: function() {
          this.nextStep(evt);
    }.bind(this), evalScripts:true});
}.bindAsEventListener(shipping);

billing.onSave = function(evt){
    new Ajax.Updater('onepage-checkout-shipping-method-additional-load', '<?=$this->getAdditionalUrl();?>', {onSuccess: function() {
          this.nextStep(evt);
    }.bind(this), evalScripts:true});
}.bindAsEventListener(billing);

}
</script>
<?endif?>
<div class="giftmessages">
<?switch ($this->getType()):?>
<?case 'onepage_checkout':?>
    <div class="inner-box">
        <span class="gift-header"><?=$this->__('Do you have any gift items in your order?');?></span>
        <div class="clear"></div>
        <div class="a-left input-checkbox">
            <input type="checkbox" name="allow_gift_messages" id="allow_gift_messages" value="1" onclick="toogleVisibilityOnObjects(this, ['allow-gift-message-container']);" <?if($this->getItemsHasMesssages() || $this->getEntityHasMessage()):?>checked<?endif?>/>
            <label for="allow_gift_messages"><?=$this->__('Check this checkbox if you want to add gift messages.')?></label>
        </div>
        <div class="clear"></div>
    </div>
    <div class="gift-box" id="allow-gift-message-container">
        <div class="scroll-box">
            <span class="gift-header"><?=$this->__('Enter a gift message for entire order.');?></span>
            <p><?=$this->__('You can leave a box blank if you don\'t wish to add a gift message for whole order.')?></p>
            <fieldset class="group-select">
                <input type="hidden" name="giftmessage[<?=$this->getEntity()->getId()?>][type]"  value="quote"/>
                <ul class="no-padding">
                    <li>
                        <div class="input-box">
                            <label for="gift-message-whole-from"><?=$this->__('From')?></label><br />
                            <input type="text" name="giftmessage[<?=$this->getEntity()->getId()?>][from]" id="gift-message-whole-from" title="<?=$this->__('From')?>"  value="<?=$this->getEscaped($this->getMessage()->getSender(), $this->getDefaultFrom())?>" class="input-text validation-passed"/>
                        </div>
                        <div class="input-box">
                            <label for="gift-message-whole-to"><?=$this->__('To')?></label><br />
                            <input type="text" name="giftmessage[<?=$this->getEntity()->getId()?>][to]" id="gift-message-whole-to" title="<?=$this->__('To')?>" value="<?=$this->getEscaped($this->getMessage()->getRecipient(), $this->getDefaultTo())?>" class="input-text validation-passed"/>
                        </div>
                    </li>
                    <li>
                        <label for="gift-message-whole-message"><?=$this->__('Message')?></label>
                        <br/>
                        <textarea id="gift-message-whole-message" onchange="toogleRequired('gift-message-whole-message', ['gift-message-whole-from','gift-message-whole-to'])" class="input-text validation-passed giftmessage-area" name="giftmessage[<?=$this->getEntity()->getId()?>][message]" title="<?=$this->__('Message')?>" ><?=$this->getEscaped($this->getMessage()->getMessage())?></textarea>
                    </li>
                    <script type="text/javascript">
                        toogleRequired('gift-message-whole-message', ['gift-message-whole-from','gift-message-whole-to']);
                    </script>
                </ul>
             </fieldset>
             <?if($this->isItemsAvailable()):?>
             <span class="gift-header"><?=$this->__('Enter a gift message for each item in your order.');?></span><div class="clear"></div>
             <p><?=$this->__('You can leave a box blank if you don\'t wish to add a gift message for the item.')?></p>
             <?foreach($this->getItems() as $_index=>$_item):?>
             <?$_product=$_item->getProduct()?>
               <div class="left">
                    <img width="75" class="product-image" src="<?=$this->helper('checkout')->getQuoteItemProductImageUrl($_item);?>"  alt="<?=$this->htmlEscape($_product->getName())?>"/><br />
                    <span class="numeration"><?=$this->__('Item %d of %d', $_index+1, $this->countItems())?></span>
               </div>
               <div class="left">
                    <h5 class="giftmessage-product-info"><?=$_product->getName()?></h5>
                    <fieldset class="group-select">
                        <input type="hidden" name="giftmessage[<?=$_item->getId()?>][type]"  value="quote_item"/>
                        <ul class="no-padding">
                            <li>
                                <div class="input-box">
                                    <label for="gift-message-<?=$_item->getId()?>-from"><?=$this->__('From')?></label><br />
                                    <input type="text" name="giftmessage[<?=$_item->getId()?>][from]" id="gift-message-<?=$_item->getId()?>-from" title="<?=$this->__('From')?>"  value="<?=$this->getEscaped($this->getMessage($_item)->getSender(), $this->getDefaultFrom())?>" class="input-text validation-passed"/>
                                </div>
                                <div class="input-box">
                                    <label for="gift-message-<?=$_item->getId()?>-to"><?=$this->__('To')?></label><br />
                                    <input type="text" name="giftmessage[<?=$_item->getId()?>][to]" id="gift-message-<?=$_item->getId()?>-to" title="<?=$this->__('To')?>" value="<?=$this->getEscaped($this->getMessage($_item)->getRecipient(), $this->getDefaultTo())?>" class="input-text validation-passed"/>
                                </div>
                            </li>
                            <li>
                                <label for="gift-message-<?=$_item->getId()?>-message"><?=$this->__('Message')?></label>
                                <br/>
                                <textarea id="gift-message-<?=$_item->getId()?>-message" onchange="toogleRequired('gift-message-<?=$_item->getId()?>-message', ['gift-message-<?=$_item->getId()?>-from','gift-message-<?=$_item->getId()?>-to'])" class="input-text validation-passed  giftmessage-area" name="giftmessage[<?=$_item->getId()?>][message]" title="<?=$this->__('Message')?>" ><?=$this->getEscaped($this->getMessage($_item)->getMessage())?></textarea>
                            </li>
                            <script type="text/javascript">
                                toogleRequired('gift-message-<?=$_item->getId()?>-message', ['gift-message-<?=$_item->getId()?>-from','gift-message-<?=$_item->getId()?>-to']);
                            </script>
                        </ul>
                    </fieldset>
             </div>
             <div class="clear"></div>
             <?endforeach;?>
             <?endif;?>
        </div>
    </div>
    <script type="text/javascript">
        toogleVisibilityOnObjects('allow_gift_messages', ['allow-gift-message-container']);
    </script>
    <?break;?>
    <?case 'multishipping_adress_checkbox':?>

    <?break;?>
    <?case 'multishipping_adress':?>
     <br />
    <div class="inner-box">
        <span class="gift-header"><?=$this->__('Gift Messages');?></span>
        <div class="clear"></div>
        <div class="a-left input-checkbox">
            <input type="checkbox" name="allow_gift_messages_<?=$this->getEntity()->getId()?>" id="allow_gift_messages_<?=$this->getEntity()->getId()?>" value="1" onclick="toogleVisibilityOnObjects(this, ['allow-gift-message-container-<?=$this->getEntity()->getId()?>']);" <?if($this->getItemsHasMesssages() || $this->getEntityHasMessage()):?>checked<?endif?>/>
            <label for="allow_gift_messages_<?=$this->getEntity()->getId()?>"><?=$this->__('Check this checkbox if you want to add gift messages to your items.')?></label>
        </div>
        <div class="clear"></div>
    </div>
    <div id="allow-gift-message-container-<?=$this->getEntity()->getId()?>">

        <span class="gift-header"><?=$this->__('Enter a gift message for this address.');?></span>
        <p><?=$this->__('You can leave a box blank if you don\'t wish to add a gift message for this address.')?></p>
        <fieldset class="group-select no-border no-padding">
        <input type="hidden" name="giftmessage[<?=$this->getEntity()->getId()?>][type]"  value="quote_address"/>
            <ul class="no-padding">
             <li>
                <div class="input-box">
                    <label for="gift-message-<?=$this->getEntity()->getId()?>-from"><?=$this->__('From')?></label><br />
                    <input type="text" name="giftmessage[<?=$this->getEntity()->getId()?>][from]" id="gift-message-<?=$this->getEntity()->getId()?>-from" title="<?=$this->__('From')?>"  value="<?=$this->getEscaped($this->getMessage()->getSender(), $this->getDefaultFrom())?>" class="input-text validation-passed"/>
                </div>
                <div class="input-box">
                    <label for="gift-message-<?=$this->getEntity()->getId()?>-to"><?=$this->__('To')?></label><br />
                    <input type="text" name="giftmessage[<?=$this->getEntity()->getId()?>][to]" id="gift-message-<?=$this->getEntity()->getId()?>-to" title="<?=$this->__('To')?>" value="<?=$this->getEscaped($this->getMessage()->getRecipient(), $this->getDefaultTo())?>" class="input-text validation-passed"/>
                </div>
            </li>
            <li>
                <label for="gift-message-<?=$this->getEntity()->getId()?>-message"><?=$this->__('Message')?></label>
                <br/>
                <textarea id="gift-message-<?=$this->getEntity()->getId()?>-message" onchange="toogleRequired('gift-message-<?=$this->getEntity()->getId()?>-message', ['gift-message-<?=$this->getEntity()->getId()?>-from','gift-message-<?=$this->getEntity()->getId()?>-to'])" class="input-text validation-passed giftmessage-area" name="giftmessage[<?=$this->getEntity()->getId()?>][message]" title="<?=$this->__('Message')?>" ><?=$this->getEscaped($this->getMessage()->getMessage())?></textarea>
            </li>
            <script type="text/javascript">
                var shippingMethod = new VarienForm('shipping_method_form');
                toogleRequired('gift-message-<?=$this->getEntity()->getId()?>-message', ['gift-message-<?=$this->getEntity()->getId()?>-from','gift-message-<?=$this->getEntity()->getId()?>-to']);
            </script>
            </ul>
         </fieldset>
         <?if($this->isItemsAvailable()):?>
         <span class="gift-header"><?=$this->__('Enter a gift message for each item in your order.');?></span><div class="clear"></div>
         <p><?=$this->__('You can leave a box blank if you don\'t wish to add a gift message for the item.')?></p>
         <?foreach($this->getItems() as $_index=>$_item):?>
         <?$_product=$_item->getProduct()?>
           <div class="left">
                <img width="75" class="product-image" src="<?=$this->helper('checkout')->getQuoteItemProductImageUrl($_item);?>"  alt="<?=$this->htmlEscape($_product->getName())?>"/><br />
                <span class="numeration"><?=$this->__('Item %d of %d', $_index+1, $this->countItems())?></span>
           </div>
           <div class="left">
                <h5 class="giftmessage-product-info"><?=$_product->getName()?></h5>
                <fieldset class="group-select no-padding no-border">
                    <input type="hidden" name="giftmessage[<?=$_item->getId()?>][type]"  value="quote_address_item"/>
                    <ul class="no-padding">
                        <li>
                            <div class="input-box">
                                <label for="gift-message-<?=$_item->getId()?>-from"><?=$this->__('From')?></label><br />
                                <input type="text" name="giftmessage[<?=$_item->getId()?>][from]" id="gift-message-<?=$_item->getId()?>-from" title="<?=$this->__('From')?>"  value="<?=$this->getEscaped($this->getMessage($_item)->getSender(), $this->getDefaultFrom())?>" class="input-text validation-passed"/>
                            </div>
                            <div class="input-box">
                                <label for="gift-message-<?=$_item->getId()?>-to"><?=$this->__('To')?></label><br />
                                <input type="text" name="giftmessage[<?=$_item->getId()?>][to]" id="gift-message-<?=$_item->getId()?>-to" title="<?=$this->__('To')?>" value="<?=$this->getEscaped($this->getMessage($_item)->getRecipient(), $this->getDefaultTo())?>" class="input-text validation-passed"/>
                            </div>
                        </li>
                        <li>
                            <label for="gift-message-<?=$_item->getId()?>-message"><?=$this->__('Message')?></label>
                            <br/>
                            <textarea id="gift-message-<?=$_item->getId()?>-message" onchange="toogleRequired('gift-message-<?=$_item->getId()?>-message', ['gift-message-<?=$_item->getId()?>-from','gift-message-<?=$_item->getId()?>-to'])" class="input-text validation-passed  giftmessage-area" name="giftmessage[<?=$_item->getId()?>][message]" title="<?=$this->__('Message')?>" ><?=$this->getEscaped($this->getMessage($_item)->getMessage())?></textarea>
                        </li>
                        <script type="text/javascript">
                            toogleRequired('gift-message-<?=$_item->getId()?>-message', ['gift-message-<?=$_item->getId()?>-from','gift-message-<?=$_item->getId()?>-to']);
                        </script>
                    </ul>
                </fieldset>
         </div>
         <div class="clear"></div>
         <?endforeach;?>
         <?endif;?>
    </div>
    <script type="text/javascript">
        toogleVisibilityOnObjects('allow_gift_messages_<?=$this->getEntity()->getId()?>', ['allow-gift-message-container-<?=$this->getEntity()->getId()?>']);
    </script>
    <?break;?>
<?endswitch?>
</div>