<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div id="answers_container">
<?if( !$answers ):?>
<?else:?>
    <h4 class="icon-head head-edit-form fieldset-legend"><?=Mage::helper('poll')->__('Assigned Answers')?></h4>
    <?foreach($answers->getItems() as $_item):?>
        <fieldset id="poll_answer_fieldset_<?=$_item->getId()?>">
        <span class="field-row">
            <label for="answer_<?=$_item->getId()?>"><?=Mage::helper('poll')->__('Answer Title:')?> <span class="required">*</span></label>
            <input id="answer_<?=$_item->getId()?>" name="answer[<?=$_item->getId()?>][title]" value="<?=$_item->getAnswerTitle()?>" class="required-entry input-text" type="text" />
        </span>
        <?=$this->getDeleteButtonHtml()?>
        <span class="field-row">
            <label for="answer_votes_<?=$_item->getId()?>"><?=Mage::helper('poll')->__('Votes Count:')?> <span class="required">*</span></label>
            <input id="answer_votes_<?=$_item->getId()?>" name="answer[<?=$_item->getId()?>][votes]" value="<?=$_item->getVotesCount()?>" class="required-entry validate-not-negative-number input-text" type="text" />
        </span>
        <input type="hidden" id="id_poll_answer_fieldset_<?=$_item->getId()?>" value="<?=$_item->getId()?>" />
        </fieldset>
    <?endforeach;?>
<?endif;?>
</div>
<?=$this->getAddButtonHtml();?>

<script type="text/javascript">
    var lastId = 0;
    var answer = function() {
        return {
            del : function(obj) {
                if( confirm('<?=Mage::helper('poll')->__('Are you sure you want to delete it?')?>') ) {
                    if( $('id_' + obj.parentNode.id) ) {
                        var itemId = $('id_' + obj.parentNode.id).value;
                        var newElement = document.createElement('input');
                        newElement.type = 'hidden';
                        newElement.value = itemId;
                        newElement.name = 'deleteAnswer[]';
                        $('answers_container').appendChild(newElement);
                    }
                    obj.parentNode.remove();
                }
            },

            add : function(obj) {
                var newElement = document.createElement('div');
                newElement.innerHTML = this.getTemplate();
                $('answers_container').appendChild(newElement);
            },

            getTemplate : function() {
                var id = this.createId();
                return  '<fieldset id="poll_answer_fieldset_' + id + '">'
                       +'<span class="field-row">'
                       +    '<label for="answer_' + id + '"><?=Mage::helper('poll')->__('Answer Title:')?> <span class="required">*</span></label>'
                       +    '<input id="answer_' + id + '" name="answer[' + id + '][title]" value="" class="required-entry input-text" type="text" />'
                       +'</span>'
                       +'<?=$this->getDeleteButtonHtml()?>'
                       +'<span class="field-row">'
                       +    '<label for="answer_votes_' + id + '"><?=Mage::helper('poll')->__('Votes Count:')?> <span class="required">*</span></label>'
                       +    '<input id="answer_votes_' + id + '" name="answer[' + id + '][votes]" value="0" class="required-entry validate-not-negative-number input-text" type="text" />'
                       +'</span>'
                       +'</fieldset>';
            },

            createId : function () {
                return --lastId;
            }
        }
    }();
</script>
