<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<p class="switcher"><label for="store_switcher"><?=$this->__('Choose Store')?>:</label>
<select name="store_switcher" id="store_switcher" class="left-col-block" onchange="return switchStore(this);">
    <option value=""><?=$this->getDefaultStoreName()?></option>
    <?foreach ($this->getWebsiteCollection() as $_website):?>
    <?$_storesCollection = $this->getStores($_website)?>
    <?if($_storesCollection->getSize()):?>
        <optgroup label="<?=$_website->getName()?>">
        <?foreach ($_storesCollection as $_store):?>
            <option value="<?=$_store->getId()?>"<?if($this->getStoreId() == $_store->getId()):?> selected<?endif;?>><?=$_store->getName()?></option>
        <?endforeach;?>
        </optgroup>
    <?endif;?>
    <?endforeach;?>
</select>
</p>
<script type="text/javascript">
    function switchStore(obj){
        var storeParam = obj.value ? 'store/'+obj.value + '/' : '';
        if(obj.switchParams){
            storeParam+= obj.switchParams;
        }
    <?if($this->getUseConfirm()):?>
        if(confirm("<?=$this->__('Please confirm site switching. All data that hasn\'t been saved will be lost.')?>")){
            setLocation('<?=$this->getSwitchUrl()?>'+storeParam);
            return true;
        }
        else {
            obj.value = '<?=$this->getStoreId()?>';
        }
        return false;
    <?else:?>
        setLocation('<?=$this->getSwitchUrl()?>'+storeParam);
    <?endif;?>
    }
</script>
