<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?$_websiteCollection = $this->getWebsiteCollection()?>
<?if ($_websiteCollection->getSize()):?>
<p class="switcher"><label for="store_switcher"><?=$this->__('Choose Store View')?>:</label>
<select name="store_switcher" id="store_switcher" class="left-col-block" onchange="return switchStore(this);">
    <option value=""><?=$this->getDefaultStoreName()?></option>
    <?foreach ($_websiteCollection as $_website):?>
        <?$showWebsite=false;?>
        <?foreach ($this->getGroupCollection($_website) as $_group):?>
            <?$showGroup=false;?>
            <?foreach ($this->getStoreCollection($_group) as $_store):?>
                <?if ($showWebsite == false):?>
                    <?$showWebsite = true;?>
                    <optgroup label="<?=$_website->getName()?>"></optgroup>
                <?endif;?>
                <?if ($showGroup == false):?>
                    <?$showGroup = true;?>
                    <optgroup label="&nbsp;&nbsp;&nbsp;<?=$_group->getName()?>">
                <?endif;?>
                <option value="<?=$_store->getId()?>"<?if($this->getStoreId() == $_store->getId()):?> selected<?endif;?>>&nbsp;&nbsp;&nbsp;&nbsp;<?=$_store->getName()?></option>
            <?endforeach;?>
            <?if ($showGroup):?>
                </optgroup>
            <?endif;?>
        <?endforeach;?>
    <?endforeach;?>
</select>
</p>
<script type="text/javascript">
    function switchStore(obj){
        var storeParam = obj.value ? 'store/'+obj.value + '/' : '';
        if(obj.switchParams){
            storeParam+= obj.switchParams;
        }
    <?if($this->getUseConfirm()):?>
        if(confirm("<?=$this->__('Please confirm site switching. All data that hasn\'t been saved will be lost.')?>")){
            setLocation('<?=$this->getSwitchUrl()?>'+storeParam);
            return true;
        }
        else {
            obj.value = '<?=$this->getStoreId()?>';
        }
        return false;
    <?else:?>
        setLocation('<?=$this->getSwitchUrl()?>'+storeParam);
    <?endif;?>
    }
</script>
<?endif;?>