<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?
/**
 * @methods
 * - getValue($key, $default)
 * - getSelected($key, $value)
 * - getChecked($key)
 * - getAttributes()
 * - getMappings()
 * - getAddMapButtonHtml()
 * - getRemoveMapButtonHtml()
 */
?>

<style type="text/css">
    #profile-generator select, #profile-generator input.input-text { width:200px; }
</style>
<script type="text/javascript">
function showOption(select)
{
    select = $(select);
    for (var i = 0, l = select.options.length; i<l; i++) {
        $$('.'+select.id+'_'+select.options[i].value).each(function (el) {
            el.style.display = select.selectedIndex==i ? '' : 'none';
        });
    }

}

function addFieldMapping()
{
    var entityType = $('profile_entity_type').value;
    new Insertion.Bottom($('map_container_'+entityType), $('map_template_'+entityType).innerHTML);
}

function removeFieldMapping(button)
{
    Element.remove(button.parentNode);
}

function setMapFileField(select)
{
    select.parentNode.getElementsByTagName('input')[0].value = select.value;
}

function toggleSelectOption(type, source, target, sourceValue, targetValue, targetText)
{
    source = $(source);
    target = $(target);

    var i, ex, option, present;
    var selectValue = source.options[source.selectedIndex].value;

    if('remove'==type && selectValue==sourceValue || 'add'==type && selectValue!=sourceValue) {
        for(i=0;i<target.options.length;i++){
            if(target.options[i].value==targetValue){
                target.remove(i);
                break;
            }
        }
    } else {
        for(i=0;i<target.options.length;i++){
            if(target.options[i].value==targetValue){
                present = true;
                break;
            } else {
                present = false;
            }
        }
        if(!present){
            option = document.createElement("OPTION");
        	option.text = targetText;
        	option.value = targetValue;
        	try {
        		target.add(option, null); // standards compliant; doesn't work in IE
        	} catch(ex) {
        		target.add(option); // IE only
        	}
        }
    }
    showOption(target);
}

function changeEntityType()
{
    toggleSelectOption('remove', 'profile_entity_type', 'profile_direction', 'customer', 'import', '<?=$this->__('Import')?>');
    toggleSelectOption('remove', 'profile_entity_type', 'profile_store_id', 'customer', '0', '<?=$this->__('Default Values')?>');
    //showOption('profile_direction');
    changeDirection();
}


function changeDirection()
{
    toggleSelectOption('remove', 'profile_direction', 'profile_data_transfer', 'export', 'interactive', '<?=$this->__('Interactive')?>');
    //showOption('profile_data_transfer');
}
</script>

<div id="profile-generator" class="entry-edit profile-generator">
    <h4 class="icon-head head-edit-form fieldset-legend"><?=$this->__("Profile Information")?></h4>
    <fieldset>
        <legend><?=$this->__("Profile Information")?></legend>
        <span class="field-row">
            <label for="profile_name"><?=$this->__("Name:")?></label>
            <input class="input-text" id="profile_name" name="name" value="<?=$this->getValue('name')?>"/>
        </span>
        <span class="field-row">
            <label for="profile_entity_type"><?=$this->__("Entity type:")?></label>
            <select id="profile_entity_type" name="entity_type" onchange="showOption(this);changeEntityType();" class="option-control">
                <option value="product" <?=$this->getSelected('entity_type', 'product')?>><?=$this->__("Products")?></option>
                <option value="customer" <?=$this->getSelected('entity_type', 'customer')?>><?=$this->__("Customers")?></option>
            </select>
        </span>
        <span class="field-row">
            <label for="profile_direction"><?=$this->__("Direction:")?></label>
            <select id="profile_direction" name="direction" onchange="showOption(this);changeDirection();" class="option-control">
                <option value="import" <?=$this->getSelected('direction', 'import')?>><?=$this->__("Import")?></option>
                <option value="export" <?=$this->getSelected('direction', 'export')?>><?=$this->__("Export")?></option>
            </select>
        </span>
        <span class="field-row">
            <label for="profile_store_id"><?=$this->__("Store:")?></label>
            <select id="profile_store_id" name="store_id">
                <?foreach ($this->getStores() as $_value=>$_label):?>
                    <option value="<?=$_value?>" <?=$this->getSelected('store_id', $_value)?>><?=htmlspecialchars($_label)?></option>
                <?endforeach?>
            </select>
            <span class="profile_direction_import profile_entity_type_product">
                    <?=$this->__("(Products will be added/updated to this store if 'store' column is blank or missing in the import file.)")?>
            </span>
        </span>
    </fieldset>

    <h4 class="icon-head head-edit-form fieldset-legend"><?=$this->__("File Information")?></h4>
    <fieldset>
        <legend><?=$this->__("File Information")?></legend>
        <span class="field-row">
            <label for="profile_data_transfer"><?=$this->__("Data transfer:")?></label>
            <select id="profile_data_transfer" name="data_transfer" onchange="showOption(this)" class="option-control">
                <option value="interactive" <?=$this->getSelected('data_transfer', 'interactive')?>><?=$this->__("Interactive")?></option>
                <option value="file" <?=$this->getSelected('data_transfer', 'file')?>><?=$this->__("Local/Remote Server")?></option>
            </select>
        </span>
        <!--
        <div class="profile_data_transfer_interactive">
            <span class="field-row">
                <label for="interactive_filename"><?=$this->__("Archive file name:")?></label>
                <input class="input-text" id="interactive_filename" name="gui_data[interactive][filename]" value="<?=$this->getValue('gui_data/interactive/filename')?>"/>
                <?=$this->__('(If left empty will be auto-generated)')?>
            </span>
        </div>
        -->
        <div class="profile_data_transfer_file">
            <span class="field-row">
                <label for="file_type"><?=$this->__("Type:")?></label>
                <select id="file_type" name="gui_data[file][type]" onchange="showOption(this)" class="option-control">
                    <option value="file" <?=$this->getSelected('gui_data/file/type', 'file')?>><?=$this->__("Local Server")?></option>
                    <option value="ftp" <?=$this->getSelected('gui_data/file/type', 'ftp')?>><?=$this->__("Remote FTP")?></option>
                </select>
            </span>
            <span class="field-row">
                <label for="file_filename"><?=$this->__("File name:")?></label>
                <input class="input-text" id="file_filename" name="gui_data[file][filename]" value="<?=$this->getValue('gui_data/file/filename')?>"/>
            </span>
            <span class="field-row">
                <label for="file_path"><?=$this->__("Path:")?></label>
                <input class="input-text" id="file_path" name="gui_data[file][path]" value="<?=$this->getValue('gui_data/file/path')?>"/>
                <span class="file_type_file">
                    <?=$this->__('(Absolute path or Relative to Magento install root, ex. var/export)')?>
                </span>
            </span>
            <div class="file_type_ftp">
                <span class="field-row">
                    <label for="file_host"><?=$this->__("FTP Host[:Port]")?></label>
                    <input class="input-text" id="file_host" name="gui_data[file][host]" value="<?=$this->getValue('gui_data/file/host')?>"/>
                </span>
                <span class="field-row">
                    <label for="file_user"><?=$this->__("User name")?></label>
                    <input class="input-text" id="file_user" name="gui_data[file][user]" value="<?=$this->getValue('gui_data/file/user')?>"/>
                </span>
                <span class="field-row">
                    <label for="file_password"><?=$this->__("Password")?></label>
                    <input class="input-text" id="io_password" name="gui_data[file][password]" value="<?=$this->getValue('gui_data/file/password')?>"/>
                </span>
                <span class="field-row">
                    <label for="file_passive"><?=$this->__("Passive mode")?></label>
                    <select id="file_passive" name="gui_data[file][passive]" onchange="showOption(this)" class="option-control">
                        <option value="" <?=$this->getSelected('gui_data/file/passive', false)?>><?=$this->__("No")?></option>
                        <option value="true" <?=$this->getSelected('gui_data/file/passive', true)?>><?=$this->__("Yes")?></option>
                    </select>
                </span>
            </div>
        </div>
    </fieldset>

    <h4 class="icon-head head-edit-form fieldset-legend"><?=$this->__("Data Format")?></h4>
    <fieldset>
        <legend><?=$this->__("Data Format")?></legend>
        <span class="field-row">
            <label for="parse_type"><?=$this->__("Type:")?></label>
            <select id="parse_type" name="gui_data[parse][type]" onchange="showOption(this)" class="option-control">
                <option value="excel_xml" <?=$this->getSelected('gui_data/parse/type', 'excel_xml')?>><?=$this->__("MS Excel XML")?></option>
                <option value="csv" <?=$this->getSelected('gui_data/parse/type', 'csv')?>><?=$this->__("CSV / Tab separated")?></option>
            </select>
        </span>
        <div class="parse_type_excel_xml">
            <span class="field-row">
                <label for="parse_single_sheet"><?=$this->__("Spreadsheet Name:")?></label>
                <input class="input-text" id="parse_single_sheet" name="gui_data[parse][single_sheet]" value="<?=$this->getValue('gui_data/parse/single_sheet')?>"/> <?=$this->__("(Leave empty for first spreadsheet)")?>
            </span>
        </div>
        <div class="parse_type_csv">
            <span class="field-row">
                <label for="parse_delimiter"><?=$this->__("Value Delimiter:")?></label>
                <input class="input-text" style="width:3em" id="parse_delimiter" name="gui_data[parse][delimiter]" value="<?=$this->getValue('gui_data/parse/delimiter', ',')?>"/> <?=$this->__("(\\t for tab)")?>
            </span>
            <span class="field-row">
                <label for="parse_enclose"><?=$this->__("Enclose Values In:")?></label>
                <input class="input-text" style="width:3em" id="parse_enclose" name="gui_data[parse][enclose]" value="<?=$this->getValue('gui_data/parse/enclose', '"')?>"/>
            </span>
        </div>
        <span class="field-row">
            <label for="parse_fieldnames"><?=$this->__("Field names in first row:")?></label>
            <select id="parse_fieldnames" name="gui_data[parse][fieldnames]" onchange="showOption(this)" class="option-control">
                <option value="" <?=$this->getSelected('gui_data/parse/fieldnames', false)?>><?=$this->__("No")?></option>
                <option value="true" <?=$this->getSelected('gui_data/parse/fieldnames', true)?>><?=$this->__("Yes")?></option>
            </select>
            <span class="profile_direction_import">
                <span class="parse_fieldnames_">
                    <?=$this->__("(When 'No', only mapped fields will be imported. When mapping, use 'column1', 'column2', etc.)")?>
                </span>
            </span>
        </span>
        <div class="profile_direction_export">
            <span class="field-row">
                <label for="map_only_specified"><?=$this->__("Export:")?></label>
                <select id="map_only_specified" name="gui_data[map][only_specified]" onchange="showOption(this)">
                    <option value="" <?=$this->getSelected('gui_data/map/only_specified', false)?>><?=$this->__("All fields")?></option>
                    <option value="true" <?=$this->getSelected('gui_data/map/only_specified', true)?>><?=$this->__("Only mapped fields")?></option>
                </select>
            </span>
        </div>
    </fieldset>

    <h4 class="icon-head head-edit-form fieldset-legend"><?=$this->__("Field Mapping")?></h4>
    <fieldset>
        <legend><?=$this->__("Field Mapping")?></legend>
        <?foreach (array('product', 'customer') as $_entityType):?>
            <div class="profile_entity_type_<?=$_entityType?>">
                <div id="map_template_<?=$_entityType?>" style="display:none">
                    <span class="field-row">
                        <?=$this->__("In Database:")?> <select name="gui_data[map][<?=$_entityType?>][db][]" onchange="setMapFileField(this)">
                            <?foreach ($this->getAttributes($_entityType) as $_value=>$_label):?>
                                <option value="<?=$_value?>"><?=$_label?></option>
                            <?endforeach?>
                        </select>
                        &lt;--&gt;
                        <?=$this->__("In File:")?> <input class="input-text" name="gui_data[map][<?=$_entityType?>][file][]"/>
                        <?=$this->getRemoveMapButtonHtml()?>
                    </span>
                </div>
                <div id="map_container_<?=$_entityType?>">
                    <?foreach ($this->getMappings($_entityType) as $_i=>$_dbField):?>
                        <span class="field-row">
                            <?=$this->__("In Database:")?> <select name="gui_data[map][<?=$_entityType?>][db][]">
                            <?foreach ($this->getAttributes($_entityType) as $_value=>$_label):?>
                                <option value="<?=$_value?>" <?=$this->getSelected('gui_data/map/'.$_entityType.'/db/'.$_i, $_value)?>><?=$_label?></option>
                            <?endforeach?>
                            </select>
                            &lt;--&gt;
                            <?=$this->__("In File:")?> <input class="input-text" name="gui_data[map][<?=$_entityType?>][file][]" value="<?=$this->getValue('gui_data/map/'.$_entityType.'/file/'.$_i)?>"/>
                            <?=$this->getRemoveMapButtonHtml()?>
                        </span>
                    <?endforeach?>
                </div>
            </div>
        <?endforeach?>
        <?=$this->getAddMapButtonHtml()?>
    </fieldset>

    <div class="profile_direction_export">
        <h4 class="icon-head head-edit-form fieldset-legend"><?=$this->__("Export Filters")?></h4>
        <fieldset>
            <div class="profile_entity_type_product">
                <span class="field-row">
                    <label for="product_filter_name"><?=$this->__("Name:")?></label>
                    <input class="input-text" id="product_filter_name" name="gui_data[product][filter][name]" value="<?=$this->getValue('gui_data/product/filter/name')?>"/>
                    <?=$this->__('(Starting with)')?>
                </span>
                <span class="field-row">
                    <label for="product_filter_sku"><?=$this->__("SKU:")?></label>
                    <input class="input-text" id="product_filter_sku" name="gui_data[product][filter][sku]" value="<?=$this->getValue('gui_data/product/filter/sku')?>"/>
                    <?=$this->__('(Starting with)')?>
                </span>
                <span class="field-row">
                    <label for="product_filter_type"><?=$this->__("Type:")?></label>
                    <select id="product_filter_type" name="gui_data[product][filter][type]">
                        <?foreach ($this->getProductTypeFilterOptions() as $_value=>$_label):?>
                            <option value="<?=$_value?>" <?=$this->getSelected('gui_data/product/filter/type', $_value)?>><?=htmlspecialchars($_label)?></option>
                        <?endforeach?>
                    </select>
                </span>
                <span class="field-row">
                    <label for="product_filter_attribute_set"><?=$this->__("Attribute Set Name:")?></label>
                    <select id="product_filter_attribute_set" name="gui_data[product][filter][attribute_set]">
                        <?foreach ($this->getProductAttributeSetFilterOptions() as $_value=>$_label):?>
                            <option value="<?=$_value?>" <?=$this->getSelected('gui_data/product/filter/attribute_set', $_value)?>><?=htmlspecialchars($_label)?></option>
                        <?endforeach?>
                    </select>
                </span>
                <span class="field-row">
                    <label for="product_filter_price_from"><?=$this->__("Price:")?></label>
                    <input class="input-text" style="width:5em" id="product_filter_price_from" name="gui_data[product][filter][price][from]" value="<?=$this->getValue('gui_data/product/filter/price/from')?>"/> <?=$this->__('to')?>
                    <input class="input-text" style="width:5em" id="product_filter_price_to" name="gui_data[product][filter][price][to]" value="<?=$this->getValue('gui_data/product/filter/price/to')?>"/>
                </span>
                <span class="field-row">
                    <label for="product_filter_qty_from"><?=$this->__("Stock Quantity:")?></label>
                    <input class="input-text" style="width:5em" id="product_filter_qty_from" name="gui_data[product][filter][qty][from]" value="<?=$this->getValue('gui_data/product/filter/qty/from')?>"/> <?=$this->__('to')?>
                    <input class="input-text" style="width:5em" id="product_filter_qty_to" name="gui_data[product][filter][qty][to]" value="<?=$this->getValue('gui_data/product/filter/qty/to')?>"/>
                </span>
                <span class="field-row">
                    <label for="product_filter_visibility"><?=$this->__("Visibility:")?></label>
                    <select id="product_filter_visibility" name="gui_data[product][filter][visibility]">
                        <?foreach ($this->getProductVisibilityFilterOptions() as $_value=>$_label):?>
                            <option value="<?=$_value?>" <?=$this->getSelected('gui_data/product/filter/visibility', $_value)?>><?=htmlspecialchars($_label)?></option>
                        <?endforeach?>
                    </select>
                </span>
                <span class="field-row">
                    <label for="product_filter_status"><?=$this->__("Status:")?></label>
                    <select id="product_filter_status" name="gui_data[product][filter][status]">
                        <?foreach ($this->getProductStatusFilterOptions() as $_value=>$_label):?>
                            <option value="<?=$_value?>" <?=$this->getSelected('gui_data/product/filter/status', $_value)?>><?=htmlspecialchars($_label)?></option>
                        <?endforeach?>
                    </select>
                </span>
            </div>
            <div class="profile_entity_type_customer">
                <span class="field-row">
                    <label for="customer_filter_firstname"><?=$this->__("First Name:")?></label>
                    <input class="input-text" id="customer_filter_firstname" name="gui_data[customer][filter][firstname]" value="<?=$this->getValue('gui_data/customer/filter/firstname')?>"/>
                    <?=$this->__('(Starting with)')?>
                </span>
                <span class="field-row">
                    <label for="customer_filter_lastname"><?=$this->__("Last Name:")?></label>
                    <input class="input-text" id="customer_filter_lastname" name="gui_data[customer][filter][lastname]" value="<?=$this->getValue('gui_data/customer/filter/lastname')?>"/>
                    <?=$this->__('(Starting with)')?>
                </span>
                <span class="field-row">
                    <label for="customer_filter_email"><?=$this->__("Email:")?></label>
                    <input class="input-text" id="customer_filter_email" name="gui_data[customer][filter][email]" value="<?=$this->getValue('gui_data/customer/filter/email')?>"/>
                    <?=$this->__('(Starting with)')?>
                </span>
                <span class="field-row">
                    <label for="customer_filter_group"><?=$this->__("Group:")?></label>
                    <select id="customer_filter_group" name="gui_data[customer][filter][group]">
                        <?foreach ($this->getCustomerGroupFilterOptions() as $_value=>$_label):?>
                            <option value="<?=$_value?>" <?=$this->getSelected('gui_data/customer/filter/group', $_value)?>><?=htmlspecialchars($_label)?></option>
                        <?endforeach?>
                    </select>
                </span>
                <span class="field-row">
                    <label for="customer_filter_adressType"><?=$this->__("Address Type:")?></label>
                    <select id="customer_filter_adressType" name="gui_data[customer][filter][adressType]" >
                            <option value="default_billing" <?=$this->getSelected('gui_data/customer/filter/adressType', 'default_billing')?>><?=$this->__('Billing Address')?></option>
                            <option value="default_shipping" <?=$this->getSelected('gui_data/customer/filter/adressType', 'default_shipping')?>><?=$this->__('Shipping Address')?></option>
                    </select>
                </span>
                <span class="field-row">
                    <label for="customer_filter_telephone"><?=$this->__("Phone:")?></label>
                    <input class="input-text" id="customer_filter_telephone" name="gui_data[customer][filter][telephone]" value="<?=$this->getValue('gui_data/customer/filter/telephone')?>"/>
                    <?=$this->__('(Starting with)')?>
                </span>
                <span class="field-row">
                    <label for="customer_filter_postcode"><?=$this->__("Zip/Postal Code:")?></label>
                    <input class="input-text" id="customer_filter_postcode" name="gui_data[customer][filter][postcode]" value="<?=$this->getValue('gui_data/customer/filter/postcode')?>"/>
                </span>
                <span class="field-row">
                    <label for="customer_filter_country"><?=$this->__("Country:")?></label>
                    <select id="customer_filter_country" name="gui_data[customer][filter][country]">
                        <?foreach ($this->getCountryFilterOptions() as $_value):?>
                            <option value="<?=$_value['value']?>" <?=$this->getSelected('gui_data/customer/filter/country', $_value['value'])?>><?=htmlspecialchars($_value['label'])?></option>
                        <?endforeach?>
                    </select>
                </span>
                <span class="field-row">
                    <label for="customer_filter_region"><?=$this->__("State/Province:")?></label>
                    <input class="input-text" id="customer_filter_region" name="gui_data[customer][filter][region]" value="<?=$this->getValue('gui_data/customer/filter/region')?>"/>
                    <?=$this->__('(For US 2-letter state names)')?>
                </span>
                <span class="field-row">
                    <label for="customer_filter_created_at_from"><?=$this->__("Customer Since:")?></label>
                    <input class="input-text" style="width:5em" id="customer_filter_created_at_from" name="gui_data[customer][filter][created_at][from]" value="<?=$this->getValue('gui_data/customer/filter/created_at/from')?>"/>
                    <img src="<?=$this->getSkinUrl('images/grid-cal.gif')?>" alt="" align="absmiddle" id="customer_filter_created_at_from_trig" title="<?=$this->__('Date selector')?>" />
                     <?=$this->__('to')?>
                    <input class="input-text" style="width:5em" id="customer_filter_created_at_to" name="gui_data[customer][filter][created_at][to]" value="<?=$this->getValue('gui_data/customer/filter/created_at/to')?>"/>
                    <img src="<?=$this->getSkinUrl('images/grid-cal.gif')?>" alt="" align="absmiddle" id="customer_filter_created_at_to_trig" title="<?=$this->__('Date selector')?>" />
<script type="text/javascript">
    Calendar.setup({
        inputField : "customer_filter_created_at_from",
        ifFormat : "<?=$this->getShortDateFormat()?>",
        button : "customer_filter_created_at_from_trig",
        align : "Bl",
        singleClick : true
    });
    Calendar.setup({
        inputField : "customer_filter_created_at_to",
        ifFormat : "<?=$this->getShortDateFormat()?>",
        button : "customer_filter_created_at_to_trig",
        align : "Bl",
        singleClick : true
    });
</script>
                </span>
            </div>
        </fieldset>
    </div>

</div>

<script type="text/javascript">
    $$('.option-control').each(showOption);
    changeEntityType();
</script>