<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
            <td><h3><?=$this->getHeader()?></h3></td>
            <td class="a-right">
                <?if($this->getTagId()):?>
                    <?=$this->getDeleteButtonHtml()?>
                <?endif;?>
                <?=$this->getSaveButtonHtml()?>
            </td>
        </tr>
    </table>
</div>
<form action="<?=$this->getSaveUrl()?>" method="POST" id="tag_edit_form">
    <?=$this->getChildHtml('tagForm');?>
</form>
<script type="text/javascript" language="javascript">
    var tagForm = new varienForm('tag_edit_form');

    function tagDelete(){
        if(confirm('<?=Mage::helper('tag')->__('Are you sure that you want to delete this tag?')?>')){
            location.href = '<?=$this->getDeleteUrl()?>'
        }
    }
</script>
