<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?if($this->getType()!== 'main' && !$this->getScriptIncluded() && $this->getCanDisplayContainer()):?>
<script type="text/javascript" src="<?=$this->getSkinUrl('js/giftmessage.js')?>"></script>
<?$this->setScriptIncluded(true);?>
<?endif;?>
<?if($this->getCanDisplayContainer()):?>
<div id="<?=$this->getId()?>">
<?endif;?>
<?switch ($this->getType()):?>
<?case 'item':?>
    <a class="listen-for-click" href="#">
        <?if($this->hasGiftMessage()):?>
        <?=Mage::helper('giftmessage')->__('Edit')?>
        <?else:?>
        <?=Mage::helper('giftmessage')->__('Add')?>
        <?endif;?>
    </a>
    <?break;?>
<?case 'order_item':?>
    <a class="listen-for-click" href="#">
        <?if($this->hasGiftMessage()):?>
        <?=Mage::helper('giftmessage')->__('Edit')?>
        <?else:?>
        <?=Mage::helper('giftmessage')->__('Add')?>
        <?endif;?>
    </a>
    <?break;?>
<?case 'main':?>
        <?if($this->hasGiftMessage()):?>
            <?if($_giftMessage=$this->getMessage()):?>
            <span class="field-row">
                <label><?=Mage::helper('giftmessage')->__('From')?></label>
                <?=$this->htmlEscape($_giftMessage->getSender())?>
            </span>
            <span class="field-row">
                <label><?=Mage::helper('giftmessage')->__('To')?></label>
                <?=$this->htmlEscape($_giftMessage->getRecipient())?>
            </span>
            <span class="field-row">
                <label><?=Mage::helper('giftmessage')->__('Message')?></label>
                 <div class="left"><?=$this->prepareAsIs($_giftMessage->getMessage())?></div>
            </span>
            <?endif;?>
        <?=$this->getWidgetButtonHtml(Mage::helper('giftmessage')->__('Edit'), 'edit')?>
        <?else:?>
        <?=$this->getWidgetButtonHtml(Mage::helper('giftmessage')->__('Add'), 'add')?>
        <?endif;?>
    <?break;?>
<?case 'order':?>
        <?if($this->hasGiftMessage()):?>
            <?if($_giftMessage=$this->getMessage()):?>

            <span class="field-row">
                <label><?=Mage::helper('giftmessage')->__('From')?></label>
                <?=$this->htmlEscape($_giftMessage->getSender())?>
            </span>
            <span class="field-row">
                <label><?=Mage::helper('giftmessage')->__('To')?></label>
                <?=$this->htmlEscape($_giftMessage->getRecipient())?>
            </span>
            <span class="field-row">
                <label><?=Mage::helper('giftmessage')->__('Message')?></label>
                <div class="left"><?=$this->prepareAsIs($_giftMessage->getMessage())?></div>
            </span>

            <?endif;?>
        <?=$this->getWidgetButtonHtml(Mage::helper('giftmessage')->__('Edit'), 'edit')?>
        <?else:?>
        <?=$this->getWidgetButtonHtml(Mage::helper('giftmessage')->__('Add'), 'add')?>
        <?endif;?>
    <?break;?>
<?endswitch?>
<?if($this->getCanDisplayContainer()):?>
</div>
<script type="text/javascript">
var <?=$this->getJsObjectName()?> = new GiftMessage('<?=$this->getId()?>');
<?=$this->getJsObjectName()?>.url = '<?=$this->getEditUrl()?>';
</script>
<?endif;?>