<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?
/**
 * Cart cross sell items template
 * 
 * @see Mage_Checkout_Block_Cart_Crosssell
 */
?>
<?if($this->getItemCount()):?>
<div class="col-1 upsell">
    <h4><?=$this->__('Based on your selection, you may be interested in the following items:')?></h4>
    <ul class="generic-product-list">
    <?foreach ($this->getItems() as $_item):?>
        <li>
            <a href="<?=$_item->getProductUrl()?>"><img src="<?=$_item->getThumbnailUrl()?>" width="75" alt="<?=$this->htmlEscape($_item->getName())?>" class="product-image"/></a>
            <div class="product-shop">
                <h5><a href="<?=$_item->getProductUrl()?>"><?=$_item->getName()?></a></h5>
                <?=$this->helper('catalog/product')->getPriceHtml($_item)?>
                <button class="form-button" onclick="setLocation('<?=$this->getAddToCartUrl($_item)?>')" type="button"><span><?=$this->__('Add to Cart')?></span></button><br/>
                <small><a href="<?=$this->getAddToWishlistUrl($_item)?>" class="link-cart"><?=$this->__('Add to Wishlist')?></a></small>
            </div>
        </li>
    <?endforeach;?>
    </ul>
</div>
<?endif;?>
