<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="shipping-estimate box">
<h4><?=$this->__('Estimate Shipping and Tax')?></h4>
<form action="<?=$this->getUrl('checkout/cart/estimatePost')?>" method="post" id="shipping-zip-form">
    <p><label for="estimate_postcode"><?=$this->__('Enter your destination to get a shipping estimate.')?></label></p>
    <p><label for="country_id"><?=$this->__('Country')?></label><br/><?=$this->getHelper('directory/data')->getCountryHtmlSelect($this->getEstimateCountryId())?></p>
    <p><label for="postcode"><?=$this->__('Zip/Postal Code')?></label><br/><input class="input-text" id="postcode" name="estimate_postcode" value="<?=$this->getEstimatePostcode()?>"/></p>
    <p><button type="submit" class="form-button-alt"><span><?=$this->__('Get a Quote')?></span></button></p>
</form>
<?if (($_shippingRateGroups = $this->getEstimateRates())):?>
<form id="co-shipping-method-form" action="<?=$this->getUrl('checkout/cart/estimateUpdatePost')?>">
    <dl class="shipment-methods">
        <?foreach ($_shippingRateGroups as $code => $_rates):?>
            <dt><?=$this->getCarrierName($code)?></dt>
            <dd>
                <ul>
                <?foreach ($_rates as $_rate):?>
                    <li>
                       <?if ($_rate->getErrorMessage()):?>
                            <strong><?=$_rate->getErrorMessage()?></strong>
                       <?else:?>
                            <input name="estimate_method" type="radio" value="<?=$_rate->getCode()?>" id="s_method_<?=$_rate->getCode()?>"<?if($_rate->getCode()===$this->getAddressShippingMethod()) echo ' checked'?>/>
                            <label for="s_method_<?=$_rate->getCode()?>"><?=$_rate->getMethodDescription()?> - <strong><?=$_rate->getPrice()?></strong></label>
                       <?endif?>
                    </li>
                <?endforeach;?>
                </ul>
            </dd>
        <?endforeach;?>
    </dl>
    <button type="submit" class="form-button-alt" name="do" value="<?=$this->__('Update Total')?>"><span><?=$this->__('Update Total')?></span></button>
</form>
<script type="text/javascript">
    var coShippingMethodForm = new VarienForm('shipping-zip-form');
    Validation.addAllThese(
    [
           ['validate-zip-code', '<?=$this->__('Please enter a valid zip code. For example 90602 or 90602-1234.')?>', function(v) {
                if( $('shipping-zip-code').value.match(/(^[A-z0-9]{2,10}([\s]{0,2}|[\-]{0,2})[A-z0-9]{2,10}$)/ )) {
                    return true;
                } else {
                    return false;
                }
           }]
    ]
    );
</script>
<?endif;?>
</div>