<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?

$numColumns = sizeof($this->getColumns());
?>
<?if($this->getCollection()):?>

<div class="grid" style="padding:0px;">
<table cellspacing="0" style="border:0;" id="<?=$this->getId()?>_table">
    <?foreach ($this->getColumns() as $_column):?>
    <col <?=$_column->getHtmlProperty()?>>
    <?endforeach;?>
    <?if ($this->getHeadersVisibility() || $this->getFilterVisibility()):?>
        <thead>
            <?if ($this->getHeadersVisibility()):?>
                <tr class="headings">
                <?foreach ($this->getColumns() as $_column):?>
                    <th <?=$_column->getHeaderHtmlProperty()?>><span class="nobr"><?=$_column->getHeaderHtml()?></span></th>
                <?endforeach;?>
                </tr>
            <?endif;?>
        </thead>
    <?endif;?>
    <tbody>
    <?if (($this->getCollection()->getSize()>0) && (!$this->getIsCollapsed())):?>
    <?foreach ($this->getCollection() as $_index=>$_item):?>
        <tr id="<?=$this->getRowId($_item)?>">
        <?$i=0;foreach ($this->getColumns() as $_column):?>
            <td class="<?=$_column->getCssProperty()?> <?=++$i==$numColumns?'last':''?>"><?=(($_html = $_column->getRowField($_item)) != '' ? $_html : '&nbsp;')?></td>
        <?endforeach;?>
        </tr>
    <?endforeach;?>
    <?elseif ($this->getEmptyText()):?>
    	<tr>
    		<td class="empty-text <?=$this->getEmptyTextClass()?>" colspan="100"><?=$this->getEmptyText()?></td>
    	</tr>
    <?endif;?>
    </tbody>
</table>
</div>
<?if($this->canDisplayContainer()):?>
<script type="text/javascript" language="javascript">
    <?=$this->getJsObjectName()?> = new varienGrid('<?=$this->getId()?>', '<?=$this->getGridUrl()?>', '<?=$this->getVarNamePage()?>', '<?=$this->getVarNameSort()?>', '<?=$this->getVarNameDir()?>', '<?=$this->getVarNameFilter()?>');
    <?=$this->getJsObjectName()?>.useAjax = '<?=$this->getUseAjax()?>';
    <?if($this->getRowClickCallback()):?>
        <?=$this->getJsObjectName()?>.rowClickCallback = <?=$this->getRowClickCallback()?>;
    <?endif;?>
    <?if($this->getCheckboxCheckCallback()):?>
        <?=$this->getJsObjectName()?>.checkboxCheckCallback = <?=$this->getCheckboxCheckCallback()?>;
    <?endif;?>
    <?if($this->getRowInitCallback()):?>
        <?=$this->getJsObjectName()?>.initRowCallback = <?=$this->getRowInitCallback()?>;
        <?=$this->getJsObjectName()?>.rows.each(function(row){<?=$this->getRowInitCallback()?>(<?=$this->getJsObjectName()?>, row)});
    <?endif;?>
    <?if($this->getMassactionBlock()->isAvailable()):?>
    <?=$this->getMassactionBlock()->getJavaScript()?>
    <?endif?>
</script>
<?endif;?>
<?endif?>