<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
                    <div id="dashboardControl">
                    <h3><?=$this->__('Dashboard Control')?></h3>
                    <ul class="tabs">
                        <li><a href="#" onclick="dashboard.getApi().changeTab(0);return false;"><span><?=$this->__('Products')?></span></a></li>
                        <li><a href="#" onclick="dashboard.getApi().changeTab(1);return false;"><span><?=$this->__('Customers')?></span></a></li>
                        <li><a href="#" onclick="dashboard.getApi().changeInnerTab(2,0);return false;"><span><?=$this->__('Visitors')?></span></a></li>
                        <li><a href="#" onclick="dashboard.getApi().changeInnerTab(2,1);return false;"><span><?=$this->__("Who's Online")?></span></a></li>
                    </ul>
                    </div>
