<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
            <td><h3><?=$this->getHeaderText()?></h3></td>
            <td class="a-right">
                <?=$this->getBackButtonHtml()?>
                <?=$this->getResetButtonHtml()?>
                <span style="display:none;" id="formButtons">
                <?=$this->getSaveButtonHtml()?>
                </span>
            </td>
        </tr>
    </table>
</div>

<div style="display:none;" id="formContainer">
<?=$this->getFormHtml()?>
</div>
<script type="text/javascript" language="javascript">
    var editForm = new varienForm('edit_form');
</script>