<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<? $_order = $this->getShipment()->getOrder()?>
<?=$this->getChildHtml('order_info')?>

<div class="box-left">
    <!--Billing Address-->
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-payment-method"><?=$this->helper('sales')->__('Payment Information')?></h4>
        </div>
        <fieldset>
            <div><?=$this->getChildHtml('payment_info')?></div>
            <div><?=Mage::helper('sales')->__('Order was placed using %s', $_order->getOrderCurrencyCode())?></div>
        </fieldset>
    </div>
</div>
<div class="box-right">
    <!--Shipping Address-->
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-shipping-method"><?=$this->helper('sales')->__('Shipping and Tracking Information')?></h4>
        </div>
        <fieldset>
            <div>
                <?if($this->getShipment()->getTracksCollection()->count()):?>
                <a href="#" id="linkId" onclick="popWin('<?=$this->helper('shipping')->getTrackingPopUpUrlByShipId($this->getShipment()->getId())?>','trackshipment','width=800,height=600,resizable=yes,scrollbars=yes')" title="<?=$this->__('Track this shipment')?>"><?=$this->__('Track this shipment')?></a>
                <br/>
                <?endif;?>
                <strong><?=$_order->getShippingDescription()?></strong>
                (<?=$this->helper('sales')->__('Total Shipping Charges %s', $this->displayPriceAttribute('shipping_amount', false, ' '))?>)
            </div>
            <div><?=$this->getChildHtml('tracking')?></div>
        </fieldset>
    </div>
</div>
<div class="clear"></div>

    <div class="entry-edit">
        <div class="entry-edit-head">
        <h4 class="icon-head head-products"><?=$this->helper('sales')->__('Items Shipped')?></h4>
        </div>
</div>
<div>
    <div class="grid">
        <table cellspacing="0" class="data">
            <col/>
            <col width="100"/>
            <thead>
                <tr class="headings">
                    <th><?=$this->helper('sales')->__('Product')?></th>
                    <th class="last"><?=$this->helper('sales')->__('Qty Shipped')?></th>
                </tr>
            </thead>
            <tbody>
                <?$_items = $this->getShipment()->getAllItems()?>
                <?$i=0;foreach ($_items as $_item):$i++?>
                    <tr class="<?=($i%2==0)?'even':'odd'?>">
                        <td>
                            <?=$_item->getName()?>
                            <div class="nobr"><strong><?=$this->helper('sales')->__('SKU')?>:</strong> <?=$_item->getSku()?></div>
                            <?=$_item->getDescription()?>
                        </td>
                        <td class="last"><?=$_item->getQty()*1?></td>
                    </tr>
                <?endforeach;?>
            </tbody>
        </table>
    </div>
</div>

<table cellspacing="0" cellpadding="10" width="100%" class="order-info-foot">
    <tr>
        <td width="40%">&nbsp;</td>
        <td class="section"><?=$this->getChildHtml('comments')?></td>
    </tr>
</table>