<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<span class="field-row grid" id="shipment_tracking_info">
<table cellspacing="0" class="data">
    <col width="100"/>
    <col/>
    <col/>
    <col width="80"/>
    <thead>
        <tr class="headings">
            <th><?=Mage::helper('sales')->__('Carrier')?></th>
            <th><?=Mage::helper('sales')->__('Title')?></th>
            <th><?=Mage::helper('sales')->__('Number')?></th>
            <th class="last"><?=Mage::helper('sales')->__('Action')?></th>
        </tr>
    </thead>
<?if($_tracks = $this->getShipment()->getAllTracks()):?>
    <tbody>
    <?$i=0;foreach ($_tracks as $_track):$i++?>
        <tr class="<?=($i%2==0)?'even':'odd'?>">
            <td><?=$this->getCarrierTitle($_track->getCarrierCode())?></td>
            <td><?=$_track->getTitle()?></td>
            <td>
                <?if ($_track->isCustom()):?>
                <?=$_track->getNumber()?>
                <?else:?>
                <a href="#" onclick="submitAndReloadArea($('shipment_tracking_info_response_<?=$_track->getId()?>'), '<?=$this->getTrackInfoUrl($_track)?>');return false">
                    <?=$_track->getNumber()?>
                </a>
                <div id="shipment_tracking_info_response_<?=$_track->getId()?>"></div>
                <?endif;?>
            </td>
            <td class="last">
                <a href="#" onclick="deleteTrackingNumber('<?=$this->getRemoveUrl($_track)?>'); return false;">
                    <?=Mage::helper('sales')->__('Delete')?>
                </a>
            </td>
        </tr>
    <?endforeach;?>
    </tbody>
<?endif;?>
    <tfoot>
        <tr>
            <td>
                <select name="carrier" class="select" style="width:110px" onchange="selectCarrier(this)">
                    <option value=""></option>
                    <?foreach ($this->getCarriers() as $_code=>$_name):?>
                    <option value="<?=$_code?>"><?=$_name?></option>
                    <?endforeach;?>
                </select>
            </td>
            <td>
                <input class="input-text" type="text" id="tracking_title" name="title" value=""/>
            </td>
            <td>
                <input class="input-text" type="text" id="tracking_number" name="number" value=""/>
            </td>
            <td class="last"><?=$this->getSaveButtonHtml()?></td>
        </tr>
    </tfoot>
</table>
<script type="text/javascript">
function selectCarrier(elem) {
    option = elem.options[elem.selectedIndex];
    if (option.value && option.value != 'custom') {
        $('tracking_title').value = option.text;
    }
    else {
        $('tracking_title').value = '';
    }
}

function deleteTrackingNumber(url) {
    if (confirm('<?=Mage::helper('sales')->__('Are you sure?')?>')) {
        submitAndReloadArea($('shipment_tracking_info').parentNode, url)
    }
}
</script>
</span>