<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?
/**
 * Category layered navigation state
 * 
 * @see Mage_Catalog_Block_Layer_State
 */
?>
<?$_filters = $this->getActiveFilters()?>
<?if(!empty($_filters)):?>
    <h4><?=$this->__('Currently Shopping by')?></h4>
    <ol class="narrowed-category">
    <?foreach ($_filters as $_filter):?>
        <li>
            <a href="<?=$_filter->getRemoveUrl()?>" class="widget-btn"/><img src="<?=$this->getSkinUrl('images/list_remove_btn.gif')?>" alt="<?=$this->__('Remove This Item')?>"/></a>
            <span class="label"><?=$_filter->getName()?>: </span><?=$_filter->getLabel()?>
        </li>
    <?endforeach;?>
    </ol>
        <div class="actions"><a href="<?=$this->getClearUrl()?>"><?=$this->__('Clear All Items')?></a></div>
<?endif;?>
