<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?
/**
 * Category view template
 *
 * @see Mage_Catalog_Block_Category_View
 */
?>
<?=$this->getMessagesBlock()->getGroupedHtml()?>
<?if($this->isContentMode()):?>
    <h2 class="category-head"><?=$this->getCurrentCategory()->getName()?></h2>
    <?=$this->getCmsBlockHtml()?>
<?elseif($this->isMixedMode()):?>
    <h2 class="category-head"><?=$this->getCurrentCategory()->getName()?></h2>
    <?=$this->getCmsBlockHtml()?>
    <?=$this->getProductListHtml()?>

<?else:?>
    <h2 class="category-head"><?=$this->getCurrentCategory()->getName()?></h2>
    <?if($_imageUrl=$this->getCurrentCategory()->getImageUrl()):?>
        <p><img src="<?=$_imageUrl?>" alt="<?=$this->getCurrentCategory()->getName()?>" width="475"/></p>
    <?endif;?>
    <?if($_description=$this->getCurrentCategory()->getDescription()):?>
        <p class="category-description"><?=$_description?></p>
    <?endif;?>
    <?=$this->getProductListHtml()?>
<?endif;?>