<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?=$this->getMessagesBlock()->getGroupedHtml()?>
<?$product=$this->getProduct()?>
<div class="product-info-box">
    <div class="product-essential">
        <div class="product-img-box">
            <p class="main-product-img">
                <img src="<?=$product->getImageUrl()?>" alt="<?=$product->getName()?>" width="265">
            </p>
        </div>

        <div class="product-shop">
            <h3 class="product-name"><?=$product->getName()?></h3>
        <?=$this->getChildHtml('rating')?>
        <?if( $reviewCount ):?>
            <a href="#customer-reviews" class="no-wrap"><small><?=$this->__('%s Review(s)', $reviewCount)?></small></a>
        <?endif;?>

        <form action="<?=$this->getUrl('checkout/cart/add')?>" method="post" id="product_addtocart_form">
        <input type="hidden" name="product" value="<?=$product->getId()?>">

        <?if($product->isSuperConfig()):?>
        <?=$this->getChildHtml('super_config')?>
        <?endif;?>
        <?$_tierPrices = $this->getTierPrices($product)?>
        <?if(count($_tierPrices)>0):?>
            <div class="product-pricing">
                <ul class="bare">
                <?foreach($_tierPrices as $_price):?>
                    <li><?=$this->__('Buy %s for %s', $_price['price_qty'], $_price['formated_price'])?></li>
                <?endforeach?>
                </ul>
            </div>
        <?endif;?>

        <?if($product->isSuperGroup()):?>
            <?=$this->getChildHtml('super_group')?>
        <?endif;?>

        <?if(!$product->isSuperGroup()):?>
            <?if($product->isSaleable()):?>
            <p><small><?=$this->__('Availability: In stock.')?></small></p>
            <?else:?>
            <p><small><?=$this->__('Availability: Out of stock.')?></small><br />
            <?endif;?>

            <?if($product->isSaleable()):?>
            <?=$this->helper('catalog/product')->getPriceHtml($product)?>
            <fieldset class="add-to-cart-box">
                <legend><?=$this->__('Add Items to Cart')?></legend>
                <span class="qty-box"><label for="qty"><?=$this->__('Qty')?>:</label> <input name="qty" type="text" class="input-text qty" id="qty"/></span>
                <button class="form-button" onclick="productAddToCartForm.submit()"><span><?=$this->__('Add to Cart')?></span></button> <strong><?=$this->__('OR')?></strong>
            </fieldset>

            <div class="add-to-box">
                <?if ($this->helper('wishlist')->isAllow()) :?>
                <a href="<?=$wishlistLink?>"><?=$this->__('Add to Wishlist')?></a><br/>
                <?endif;?>

                <?if($_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($product)):?>
                <a href="<?=$_compareUrl?>"><?=$this->__('Add to Compare')?></a>
                <?endif;?>
            </div>

            <?else:?>
                <?if ($this->helper('wishlist')->isAllow()) :?>
                <p><a href="<?=$wishlistLink?>"><?=$this->__('Add to Wishlist')?></a><br/>
                <?endif;?>

                <?if($_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($product)):?>
                <a href="<?=$_compareUrl?>"><?=$this->__('Add to Compare')?></a>
                <?endif;?></p>

            <?endif;?>
        <?else:?>
            <button class="form-button" onclick="productAddToCartForm.submit()"><span><?=$this->__('Add to Cart')?></span></button> <strong><?=$this->__('OR')?></strong>

        <?if ($this->helper('wishlist')->isAllow()) :?>
            &nbsp;&nbsp;<a href="<?=$wishlistLink?>"><?=$this->__('Add to Wishlist')?></a>
        <?endif;?>

        <?if($_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($product)):?>
            <span class="pipe">|</span><a href="<?=$_compareUrl?>"><?=$this->__('Add to Compare')?></a>
        <?endif;?>

        <?endif;?>
        </form>
        <script type="text/javascript">
            var productAddToCartForm = new VarienForm('product_addtocart_form');
            productAddToCartForm.submit = function() {
                if(this.validator.validate()) {
                    this.form.submit();
                }
            }.bind(productAddToCartForm);
        </script>
        <div class="clear"></div>
        <div class="divider"></div>

        <p><a href="<?=$product->getProductUrl()?>">&laquo; <?=$this->__('Back to Main Product Info')?></a></p>

        </div>
        </div>

        <div class="product-collateral">
    <?if( $this->getCollection() && $this->count()):?>
        <div class="collateral-box dedicated-review-box" id="customer-reviews">
            <div class="head">
                <h4><?=$this->__('Customer Reviews')?></h4>
            </div>
        <?=$this->getToolbarHtml()?>
            <ol style="margin-top:15px;">
        <?foreach( $this->getCollection()->getItems() as $_review ):?>
                <li>
                    <a href="<?=$this->getReviewUrl($_review->getId())?>"><strong><?=$_review->getTitle()?></strong></a> <?=$this->__('Review by %s', $_review->getNickname())?>
                    <table class="ratings-list" cellspacing="0">
                        <tbody>
                        <?foreach( $_review->getRatingVotes() as $_vote ):?>
                        <tr>
                            <td class="label"><strong><?=$_vote->getRatingCode()?></strong></td>
                            <td>
                                <div class="rating-box">
                                    <div class="rating" style="width: <?=$_vote->getPercent()?>%;"></div>
                                </div>
                            </td>
                        </tr>
                        <?endforeach;?>
                        </tbody>
                    </table>
                    <p><?=nl2br($_review->getDetail())?> <?=$this->__('(Posted on %s)', $this->formatDate($_review->getCreatedAt()), 'long')?></p></li>
                <li>
        <?endforeach;?>
            </ol>
        </div>
        <?=$this->getToolbarHtml()?>
    <?else:?>
    <?endif;?>
    <br/>
    <?=$this->getChildHtml('reviewForm')?>
    </div>
</div>
