<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?
/**
 * One page checkout payment methods
 *
 * @see Mage_Checkout_Block_Onepage_Payment_Methods
 */
?>
<dl class="payment-methods">
<?foreach ($this->getMethods() as $_method): $_code = $_method->getCode()?>
    <dt>
        <input id="p_method_<?=$_code?>" value="<?=$_code?>" type="radio" name="payment[method]" title="<?=$this->htmlEscape($_method->getTitle())?>" onclick="payment.switchMethod('<?=$_code?>')"<?if($this->getSelectedMethodCode()==$_code):?> checked<?endif;?>/>
        <label for="p_method_<?=$_code?>"><?=$_method->getTitle()?></label>
    </dt>
    <dd>
        <?=$this->getChildHtml('payment.method.'.$_code)?>
    </dd>
<?endforeach;?>
</dl>