<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<dt>
    <input type="radio" title="<?=$this->getTitle()?>" id="payment_method_<?=$this->getMethod()?>" name="payment[method]" value="<?=$this->getMethod()?>" <?if($this->isCurrent()):?>checked<?endif?> onclick="payment.switchMethod('<?=$this->getMethod()?>')"  class1="validate-one-required"/>&nbsp;<label for="payment_method_<?=$this->getMethod()?>"><?=$this->getTitle()?></label>
</dt>
<dd>
    <fieldset class="form-list">
        <ul id="payment_form_<?=$this->getMethod()?>" style="display:none">
            <li><div class="input-box"><label for="<?=$this->getMethod()?>_cc_owner"><?=$this->__('Name on Card')?> <span class="required">*</span></label><br/>
                <input type="text" title="<?=$this->__('Name on Card')?>" class="required-entry input-text" id="<?=$this->getMethod()?>_cc_owner" name="payment[cc_owner]" value="<?=$this->getPayment()->getCcOwner()?>"/></div></li>
            <li><div class="input-box"><label for="<?=$this->getMethod()?>_cc_type"><?=$this->__('Credit Card Type')?> <span class="required">*</span></label><br/>
                <select id="<?=$this->getMethod()?>_cc_type" name="payment[cc_type]" class="required-entry validate-cc-type-select">
                <?foreach ($this->getCcTypes() as $k=>$v):?>
                    <option value="<?=$k?>" <?if($k==$this->getPayment()->getCcType()):?>selected<?endif?>><?=$v?></option>
                <?endforeach?>
                </select></div></li>
            <li><div class="input-box"><label for="<?=$this->getMethod()?>_cc_number"><?=$this->__('Credit Card Number')?> <span class="required">*</span></label><br/>
                <input type="text" id="<?=$this->getMethod()?>_cc_number" name="payment[cc_number]" title="<?=$this->__('Credit Card Number')?>" class="input-text validate-cc-number validate-cc-type" value=""/></div></li>
            <li><div class="input-box"><label for="<?=$this->getMethod()?>_expiration"><?=$this->__('Expiration Date')?> <span class="required">*</span></label><br/>

                <select id="<?=$this->getMethod()?>_expiration" style="width:140px;" name="payment[cc_exp_month]" class="required-entry">
                <?foreach ($this->getMonths() as $k=>$v):?>
                    <option value="<?=$k?>" <?if($k==$this->getPayment()->getCcExpMonth()):?>selected<?endif?>><?=$v?></option>
                <?endforeach?>
                </select>  <select id="<?=$this->getMethod()?>_expiration_yr" style="width:103px;" name="payment[cc_exp_year]" class="required-entry">
                <?foreach ($this->getYears() as $k=>$v):?>
                    <option value="<?=$k?>" <?if($k==$this->getPayment()->getCcExpYear()):?>selected<?endif?>><?=$v?></option>
                <?endforeach?>
                </select></div></li>
            <?if($this->hasVerification()):?>
            <li><div class="input-box"><label for="<?=$this->getMethod()?>_cc_cid"><?=$this->__('Card Verification Number')?> <span class="required">*</span></label><br/>
                <input type="text" title="<?=$this->__('Card Verification Number')?>" class="required-entry input-text" id="<?=$this->getMethod()?>_cc_cid" name="payment[cc_cid]" style="width:3em;" value=""/> &nbsp; <a href="#" class="cvv-what-is-this"><?=$this->__('What is this?')?></a></div></li>
            <?endif?>
        </ul>
    </fieldset>
</dd>
