<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?=$this->getMessagesBlock()->getGroupedHtml()?>
<?if($this->getWishlist()->getSize()):?>
<form action="<?=$this->getUrl('*/*/update')?>" method="post">
    <table cellspacing="0" width="100%" class="data-table box-table" id="wishlist-table">
    <col width="130"/>
    <col/>
    <col width="130"/>
    <thead>
        <tr>
            <th class="align-left"><?=$this->__('Product')?></th>
            <th class="align-center"><?=$this->__('Comment')?></th>
            <th class="align-center">&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        <?foreach($this->getWishlist() as $item):?>
        <tr>
            <td>
                <div>
                    <a href="<?=$item->getProductUrl()?>">
                        <img src="<?=$item->getSmallImageUrl()?>" alt="<?=htmlspecialchars($item->getName())?>" width="113"/>
                    </a>
                </div>
                <div><a href="<?=$item->getProductUrl()?>" title="<?=$item->getName()?>"><?=$item->getName()?></a></div>
            </td>            
            <td class="align-center"><?=$this->getEscapedDescription($item)?></td>
            <td class="align-center">
                <a href="#" onclick="setLocation('<?=$this->helper('checkout/cart')->getAddUrl($item)?>');return false;" class="link-cart"><?=$this->__('Add to Cart')?></a><br/>
                <a href="#" onclick="setLocation('<?=$this->helper('wishlist')->getAddUrl($item)?>');return false;" class="link-cart"><?=$this->__('Add to Wishlist')?></a>
            </td>
        </tr>
        <?endforeach?>
    <tbody>
    </table>
    <script type="text/javascript">decorateTable('wishlist-table')</script>
    <div class="form-buttons">
        <button onclick="setLocation('<?=$this->getUrl('*/*/allcart', array('_current'=>true))?>')" class="form-button-alt"  type="button"><span><?=$this->__('Add All to Cart')?></span></button>&nbsp;
    </div>
</form>
<?else:?>
    <p><?=$this->__('You have placed no product yet.')?></p>
<?endif?>