<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="page-head">
    <h3><?=$this->__('Share Your Wishlist')?></h3>
</div><?=$this->getMessagesBlock()->getGroupedHtml()?>
<form action="<?=$this->getSendUrl()?>" id="form-validate" method="post">
        <ul class="form-list">
            <li>
                <label for="email_address"><?=$this->__('Email addresses, separated by commas')?> <span class="required">*</span></label><br/>
                <textarea name="email" cols="60" rows="5" class="validate-emails required-entry"><?=$this->getEnteredData('email')?></textarea>
            </li>
            <li>
                <label for="email_address"><?=$this->__('Message')?></label><br/>
                <textarea name="message" cols="60" rows="5"><?=$this->getEnteredData('message')?></textarea>
            </li>
        </ul>
    <div class="form-buttons">
            <p class="required"><?=$this->__('* Required Fields')?></p>
            <button type="submit" class="form-button"><span><?=$this->__('Share Wishlist')?></span></button>
    </div>
</form>
<script type="text/javascript">
<!--
Validation.addAllThese([
    ['validate-emails', '<?=$this->__('Please enter a valid email addresses, separated by commas. For example johndoe@domain.com, johnsmith@domain.com.')?>', function (v) {
                if(Validation.get('IsEmpty').test(v)) {
                    return true;
                }

                var valid_regexp = /^[a-z0-9\._-]{1,30}@([a-z0-9_-]{1,30}\.){1,5}[a-z]{2,4}$/;
                var emails = v.split(',');

                for (var i=0; i<emails.length; i++) {
                    if(!valid_regexp.test(emails[i].strip())) {
                        return false;
                    }
                }

                return true;
            }]
]);
var dataForm = new VarienForm('form-validate', true);
//-->
</script>
