<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="page-head">
    <h3><?=$this->__('My Wishlist')?></h3>
</div>

<?=$this->getMessagesBlock()->getGroupedHtml()?>
<?if($this->getWishlist()->getSize()):?>
<form action="<?=$this->getUrl('*/*/update')?>" method="post">
    <table cellspacing="0" width="100%" class="data-table box-table" id="wishlist-table">
    <col width="130"/>
    <col width="300"/>
    <col/>
    <col/>
        <thead>
            <tr>
                <th><?=$this->__('Product')?></th>
                <th><?=$this->__('Comment')?></th>
                <th><?=$this->__('Added On')?></th>
                <th class="a-center">&nbsp;</th>
            </tr>
        </thead>
        <tbody>
        <?foreach($this->getWishlist() as $item):?>
            <tr>
                <td>
                    <div><a href="<?=$item->getProductUrl()?>"><img src="<?=$item->getSmallImageUrl()?>" alt="<?=$this->htmlEscape($item->getName())?>" width="113"/></a></div>
                    <div><a href="<?=$item->getProductUrl()?>" title="<?=$this->htmlEscape($item->getName())?>"><?=$item->getName()?></a></div>
                    <?=$this->helper('catalog/product')->getPriceHtml($item)?>
                </td>
                <td align="center">
                    <textarea name="description[<?=$item->getWishlistItemId()?>]" style="width:95%;height:160px;" onfocus="focusComment(this)" onblur="focusComment(this)"><?=( $this->getEscapedDescription($item) ) ? $this->getEscapedDescription($item) : $this->__('Please, enter your comments...') ?></textarea>
                </td>
                <td>
                    <?=$this->getFormatedDate($item->getAddedAt())?>
                </td>
                <td class="a-center">
                <?if($item->isSaleable()):?>
                    <a href="#" onclick="setLocation('<?=$this->getItemAddToCartUrl($item)?>');return false;" class="link-cart"><?=$this->__('Add to Cart')?></a><br/>
                <?endif;?>
                    <a href="#" onclick="confirmRemoveWishlistItem('<?=$this->getItemRemoveUrl($item)?>');return false;" class="link-remove" /><?=$this->__('Remove Item')?></a>
                </td>
            </tr>
        <?endforeach?>
        </tbody>
    </table>
<script type="text/javascript">decorateTable('wishlist-table')</script>
    <div class="button-set">
        <button onclick="setLocation('<?=$this->getUrl('*/*/share')?>')" class="form-button-alt" type="button"><span><?=$this->__('Share Wishlist')?></span></button>&nbsp;
        <button onclick="setLocation('<?=$this->getUrl('*/*/allcart')?>')" class="form-button-alt"  type="button"><span><?=$this->__('Add All to Cart')?></span></button>&nbsp;
        <button type="submit" class="form-button" name="do"><span><?=$this->__('Update Wishlist')?></span></button>
    </div>
</form>
<?else:?>
    <p><?=$this->__('You have no items in your wishlist.')?></p>
<?endif?>
<script type="text/javascript">
function confirmRemoveWishlistItem(url){
    if(confirm('<?=$this->__('Are you sure you want to remove this product from your wishlist?')?>')) {
        setLocation(url);
    }
}

function focusComment(obj) {
    if( obj.value == '<?=$this->__('Please, enter your comments...')?>' ) {
        obj.value = '';
    } else if( obj.value == '' ) {
        obj.value = '<?=$this->__('Please, enter your comments...')?>';
    }
}
</script>