<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?=$this->getAddButtonHtml()?> <?=$this->getAfterElementHtml()?>
<div>&nbsp;</div>
<span id="<?=$this->getElement()->getHtmlId()?>_container"></span>
<span id="<?=$this->getElement()->getHtmlId()?>_delete_button" style="display:none"></span>
<div id="<?=$this->getElement()->getHtmlId()?>_add_template" style="display:none">
<div class="tier-price-input" id="<?=$this->getElement()->getHtmlId()?>_row___index__">
    <div class="tier-container">
        <div class="custgroup-div">
            <strong><?=('Customer Group')?></strong>&nbsp;
            <span>
              <select id="'<?=$this->getElement()->getHtmlId()?>_row___index___cust_group'" disabled="no-template" class="<?=$this->getElement()->getClass()?> custgroup required-entry" name="'<?=$this->getElement()->getName()?>[__index__][cust_group]'">
              <?foreach ($this->getCustomerGroups() as $_groupId=>$_groupName):?>
                  <option value="<?=$_groupId?>"><?=htmlspecialchars($_groupName)?></option>
              <?endforeach?>
              </select>
            </span>
        </div>
        <div class="qty-div">
            <strong><?=('Qty')?></strong>&nbsp;
            <span>
              <input id="'<?=$this->getElement()->getHtmlId()?>_row___index___price_qty'" disabled="no-template" class="<?=$this->getElement()->getClass()?> qty required-entry validate-number validate-greater-than-zero" type="text" name="'<?=$this->getElement()->getName()?>[__index__][price_qty]'" value="'#{qty}'"><strong><?=Mage::helper('catalog')->__(' and above.')?></strong>
            </span>
        </div>
        <div class="price-div">
            <strong><?=('Price')?></strong>&nbsp;
            <span>
              <input id="'<?=$this->getElement()->getHtmlId()?>_row___index___price'" disabled="no-template" class="<?=$this->getElement()->getClass()?> price required-entry validate-number validate-greater-than-zero" type="text" name="'<?=$this->getElement()->getName()?>[__index__][price]'" value="'#{price}'">
            </span>
            <input id="'<?=$this->getElement()->getHtmlId()?>_row___index__delete'" type="hidden" name="'<?=$this->getElement()->getName()?>[__index__][delete]'" value="">
            <?=$this->getDeleteButtonHtml()?>
        </div>
    </div>
</div>
</div>
<br /><br />
<script type="text/javascript">
<!--
    var tierPriceControl = {
        template : new Template($('<?=$this->getElement()->getHtmlId()?>_add_template').innerHTML.replace(/__index__/g, '#{index}').replace(/ disabled="?no-template"?/g, '').replace(/ disabled/g, '').replace(/="'([^']*)'"/g, '="$1"')),
        itemsCount : 0,
        deleteButton: false,
        addItem  : function () {
            var data = {};
            data.group = '<?=$this->getDefaultCustomerGroup()?>';
            data.qty = '';
            data.price = '';
            data.index = this.itemsCount++;
            if(arguments.length == 3) {
                data.group = arguments[0];
                data.qty   = arguments[1];
                data.price = arguments[2];
            }
            new Insertion.Bottom($('<?=$this->getElement()->getHtmlId()?>_container'), this.template.evaluate(data));
            $('tier_price_row_'+data.index+'_cust_group').value = data.group;
        },
        deleteItem : function(item) {
            $('<?=$this->getElement()->getHtmlId()?>_row_' + item).hide();
            $('<?=$this->getElement()->getHtmlId()?>_row_' + item).addClassName('no-display template');
            if($('<?=$this->getElement()->getHtmlId()?>_row_'+item+'delete')){
                $('<?=$this->getElement()->getHtmlId()?>_row_'+item+'delete').value=1;
            }
        }
    }
    <?foreach ($this->getValues() as $_item):?>
    tierPriceControl.addItem('<?=$_item['cust_group']?>', '<?=$_item['price_qty']?>','<?=$_item['price']?>');
    <?endforeach;?>
//-->
</script>