<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?$_source  = $this->getSource()?>
<?$this->setPriceDataObject($_source)?>
<?$_currency= $this->getCurrency()?>
<?if ($_source):?>
<table cellspacing="0" width="100%">
    <tfoot>
        <tr>
            <td class="label">
                <strong><big>
                <?if ($this->getGrandTotalTitle()):?>
                    <?=$this->getGrandTotalTitle()?>
                <?else:?>
                    <?=Mage::helper('sales')->__('Grand Total')?>
                <?endif;?>
                </big></strong>
            </td>
            <td class="emph"><big><?=$this->displayPriceAttribute('grand_total', true)?></big></td>
        </tr>
        <?if ($this->getCanDisplayTotalPaid()):?>
        <tr>
            <td class="label"><strong><?=Mage::helper('sales')->__('Total Paid')?></strong></td>
            <td class="emph"><?=$this->displayPriceAttribute('total_paid', true)?>
            </td>
        </tr>
        <?endif;?>
        <?if ($this->getCanDisplayTotalRefunded()):?>
        <tr>
            <td class="label"><strong><?=Mage::helper('sales')->__('Total Refunded')?></strong></td>
            <td class="emph"><?=$this->displayPriceAttribute('total_refunded', true)?></td>
        </tr>
        <?endif;?>
        <?if ($this->getCanDisplayTotalDue()):?>
        <tr>
            <td class="label"><big><strong><?=Mage::helper('sales')->__('Total Due', true)?></strong></big></td>
            <td class="emph"><big><?=$this->displayPriceAttribute('total_due', true)?></big></td>
        </tr>
        <?endif;?>
    </tfoot>
    <tbody>
        <?if ((float) $_source->getSubtotal()):?>
        <tr>
            <td class="label"><?=Mage::helper('sales')->__('Subtotal')?></td>
            <td><?=$this->displayPriceAttribute('subtotal')?></td>
        </tr>
        <?endif;?>
        <?if ((float) $_source->getTaxAmount()):?>
        <tr>
            <td class="label"><?=Mage::helper('sales')->__('Tax')?></td>
            <td><?=$this->displayPriceAttribute('tax_amount')?></td>
        </tr>
        <?endif;?>

        <?if ((float) $_source->getShippingAmount() || $_source->getShippingDescription()):?>
        <tr>
            <td class="label"><?=Mage::helper('sales')->__('Shipping &amp; Handling')?></td>
            <td><?=$this->displayPriceAttribute('shipping_amount')?></td>
        </tr>
        <?endif;?>
        <?if ((float) $_source->getDiscountAmount()):?>
        <tr>
            <td class="label">
                <?if ($_source->getCouponCode()):?>
                    <?=Mage::helper('sales')->__('Discount (%s)', $_source->getCouponCode())?>
                <?else:?>
                    <?=Mage::helper('sales')->__('Discount')?>
                <?endif;?>
            </td>
            <td><?=$this->displayPriceAttribute('discount_amount')?></td>
        </tr>
        <?endif;?>

        <?if ((float) $_source->getGiftcertAmount()):?>
        <tr>
            <td class="label"><?=Mage::helper('sales')->__('Gift Certificate')?></td>
            <td><?=$this->displayPriceAttribute('giftcert_amount')?></td>
        </tr>
        <?endif;?>

        <?if ((float) $_source->getAdjustmentPositive()):?>
        <tr>
            <td class="label"><?=Mage::helper('sales')->__('Adjustment Refund')?></td>
            <td><?=$this->displayPriceAttribute('adjustment_positive')?></td>
        </tr>
        <?endif;?>

        <?if ((float) $_source->getAdjustmentNegative()):?>
        <tr>
            <td class="label"><?=Mage::helper('sales')->__('Adjustment Fee')?></td>
            <td><?=$this->displayPriceAttribute('adjustment_negative')?></td>
        </tr>
        <?endif;?>
    </tbody>
</table>
<?endif;?>