<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<script type="text/javascript">
function install(type)
{
    $('run_iframe').style.display = 'block';
    $(type+'_form').submit();
}
</script>
<div class="content-header">
	<table cellspacing="0" class="grid-header">
		<tr>
			<td><h3><?=$this->getTitle()?></h3></td><td class="form-buttons"><?=$this->getBackButtonHtml()?></td>
		 </tr>
	</table>
</div>
<div class="entry-edit">
    <form action="<?=$this->getUploadInstallUrl()?>" method="post" id="local_form" enctype="multipart/form-data" target="run_iframe">
        <h4 class="icon-head head-edit-form fieldset-legend"><?=$this->__("Upload Local File")?></h4>
        <fieldset>
            <legend><?=$this->__("Upload Local File")?></legend>

            <table class="" cellspacing="5">
                <tbody>
                    <tr><th><?=$this->__("Upload local file:")?></th><td><input type="file" name="local"/></td></tr>
                </tbody>
            </table>

            <?=$this->getUploadButtonHtml()?><br/>
        </fieldset>
    </form>

    <form action="<?=$this->getRemoteInstallUrl()?>" method="post" id="remote_form" enctype="multipart/form-data" target="run_iframe">
        <h4 class="icon-head head-edit-form fieldset-legend"><?=$this->__("Download Remote File")?></h4>
        <fieldset>
            <legend><?=$this->__("Download Remote File")?></legend>

            <table class="" cellspacing="5">
                <tbody>
                    <tr><th><?=$this->__("Remote URL:")?></th><td><input name="remote" class="input-text"/></td></tr>
                </tbody>
            </table>

            <?=$this->getRemoteButtonHtml()?><br/>
        </fieldset>
    </form>

    <iframe id="run_iframe" name="run_iframe" src="<?=$this->getUrl('*/*/install')?>" frameborder=0 style="display:none; width:100%; height:400px;"></iframe>
</div>