<? $_order = $this->getOrder() ?>

<div class="page-head button-level">
    <h3><?=$this->__('Order #%s - %s', $_order->getRealOrderId(), $_order->getStatusLabel())?></h3>
  <?if ($this->helper('sales/reorder')->canReorder($_order)) :?>
                        	<a href="<?=$this->getReorderUrl($_order)?>" style="font-weight: bold; color: #FF6600;"><?=$this->__('Reorder')?></a>
                        <?endif?>
</div>


<div class="order-access">
<div class="order-info">
<?=$this->__('About Ihis Order:')?>
<ul>
  <?$_links = $this->getLinks();?>
                <?foreach ($_links as $_link):?>
                        <?if($_link->getUrl()):?>
                        <li><a href="<?=$_link->getUrl()?>"><?=$_link->getLabel()?></a></li>
                        <?else:?>
                        <li class="selected"><?=$_link->getLabel()?></li>
                        <?endif;?>
                <?endforeach;?>
</ul>
</div>
</div>


<p><?=$this->__('Order Date: %s', $this->formatDate($_order->getCreatedAt(), 'long'))?></p>
<div class="col2-set generic-box">
    <div class="col-1">
        <h4><?=$this->__('Shipping Address')?></h4>
        <address><?=$_order->getShippingAddress()->format('html')?></address>
    </div>
    <div class="col-2">
        <h4><?=$this->__('Shipping Method')?><?/* | <a href="#"><?=$this->__('Track Order')?></a>*/?></h4>
        <?=$_order->getShippingDescription()?>
    </div>
</div>
<div class="col2-set generic-box">
    <div class="col-1">
        <h4><?=$this->__('Billing Address')?></h4>
        <address><?=$_order->getBillingAddress()->format('html')?></address>
    </div>
    <div class="col-2">
        <h4><?=$this->__('Payment Method')?></h4>
        <?=$this->getPaymentInfoHtml()?>
    </div>
</div>