<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="divider"></div>
<div class="head">
    <h3>Invoice #0001</h3>
    <a href="#">Print Invoice</a>
</div>
<div class="col2-set">
    <div class="col-1">
        <h4>Shipping Address</h4>
        <address>John Doe<br/>
        Varien<br/>
        3402 Motor Ave.<br/>
        Suite B<br/>
        Los Angeles, CA 90034</br>
        <strong>T</strong> | (310)123-1234</address>
    </div>
    <div class="col-2">
        <h4>Billing Address</h4>
        <address>John Doe<br/>
        Varien<br/>
        3402 Motor Ave.<br/>
        Suite B<br/>
        Los Angeles, CA 90034</br>
        <strong>T</strong> | (310)123-1234</address>
    </div>
</div>
<br/>
<div class="col2-set">
    <div class="col-1">
        <h4>Shipping Method</h4>
        USPS Express Mail
    </div>
    <div class="col-2">
        <h4>Billing Method</h4>
        Credit Card: Visa xxxx1234
    </div>
</div>
<br/>
<h4>Items Ordered</h4>
<table cellspacing="0" class="data-table">
    <thead>
        <tr>
            <th>Product Name</th>
            <th class="a-right">Price</th>
            <th class="a-center">Qty</th>
            <th class="a-center">Qty Shipped</th>
            <th class="a-right">Subtotal</th>
        </tr>
    </thead>
    <tbody>
        <tr class="last">
            <td>Product Name goes here</td>
            <td class="a-right">$29.99</td>
            <td class="a-center">1</td>
            <td class="a-center">1</td>
            <td class="last a-right">$29.99</td>
        </tr>
    </tbody>
    <tfoot>
        <tr>
            <td colspan="4" class="a-right">Order Subtotal</td>
            <td class="last a-right">$41.97</td>
        </tr>
    </tfoot>
</table>
<br/>
