<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?if($this->helper('giftmessage/message')->getIsMessagesAvailable('order', $this->getOrder())):?>
<script type="text/javascript">
function giftMessageToogle(giftMessageIdentifier)
{
    var link = $('order-item-gift-message-link-'+giftMessageIdentifier);
    var container = $('order-item-gift-message-'+giftMessageIdentifier);
    var row = $('order-item-row-'+giftMessageIdentifier);


    if(link.expanded) {
        link.expanded = false;
        link.removeClassName('collapse');
        link.addClassName('expand');
        if(container.hasClassName('last')) {
            row.addClassName('last');
        }
        container.hide();
    } else {
        link.expanded = true;
        link.addClassName('collapse');
        link.removeClassName('expand');
        if(container.hasClassName('last')) {
            row.removeClassName('last');
        }
        container.show();
    }

    return false;
}
</script>
<?endif;?>
<? $_order = $this->getOrder() ?>

<?foreach ($_order->getInvoiceCollection() as $_invoice):?>
<br />
<div class="head">
    <h3>Invoice #<?=$_invoice->getIncrementId();?></h3>
    <!--<a href="#">Print Invoice</a>-->
</div>

<h4><?=$this->__('Items Invoiced')?></h4>
<table cellspacing="0" class="data-table" id="my-orders-table-<?=$_invoice->getId();?>">
    <thead>
        <tr>
            <th><?=$this->__('Product Name')?></th>
            <th width="15%"><?=$this->__('Price')?></th>
            <th class="a-center" width="10%"><?=$this->__('Qty Invoiced')?></th>
            <th class="a-right" width="20%"><?=$this->__('Subtotal')?></th>
        </tr>
    </thead>
    <tbody>
        <?$_items = $_invoice->getAllItems();?>
        <?$_count = count($_items)?>
        <?$_index = 0;?>
        <?foreach ($_items as $_item):?>
            <tr <?=($_index++ > $_count ? ' class="last"' : '')?> id="order-item-row-<?=$_item->getId()?>">
                <td><?=$_item->getName()?></td>
                <td class="a-right nowrap"><?=$_order->formatPrice($_item->getPrice())?> </td>
                <td class="a-center"><?=$_item->getQty()*1?> </td>
                <td class="last a-right nowrap"><?=$_order->formatPrice($_item->getRowTotal())?> </td>
            </tr>
        <?endforeach;?>
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" class="a-right"><?=$this->__('Order Subtotal')?></td>
            <td class="last a-right"><?=$_order->formatPrice($_invoice->getSubtotal())?></td>
        </tr>
        <?if ($_invoice->getDiscountAmount() > 0):?>
            <tr>
                <td colspan="3" class="a-right"><?=$this->__('Discount :')?></td>
                <td class="last a-right"><?=$_order->formatPrice(0.00 - $_invoice->getDiscountAmount())?></td>
            </tr>
        <?endif;?>
        <?if ($_invoice->getTaxAmount() > 0):?>
            <tr>
                <td colspan="3" class="a-right"><?=$this->__('Tax')?></td>
                <td class="last a-right"><?=$_order->formatPrice($_invoice->getTaxAmount())?></td>
            </tr>
        <?endif;?>
        <?if ($_invoice->getShippingAmount() || $_invoice->getShippingDescription()):?>
            <tr>
                <td colspan="3" class="a-right"><?=$this->__('Shipping & Handling')?></td>
                <td class="last a-right"><?=$_order->formatPrice($_invoice->getShippingAmount())?></td>
            </tr>
        <?endif;?>
        <tr>
            <td colspan="3" class="a-right"><?=$this->__('Grand Total')?></td>
            <td class="last a-right"><?=$_order->formatPrice($_invoice->getGrandTotal())?></td>
        </tr>
    </tfoot>
</table>
<script type="text/javascript">decorateTable('my-orders-table-<?=$_invoice->getId();?>')</script>
<?endforeach;?>
<div class="button-set">
    <a href="<?=$this->getBackUrl()?>" class="left">&laquo; <?=$this->__('Back to My Orders')?></a>
</div>