<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?if($this->helper('giftmessage/message')->getIsMessagesAvailable('order', $this->getOrder())):?>
<script type="text/javascript">
function giftMessageToogle(giftMessageIdentifier)
{
    var link = $('order-item-gift-message-link-'+giftMessageIdentifier);
    var container = $('order-item-gift-message-'+giftMessageIdentifier);
    var row = $('order-item-row-'+giftMessageIdentifier);


    if(link.expanded) {
        link.expanded = false;
        link.removeClassName('collapse');
        link.addClassName('expand');
        if(container.hasClassName('last')) {
            row.addClassName('last');
        }
        container.hide();
    } else {
        link.expanded = true;
        link.addClassName('collapse');
        link.removeClassName('expand');
        if(container.hasClassName('last')) {
            row.removeClassName('last');
        }
        container.show();
    }

    return false;
}
</script>
<?endif;?>
<? $_order = $this->getOrder() ?>
<a href="<?=$this->getPrintAllShipmentsUrl($_order)?>" target="_blank"><?=$this->__('Print All Shipments')?></a>
<? if ($_order->getTracksCollection()->count()) : ?>
<div style="float:right">
<a href="#" id="linkId" onclick="popWin('<?=$this->helper('shipping')->getTrackingPopUpUrlByOrderId($_order->getId())?>','trackorder','width=800,height=600,resizable=yes,scrollbars=yes')" title="<?=$this->__('Track all shipment(s)')?>"><?=$this->__('Track all shipments')?></a>
</div>
<?endif;?>
<?foreach ($_order->getShipmentsCollection() as $_shipment):?>
<br />
<div class="head">
    <h3><?=$this->__('Shipment #')?><?=$_shipment->getIncrementId();?></h3>
    <a href="<?=$this->getPrintShipmentUrl($_shipment)?>" target="_blank"><?=$this->__('Print Shipment')?></a>
</div>
<table class="data">
<?$tracks = $_shipment->getTracksCollection();?>
<? if ($tracks->count()):?>
    <tr>
        <td colspan="2">
            <a href="#" id="linkId" onclick="popWin('<?=$this->helper('shipping')->getTrackingPopUpUrlByShipId($_shipment->getId())?>','trackshipment','width=800,height=600,resizable=yes,scrollbars=yes')" title="<?=$this->__('Track this shipment')?>"><?=$this->__('Track this shipment')?></a>
        </td>
    </tr>
    <tr>
        <td class="label"><?=$this->__('Tracking Number(s)')?>:</td>
        <td>&nbsp;
    <?
    $i = 1;
    $_size = $tracks->count();
    foreach($tracks as $track):?>
    <?if($track->isCustom()):?>
        <?=$track->getNumber()?>
    <?else:?>
    <a href="#" onclick="popWin('<?=$this->helper('shipping')->getTrackingPopUpUrlByTrackID($track->getEntityId())?>','trackorder','width=800,height=600,resizable=yes,scrollbars=yes')" ><?=$track->getNumber()?></a>
    <?endif;?>
    <?if($i!=$_size):?>, <?endif;?>
    <?$i++;
    endforeach;?>
    </td>
<? endif;?>
</table>
<h4><?=$this->__('Items Shipped')?></h4>
<table cellspacing="0" class="data-table" id="my-orders-table-<?=$_shipment->getId();?>">
    <thead>
        <tr>
            <th><?=$this->__('Product Name')?></th>
            <th width="15%"><?=$this->__('SKU')?></th>
            <th class="a-center" width="15%"><?=$this->__('Qty Shipped')?></th>
        </tr>
    </thead>
    <tbody>
        <?$_items = $_shipment->getAllItems();?>
        <?$_count = count($_items)?>
        <?$_index = 0;?>
        <?foreach ($_items as $_item):?>
        <tr <?=($_index++ > $_count ? ' class="last"' : '')?> id="order-item-row-<?=$_item->getId()?>">
            <td>
                <?=$_item->getName()?>
                <?=$_item->getDescription()?>
            </td>
            <td><?=$_item->getSku()?></td>
            <td class="a-center"><?=$_item->getQty()*1?></td>
        </tr>
        <?endforeach;?>
    </tbody>
</table>
<script type="text/javascript">decorateTable('my-orders-table-<?=$_shipment->getId();?>')</script>
<?endforeach;?>
<div class="button-set">
    <a href="<?=$this->getBackUrl()?>" class="left">&laquo; <?=$this->__('Back to My Orders')?></a>
</div>
