<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?if($this->helper('giftmessage/message')->getIsMessagesAvailable('order', $this->getOrder())):?>
<script type="text/javascript">
function giftMessageToogle(giftMessageIdentifier)
{
    var link = $('order-item-gift-message-link-'+giftMessageIdentifier);
    var container = $('order-item-gift-message-'+giftMessageIdentifier);
    var row = $('order-item-row-'+giftMessageIdentifier);


    if(link.expanded) {
        link.expanded = false;
        link.removeClassName('collapse');
        link.addClassName('expand');
        if(container.hasClassName('last')) {
            row.addClassName('last');
        }
        container.hide();
    } else {
        link.expanded = true;
        link.addClassName('collapse');
        link.removeClassName('expand');
        if(container.hasClassName('last')) {
            row.removeClassName('last');
        }
        container.show();
    }

    return false;
}
</script>
<?endif;?>
<? $_order = $this->getOrder() ?>

<h4><?=$this->__('Items Ordered')?>

<? if ($_order->getTracksCollection()->count()) : ?>
<span class="separator">|</span>
<a href="#" id="linkId" onclick="popWin('<?=$this->helper('shipping')->getTrackingPopUpUrlByOrderId($_order->getId())?>','trackorder','width=800,height=600,resizable=yes,scrollbars=yes')" title="<?=$this->__('Track your order')?>"><?=$this->__('Track your order')?></a>
</h4>
<?else:?>
</h4>
<?endif;?>
<table cellspacing="0" class="data-table" id="my-orders-table">
    <thead>
        <tr>
            <th><?=$this->__('Product Name')?></th>
            <th width="15%"><?=$this->__('Price')?></th>
            <th class="a-center" width="6%"><?=$this->__('Qty Ordered')?></th>
            <th class="a-center" width="6%"><?=$this->__('Qty Shipped')?></th>
            <th class="a-center" width="6%"><?=$this->__('Qty Canceled')?></th>
            <th class="a-right" width="18%"><?=$this->__('Subtotal')?></th>
        </tr>
    </thead>
    <tbody>
        <?$_items = $_order->getItemsCollection();?>
        <?$_count = $_items->count();?>
        <?$_index = 0;?>
        <?foreach ($_items as $_item):?>
            <tr <?=($_index++ > $_count ? ' class="last"' : '')?> id="order-item-row-<?=$_item->getId()?>">
            <td><?=$_item->getName()?>
            <?if($this->helper('giftmessage/message')->getIsMessagesAvailable('order_item', $_item) && $_item->getGiftMessageId()):?>
            <br /><a href="#" id="order-item-gift-message-link-<?=$_item->getId()?>" class="giftmessage-preview-link expand" onclick="return giftMessageToogle('<?=$_item->getId()?>')"><?=$this->__('Gift Message')?></a>
            <?endif;?>
            </td>
                <td class="nowrap a-right"><?=$_order->formatPrice($_item->getPrice())?> </td>
                <td class="a-center"><?=$_item->getQtyOrdered()*1?> </td>
                <td class="a-center"><?=$_item->getQtyShipped()*1?> </td>
                <td class="a-center"><?=$_item->getQtyCanceled()*1?> </td>
                <td class="last a-right nowrap"><?=$_order->formatPrice($_item->getRowTotal())?> </td>
            </tr>
            <?if($this->helper('giftmessage/message')->getIsMessagesAvailable('order_item', $_item) && $_item->getGiftMessageId()):?>
            <tr <?=($_index++ > $_count ? ' class="last"' : '')?> id="order-item-gift-message-<?=$_item->getId()?>" style="display:none;">
                <?$_giftMessage=$this->helper('giftmessage/message')->getGiftMessageForEntity($_item);?>
                <td class="giftmessage-row last" colspan="5">
                <div class="left">
                     <ul>
                        <li>
                            <label><?=$this->__('From')?></label> <?=$this->htmlEscape($_giftMessage->getRecipient())?>
                        </li>
                        <li>
                            <label><?=$this->__('To')?></label> <?=$this->htmlEscape($_giftMessage->getSender())?>
                        </li>
                        <li><?=$this->helper('giftmessage/message')->getEscapedGiftMessage($_item)?></li>
                     </ul>

                </div>
                <div class="right"><a href="#" onclick="return giftMessageToogle('<?=$_item->getId()?>')"><img src="<?=$this->getSkinUrl('images/gift-message-close.gif')?>"></a></div>
                </td>
            </tr>
            <?endif?>
        <?endforeach;?>

    </tbody>
    <tfoot>
        <tr>
            <td colspan="5" class="a-right"><?=$this->__('Order Subtotal')?></td>
            <td class="last a-right"><?=$_order->formatPrice($_order->getSubtotal())?></td>
        </tr>
        <?if ($_order->getDiscountAmount() > 0):?>
            <tr>
                <td colspan="5" class="a-right"><?=$this->__('Discount '.($_order->getCouponCode()?'('.$_order->getCouponCode().')':''))?></td>
                <td class="last a-right"><?=$_order->formatPrice(0.00 - $_order->getDiscountAmount())?></td>
            </tr>
        <?endif;?>
        <?if ($_order->getTaxAmount() > 0):?>
            <tr>
                <td colspan="5" class="a-right"><?=$this->__('Tax')?></td>
                <td class="last a-right"><?=$_order->formatPrice($_order->getTaxAmount())?></td>
            </tr>
        <?endif;?>
        <?if ($_order->getShippingAmount() || $_order->getShippingDescription()):?>
            <tr>
                <td colspan="5" class="a-right"><?=$this->__('Shipping & Handling')?></td>
                <td class="last a-right"><?=$_order->formatPrice($_order->getShippingAmount())?></td>
            </tr>
        <?endif;?>
        <tr>
            <td colspan="5" class="a-right"><?=$this->__('Grand Total')?></td>
            <td class="last a-right"><?=$_order->formatPrice($_order->getGrandTotal())?></td>
        </tr>
    </tfoot>
</table>
<script type="text/javascript">decorateTable('my-orders-table')</script>
<?if($this->helper('giftmessage/message')->getIsMessagesAvailable('order', $_order) && $_order->getGiftMessageId()):?>
<div class="giftmessage">
    <?$_giftMessage=$this->helper('giftmessage/message')->getGiftMessageForEntity($_order);?>
    <strong><?=$this->__('Gift Message for this Order')?></strong>
     <ul>
        <li>
            <label><?=$this->__('From')?></label> <?=$this->htmlEscape($_giftMessage->getRecipient())?>
        </li>
        <li>
            <label><?=$this->__('To')?></label> <?=$this->htmlEscape($_giftMessage->getSender())?>
        </li>
        <li><?=$this->helper('giftmessage/message')->getEscapedGiftMessage($_order)?></li>
     </ul>
</div>
<?endif;?>
<?$_history = $this->getOrder()->getVisibleStatusHistory()?>
<?if (count($_history)):?>
    <div class="clear">&nbsp;</div>
    <h4><?=$this->__('About Your Order')?></h4>
    <div>
        <dl>
            <?foreach ($_history as $_historyItem):?>
                <dt><?=$this->formatDate($_historyItem->getCreatedAt(), 'medium', true)?></dt>
                <dd><?=$_historyItem->getComment()?></dd>
            <?endforeach;?>
        </dl>
    </div>
<?endif;?>

<div class="button-set">
    <a href="<?=$this->getBackUrl()?>" class="left">&laquo; <?=$this->__('Back to My Orders')?></a>
</div>