<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?=Mage::helper('catalog')->__('Super product attributes configuration')?></h4>
    </div>
    <fieldset id="<?=$this->getHtmlId()?>">
        <legend><?=Mage::helper('catalog')->__('Super product attributes configuration')?></legend>
        <input type="hidden" id="<?=$this->getHtmlId()?>_save_links" name="configurable_products_data" value=""/>
        <input type="hidden" id="<?=$this->getHtmlId()?>_save_attributes" name="configurable_attributes_data" />
        <ul id="<?=$this->getHtmlId()?>_attributes" class="super-attributes">
        </ul>
    </fieldset>
</div>
<div class="no-display" id="<?=$this->getHtmlId()?>_attribute_template">
    <div class="attribute-name-container">
        '{{frontend_label}}'
    </div>
    <div class="values-container">
        <label for="__id___label" class="bold"><?=Mage::helper('catalog')->__('Attribute Name:')?></label>
        <input id="__id___label" type="text" class="input-text attribute-label required-entry template no-display" value="'{{label}}'"/>
        <ul class="attribute-values">
        </ul>
    </div>
</div>
<div class="no-display" id="<?=$this->getHtmlId()?>_value_template">
    <div class="attribute-value-label-container">
    <?=Mage::helper('catalog')->__('Option:')?> <strong>'{{label}}'</strong>
</div>
<div class="attribute-values-container-main">
    <div class="attribute-values-container">
    <?=Mage::helper('catalog')->__('Price:')?>
    <input id="__id___pricing" type="text" class="input-text attribute-price validate-number template no-display" value="'{{pricing_value}}'"/>
</div>
<div class="attribute-values-container">
    <select class="attribute-price-type">
        <option value="0"><?=Mage::helper('catalog')->__('Fixed')?></option>
        <option value="1"><?=Mage::helper('catalog')->__('Percentage')?></option>
    </select>
</div>
</div>
</div>
<?=$this->getGridHtml()?>
<script type="text/javascript">
var superProduct = new Product.Configurable(<?=$this->getAttributesJson()?>,<?=$this->getLinksJson()?>,'<?=$this->getHtmlId()?>_',<?=$this->getGridJsObject()?>);
superProduct.createEmptyUrl = '<?=$this->getNewEmptyProductUrl()?>';
superProduct.createNormalUrl = '<?=$this->getNewProductUrl()?>';
</script>
