<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div id="<?=$this->getHtmlId()?>">
<table cellspacing="0" cellpadding="0" class="massaction">
<tr>
    <td>
        <a href="#" onclick="return <?=$this->getJsObjectName()?>.selectAll()"><?=$this->__('Select All')?></a>
        <div class="delimiter">&nbsp;</div>
        <a href="#" onclick="return <?=$this->getJsObjectName()?>.unselectAll()"><?=$this->__('Unselect All')?></a>
        <div class="delimiter">&nbsp;</div>
        <a href="#" onclick="return <?=$this->getJsObjectName()?>.selectVisible()"><?=$this->__('Select Visible')?></a>
        <div class="delimiter">&nbsp;</div>
        <a href="#" onclick="return <?=$this->getJsObjectName()?>.unselectVisible()"><?=$this->__('Unselect Visible')?></a>
        <div class="delimiter">&nbsp;</div>
        <span id="<?=$this->getHtmlId()?>-count">0</span> <?=$this->__('items selected')?>
    </td>
    <td>
        <div class="right">
            <div class="entry-edit">
                <form id="<?=$this->getHtmlId()?>-form" method="POST">
                    <fieldset>
                        <span class="field-row">
                            <label><?=$this->__('Actions')?></label>
                            <select id="<?=$this->getHtmlId()?>-select" class="required-entry select absolute-advice">
                                <option value=""></option>
                                <?foreach($this->getItems() as $_item):?>
                                    <option value="<?=$_item->getId()?>"><?=$_item->getLabel()?></option>
                                <?endforeach;?>
                            </select>
                        </span>
                        <span class="outer-span" id="<?=$this->getHtmlId()?>-form-hiddens"></span>
                        <span class="outer-span" id="<?=$this->getHtmlId()?>-form-additional"></span>
                        <span class="field-row">
                            <?=$this->getApplyButtonHtml()?>
                        </span>
                    </fieldset>
                </form>
            </div>

            <div class="no-display">
            <?foreach($this->getItems() as $_item):?>
                <div id="<?=$this->getHtmlId()?>-item-<?=$_item->getId()?>-block">
                    <?=$_item->getAdditionalActionBlockHtml()?>
                </div>
            <?endforeach;?>
            </div>
        </div>
    </td>
</tr>
</table>
<?if(!$this->getParentBlock()->canDisplayContainer()):?>
<script type="text/javascript">
    <?=$this->getJsObjectName()?>.setGridIds(<?=$this->getGridIdsJson()?>);
</script>
<?endif;?>
</div>