<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * Install configuration template
 *
 * @see Mage_Install_Block_Config
 */
?>
<div class="page-head">
    <h3><?=$this->__('Configuration')?></h3>
</div>
<?=$this->getMessagesBlock()->getGroupedHtml()?>

<?if($this->getInstaller()->getServerCheckStatus()):?>
<form action="<?=$this->getPostUrl()?>" method="post" id="form-validate">
<fieldset class="group-select">
 <legend><?=$this->__('Connection')?></legend>
    <h4 class="legend"><?=$this->__('Database Connection')?></h4>
    <ul>
        <li>
            <div class="input-box">
                <label for="host"><?=$this->__('Host')?> <span class="required">*</span></label><br/>
                <input type="text" name="config[db_host]" id="host" value="<?=$this->getFormData()->getDbHost()?>" title="<?=$this->__('Database host')?>" class="required-entry input-text"/>
                <p style="margin-top:4px; line-height:1.3em; color:#666;">
                    <small><?=$this->__('You can specify server port, ex.: localhost:3307<br/>If you are not using default UNIX socket, you can specify it here instead of host, ex.: /var/run/mysqld/mysqld.sock')?></small>
                </p>
            </div>
            <div class="input-box">
                <label for="dbname"><?=$this->__('Database Name')?> <span class="required">*</span></label><br/>
                <input type="text" name="config[db_name]" id="dbname" value="<?=$this->getFormData()->getDbName()?>" title="<?=$this->__('Database Name')?>" class="required-entry input-text"/>
            </div>
        </li>
        <li>
            <div class="input-box">
                <label for="user"><?=$this->__('User Name')?> <span class="required">*</span></label><br/>
                <input type="text" name="config[db_user]" id="user" value="<?=$this->getFormData()->getDbUser()?>" title="<?=$this->__('Database user name')?>" class="required-entry input-text"/>
            </div>
            <div class="input-box">
                <label for="password"><?=$this->__('User Password')?></label><br/>
                <input type="password" name="config[db_pass]" id="password" value="" title="<?=$this->__('Database user password')?>" class="input-text"/>
            </div>
        </li>
    </ul>
</fieldset>

<fieldset class="group-select">
    <legend><?=$this->__('Web access options')?></legend>
    <h4 class="legend"><?=$this->__('Web access options')?></h4>
    <ul>
        <li>
            <input type="checkbox" name="config[use_rewrites]" id="use_rewrites" value="1" <?if($this->getFormData()->getUseRewrites()):?>checked<?endif?>>
            <label for="use_rewrites"><?=$this->__('Use Web Server (Apache) Rewrites')?></label><br/>
            <p style="margin-top:4px; line-height:1.3em; color:#666;">
                <small>
                    <?=$this->__('You could enable this option to use web server rewrites functionality for improved search engines optimization.')?><br>
                    <strong><?=$this->__('Please make sure that <code>mod_rewrite</code> is enabled in Apache configuration.')?></strong>
                </small>
            </p>
        </li>
        <li>
            <input type="checkbox" name="config[use_secure]" id="use_secure" value="1" <?if($this->getFormData()->getUseSecure()):?>checked<?endif?> onclick="this.checked ? $('use_secure_options').show() : $('use_secure_options').hide(); return true">
            <label for="use_secure"><?=$this->__('Use Secure URLs (SSL)')?></label><br/>
            <p style="margin-top:4px; line-height:1.3em; color:#666;">
                <small><?=$this->__('Enable this option only if you have SSL available.')?></small>
            </p>
        </li>
    </ul>
    <ul id="use_secure_options" <?if(!$this->getFormData()->getUseSecure()):?>style="display:none"<?endif?>>
        <li>
            <label for="secure_base_url"><?=$this->__('Secure Base URL')?> <span class="required">*</span></label><br/>
            <input type="text" name="config[secure_base_url]" id="secure_base_url" value="<?=$this->getFormData()->getSecureBaseUrl()?>" title="<?=$this->__('Secure Base URL')?>" class="required-entry input-text"/>
            <p style="margin-top:4px; line-height:1.3em; color:#666;">
                <small><?=$this->__('Provide a complete base URL for SSL connection. For example: %s', '<strong>https://www.mydomain.com/magento/</strong>')?></small>
            </p>
        </li>
        <li>
            <input type="checkbox" name="config[use_secure_admin]" id="use_secure_admin" value="1" <?if($this->getUseSecureAdmin()):?>checked<?endif?>>
            <label for="use_secure_admin"><?=$this->__('Run admin interface with SSL')?></label><br/>
            <p style="margin-top:4px; line-height:1.3em; color:#666;">
                <small><?=$this->__('')?></small>
            </p>
        </li>
        <li>
            <input type="checkbox" name="skip_url_validation" id="skip_url_validation" value="1" <?if($this->getSkipSecureValidation()):?>checked<?endif?>>
            <label for="skip_url_validation"><?=$this->__('Skip Secure URL validation before next step')?></label><br/>
            <p style="margin-top:4px; line-height:1.3em; color:#666;">
                <small><?=$this->__('Check this box only if it is not possible to automatically validate Secure URL, for example if HTTP authentication is required.')?></small>
            </p>
        </li>
    </ul>
</fieldset>

<div class="button-set">
    <p class="required">* <?=$this->__('Required Fields')?></p>
    <button class="form-button" type="submit"><span><?=$this->__('Continue')?></span></button>
</div>
</form>
<script type="text/javascript">
    var dataForm = new VarienForm('form-validate');
</script>
<?else:?>
    <div><?=$this->__('Please set all required settings before clicking Continue')?></div>
    <div class="button-set">
        <button class="form-button" type="button" onclick="setLocation('<?=$this->getUrl('*/*/*')?>')"><span><?=$this->__('Continue')?></span></button>
    </div>
<?endif;?>