<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * Install configuration template
 *
 * @see Mage_Install_Block_Config
 */
?>
<div class="page-head">
    <h3><?=$this->__('Configuration')?></h3>
</div>
<?=$this->getMessagesBlock()->getGroupedHtml()?>

<?if($this->getInstaller()->getServerCheckStatus()):?>
<form action="<?=$this->getPostUrl()?>" method="post" id="form-validate">
<fieldset class="group-select">
 <legend><?=$this->__('Connection')?></legend>
    <h4 class="legend"><?=$this->__('Database Connection')?></h4>
    <ul>
        <li>
            <div class="input-box">
                <label for="host"><?=$this->__('Host')?> <span class="required">*</span></label><br/>
                <input type="text" name="config[db_host]" id="host" value="<?=$this->getFormData()->getDbHost()?>" title="<?=$this->__('Database host')?>" class="required-entry input-text"/>
                <p style="margin-top:4px; line-height:1.3em; color:#666;">
                    <small><?=$this->__('You can specify server port, ex.: localhost:3307<br/>If you are not using default UNIX socket, you can specify it here instead of host, ex.: /var/run/mysqld/mysqld.sock')?></small>
                </p>
            </div>
            <div class="input-box">
                <label for="dbname"><?=$this->__('Database Name')?> <span class="required">*</span></label><br/>
                <input type="text" name="config[db_name]" id="dbname" value="<?=$this->getFormData()->getDbName()?>" title="<?=$this->__('Database Name')?>" class="required-entry input-text"/>
            </div>
        </li>
        <li>
            <div class="input-box">
                <label for="user"><?=$this->__('User Name')?> <span class="required">*</span></label><br/>
                <input type="text" name="config[db_user]" id="user" value="<?=$this->getFormData()->getDbUser()?>" title="<?=$this->__('Database user name')?>" class="required-entry input-text"/>
            </div>
            <div class="input-box">
                <label for="password"><?=$this->__('User Password')?></label><br/>
                <input type="password" name="config[db_pass]" id="password" value="" title="<?=$this->__('Database user password')?>" class="input-text"/>
            </div>
        </li>
    </ul>
</fieldset>
<fieldset class="group-select">
 <legend><?=$this->__('Default store')?></legend>
    <h4 class="legend"><?=$this->__('Default store')?></h4>
    <ul>
        <li>
            <div class="input-box">
                <label for="default_host"><?=$this->__('Host')?> <span class="required">*</span></label><br/>
                <input type="text" name="config[host]" id="default_host" value="<?=$this->getFormData()->getHost()?>" title="<?=$this->__('Host name')?>" class="required-entry input-text"/>
            </div>
            <div class="input-box">
                <label for="basepath"><?=$this->__('Base Path')?> <span class="required">*</span></label><br/>
                <input type="text" name="config[base_path]" id="basepath" value="<?=$this->getFormData()->getBasePath()?>" title="<?=$this->__('WWW base path')?>" class="required-entry input-text"/>
            </div>
        </li>
        <li>
            <div class="input-box">
                <label for="protocol"><?=$this->__('Protocol')?> <span class="required">*</span></label><br/>
                <select name="config[protocol]" id="protocol" title="<?=$this->__('Protocol')?>" class="required-entry">
                    <option value="http" selected>http</option>
                </select>
            </div>
            <div class="input-box">
                <label for="port"><?=$this->__('Port')?> <span class="required">*</span></label><br/>
                <input type="text" name="config[port]" id="port" value="<?=$this->getFormData()->getPort()?>" title="<?=$this->__('Port')?>" class="required-entry input-text"/>
                <p style="margin-top:4px; line-height:1.3em; color:#666;">
                    <small><?=$this->__('For HTTPS connections, the default port is 443.')?><br/>
                    <?=$this->__('For HTTP connections, the default port is 80.')?></small>
                </p>
            </div>
        </li>
    </ul>
</fieldset>
<fieldset class="group-select">
 <legend><?=$this->__('Secure Connection')?></legend>
    <h4 class="legend"><?=$this->__('Secure Connection')?></h4>
    <ul>
        <li>
            <div class="input-box">
                <label for="secure_host"><?=$this->__('Secure Host')?> <span class="required">*</span></label><br/>
                <input type="text" name="config[secure_host]" id="secure_host" value="<?=$this->getFormData()->getSecureHost()?>" title="<?=$this->__('Secure host name')?>" class="required-entry input-text"/>
            </div>
            <div class="input-box">
                <label for="secure_basepath"><?=$this->__('Secure Base Path')?> <span class="required">*</span></label><br/>
                <input type="text" name="config[secure_base_path]" id="secure_basepath" value="<?=$this->getFormData()->getSecureBasePath()?>" title="<?=$this->__('Secure www base path')?>" class="required-entry input-text"/>
            </div>
        </li>
        <li>
            <div class="input-box">
                <label for="secure_protocol"><?=$this->__('Secure Protocol')?> <span class="required">*</span></label><br/>
                <select name="config[secure_protocol]" id="secure_protocol" title="<?=$this->__('Secure Protocol')?>" class="required-entry">
                    <option value="http"<?if($this->getFormData()->getSecureProtocol()=='http'):?> selected<?endif;?>>http</option>
                    <option value="https"<?if(!$this->getFormData()->getSecureProtocol() || $this->getFormData()->getSecureProtocol()=='https'):?> selected<?endif;?>>https</option>
                </select>
            </div>
            <div class="input-box">
                <label for="secure_port"><?=$this->__('Secure Port')?> <span class="required">*</span></label><br/>
                <input type="text" name="config[secure_port]" id="secure_port" value="<?=$this->getFormData()->getSecurePort()?>" title="<?=$this->__('Secure Port')?>" class="required-entry input-text"/>
                <p style="margin-top:4px; line-height:1.3em; color:#666;">
                    <small><?=$this->__('For HTTPS connections, the default port is 443.')?><br/>
                    <?=$this->__('For HTTP connections, the default port is 80.')?></small>
                </p>
            </div>
        </li>
    </ul>
</fieldset>
<fieldset class="group-select">
    <legend><?=$this->__('Configuration options')?></legend>
    <h4 class="legend"><?=$this->__('Configuration options')?></h4>
    <ul>
        <li>
            <input type="checkbox" name="config[use_script_name]" id="use_script_name" value="1" <?if($this->getFormData()->getUseScriptName()):?>checked<?endif?>>
            <label for="use_script_name"><?=$this->__('Do not use Apache Rewrites')?></label><br/>
            <p style="margin-top:4px; line-height:1.3em; color:#666;">
                <small><?=$this->__('If you do not have apache mod_rewrite module available you could use this option to allow Magento functionality by inserting /index.php/ in every URL. Please note, that if you disable this option without having mod_rewrite enabled, the next page might not load.')?></small>
            </p>
        </li>
        <li>
            <input type="checkbox" name="skip_url_validation" id="skip_url_validation" value="1" <?if($this->getSkipUrlValidation()):?>checked<?endif?>>
            <label for="skip_url_validation"><?=$this->__('Skip URL validation')?></label><br/>
            <p style="margin-top:4px; line-height:1.3em; color:#666;">
                <small><?=$this->__('Check this box only if you are unable to automatically validate Magento URL, for example if HTTP authentication is required.')?></small>
            </p>
        </li>
    </ul>
</fieldset>
<div class="form-buttons">
    <p class="required">* <?=$this->__('Required Fields')?></p>
    <button class="form-button" type="submit"><span><?=$this->__('Continue')?></span></button>
</div>
</form>
<script type="text/javascript">
    var dataForm = new VarienForm('form-validate');
</script>
<?else:?>
    <div><?=$this->__('Please set all required settings before clicking Continue')?></div>
    <div class="form-buttons">
        <button class="form-button" type="button" onclick="setLocation('<?=$this->getUrl('*/*/*')?>')"><span><?=$this->__('Continue')?></span></button>
    </div>
<?endif;?>