<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * Installation end page
 *
 * @see Mage_Install_Block_End
 */
?>
<div class="page-head">
    <h3><?=$this->__("You're All Set")?>!</h3>
</div>
<p><?=$this->__('Get ready to experience Open-Source eCommerce Evolved.')?></p>
<?if($this->getEncryptionKey()):?>
<p><?=$this->__('Before you continue to your store, please make a note of your encryption key (Magento uses it to encrypt passwords, credit cards and more).')?></p>
<p><strong><big><?=$this->getEncryptionKey()?></big></strong></p>
<p><?=$this->__('(Make sure you keep it in a safe place.)')?></p>
<?endif;?>
<div class="button-set">
    <button class="form-button" onclick="setLocation('<?=Mage::getBaseUrl()?>')" type="button"><?=$this->__('Go to Frontend')?></button>&nbsp;&nbsp;
    <button class="form-button" onclick="setLocation('<?=$this->getUrl('adminhtml')?>')" type="button"><?=$this->__('Go to Backend')?></button>
</div>