<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * Install localization template
 *
 * @see Mage_Install_Block_Locale
 */
?>
<div class="page-head">
    <h3><?=$this->__('Localization')?></h3>
</div>
<?=$this->getMessagesBlock()->getGroupedHtml()?>

<form action="<?=$this->getPostUrl()?>" method="post" id="form-validate">
<fieldset class="group-select">
 <legend><?=$this->__('Locale')?></legend>
    <h4 class="legend"><?=$this->__('Locale settings')?></h4>
    <ul>
        <li>
            <div class="input-box">
                <label for="locale"><?=$this->__('Locale')?> <span class="required">*</span></label><br/>
                <?=$this->getLocaleSelect()?>
            </div>
        </li>
        <li>
            <div class="input-box">
                <label for="timezone"><?=$this->__('Time Zone')?> <span class="required">*</span></label><br/>
                <?=$this->getTimezoneSelect()?>
            </div>
            <div class="input-box">
                <label for="currency"><?=$this->__('Default Currency')?> <span class="required">*</span></label><br/>
                <?=$this->getCurrencySelect()?>
            </div>
        </li>
    </ul>
</fieldset>
<div class="form-buttons">
    <p class="required">* <?=$this->__('Required Fields')?></p>
    <button class="form-button" type="submit"><span><?=$this->__('Continue')?></span></button>
</div>
</form>
<script type="text/javascript">
    function changeLocale(event){
        var elem = Event.element(event);
        if(elem){
            setLocation('<?=$this->getChangeUrl()?>locale/'+elem.value);
        }
    }
    var dataForm = new VarienForm('form-validate');
    if($('locale')){
        Event.observe($('locale'), 'change', changeLocale);
    }
</script>