<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
            <td><h3><?=$this->helper('core')->__('Delete Store "%s"', $this->getModel()->getName());?></h3></td>
            <td class="a-right">
                <?=$this->getChildHtml('back_button')?>
            </td>
        </tr>
    </table>
</div>
<form action="<?=$this->getData('action')?>" method="post" id="delete_form">
    <p>
        Are you sure, lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.
    </p>
    <p>
        <input type="checkbox" name="create_backup" checked="checked" id="input_create_backup" />&nbsp;<label for="input_create_backup"><?=$this->helper('adminhtml')->__('Create DB Backup');?></label>
    </p>
    <p>
        <?=$this->getChildHtml('confirm_deletion_button')?> <?=$this->getChildHtml('cancel_button')?>
    </p>
</form>
<script type="text/javascript" language="javascript">
    var deleteForm = new varienForm('delete_form');
</script>
