<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="entry-edit">
    <?foreach ($this->getReleases() as $_log):?>
    <h4 class="icon-head head-edit-form fieldset-legend"><?=$_log['version']['release']?> (<?=$_log['stability']['release']?>)</h4>
    <fieldset>
        <legend><?=$_log['version']['release']?> (<?=$_log['stability']['release']?>)</legend>

        <table class="" cellspacing="5">
            <tbody>
                <tr><th><?=$this->__("Date:")?></th><td><?=$_log['date']?></td></tr>
                <tr><th><?=$this->__("Version:")?></th><td><?=$_log['version']['release']?> (<?=$_log['stability']['release']?>)</td></tr>
                <tr><th><?=$this->__("API:")?></th><td><?=$_log['version']['api']?> (<?=$_log['stability']['api']?>)</td></tr>
                <tr><th><?=$this->__("License:")?></th><td>
                    <?if (is_array($_log['license'])):?>
                        <?if ($_uri = $_log['license']['attribs']['uri']):?>
                            <a href="<?=$_uri?>" target="_blank">
                        <?endif?>
                        <?=$_log['license']['_content']?>
                        <?if ($_uri):?>
                            </a>
                        <?endif?>
                    <?else:?>
                        <?=$_log['license']?>
                    <?endif?>
                </td></tr>
                <tr><th><?=$this->__("Notes:")?></th><td><?=nl2br($_log['notes'])?></td></tr>
            </tbody>
        </table>
    </fieldset>
    <?endforeach?>
</div>