<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="entry-edit">
    <h4 class="icon-head head-edit-form fieldset-legend"><?=$this->__("Provided Files")?></h4>
    <fieldset>
        <legend><?=$this->__("Provided Files")?></legend>
        <table class="" cellspacing="5">
            <thead><th><?=$this->__("Role")?></th><th><?=$this->__("Name")?></th><th><?=$this->__("Installed As")?></th><th><?=$this->__("md5sum")?></th></thead>
            <tbody>
            <?foreach ($this->getPkg()->getFilelist() as $_file):?>
                <tr><td><?=$_file['role']?></td><td><?=$_file['name']?></td><td><?=$_file['installed_as']?></td><td><?=$_file['md5sum']?></td></tr>
            <?endforeach?>
            </tbody>
        </table>
    </fieldset>
</div>