<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="entry-edit">
    <h4 class="icon-head head-edit-form fieldset-legend"><?=$this->__("Dependencies")?></h4>
    <fieldset>
        <legend><?=$this->__("Dependencies")?></legend>
        <table class="" cellspacing="5">
            <thead><th><?=$this->__("Type")?></th><th><?=$this->__("Role")?></th><th><?=$this->__("Name")?></th><th><?=$this->__("Min")?></th><th><?=$this->__("Max")?></th><th><?=$this->__("Recommended")?></th><th><?=$this->__("Exclude")?></th></thead>
            <tbody>
            <?foreach ($this->getDepends() as $_dep):?>
                <tr><td><?=$_dep['type']?></td><td><?=$_dep['role']?></td><td><?=$_dep['name']?></td><td><?=$_dep['min']?></td><td><?=$_dep['max']?></td><td><?=$_dep['recommended']?></td><td><?=$_dep['exclude']?></td></tr>
            <?endforeach?>
            </tbody>
        </table>
    </fieldset>
</div>

<pre><?#print_r($this->getData('pkg'))?></pre>
