<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="entry-edit">
    <h4 class="icon-head head-edit-form fieldset-legend"><?=$this->__("Package Information")?></h4>
    <fieldset>
        <legend><?=$this->__("Package Information")?></legend>
        <table class="" cellspacing="5">
            <tbody>
                <tr><th><?=$this->__("Name:")?></th><td><?=$this->getPkg()->getPackage()?></td></tr>
                <tr><th><?=$this->__("Channel:")?></th><td><?=$this->getPkg()->getChannel()?></td></tr>
                <tr><th><?=$this->__("Summary:")?></th><td><?=$this->getPkg()->getSummary()?></td></tr>
                <tr><th><?=$this->__("Description:")?></th><td><?=nl2br($this->getPkg()->getDescription())?></td></tr>
            </tbody>
        </table>
    </fieldset>

    <h4 class="icon-head head-edit-form fieldset-legend"><?=$this->__("Current Release Information")?></h4>
    <fieldset>
        <legend><?=$this->__("Current Release Information")?></legend>
        <table class="" cellspacing="5">
            <tbody>
                <tr><th><?=$this->__("Date:")?></th><td><?=$this->getPkg()->getDate()?> <?=$this->getPkg()->getTime()?></td></tr>
                <tr><th><?=$this->__("Version:")?></th><td><?=$this->getPkg()->getVersion()?> (<?=$this->getPkg()->getState()?>)</td></tr>
                <tr><th><?=$this->__("API:")?></th><td><?=$this->getPkg()->getVersion('api')?> (<?=$this->getPkg()->getState('api')?>)</td></tr>
                <tr><th><?=$this->__("License:")?></th><td>
                    <?if ($_uri = $this->getPkg()->getLicenseLocation()):?>
                        <a href="<?=$_uri?>" target="_blank">
                    <?endif?>
                    <?=$this->getPkg()->getLicense()?>
                    <?if ($_uri):?>
                        </a>
                    <?endif?>
                </td></tr>
                <tr><th><?=$this->__("Notes:")?></th><td><?=nl2br($this->getPkg()->getNotes())?></td></tr>
            </tbody>
        </table>
    </fieldset>

    <h4 class="icon-head head-edit-form fieldset-legend"><?=$this->__("Maintainers")?></h4>
    <fieldset>
        <legend><?=$this->__("Maintainers")?></legend>
        <table class="" cellspacing="5">
            <thead><th><?=$this->__("Role")?></th><th><?=$this->__("Name")?></th><th><?=$this->__("User")?></th><th><?=$this->__("Email")?></th></thead>
            <tbody>
            <?foreach ($this->getPkg()->getMaintainers() as $_maint):?>
                <tr>
                    <td><?=$_maint['role']?>:</td>
                    <td><?=$_maint['name']?></td>
                    <td><?=$_maint['handle']?></td>
                    <td><?=$_maint['email']?></td>
                    <td><?if(empty($_maint['active']) || $_maint['active']!=='yes'):?>(<?=$this->__("Inactive")?>)<?endif?></td>
                </tr>
            <?endforeach?>
            </tbody>
        </table>
    </fieldset>
</div>