<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage_Rss
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="page-head">
    <h3><?=$this->__('RSS Feeds')?> <img src="<?=$this->getSkinUrl()?>images/icon_big_rss.png" class="v-middle" style="margin-bottom:3px;"/></h3>
</div>
<?
$_categories = $this->getRssCatalogFeeds();
$_misc = $this->getRssMiscFeeds();
?>
    <?if($_misc):?>
    <table cellspacing="0" class="data-table" id="rss-table-misc">
        <thead><tr><th>Miscellaneous Feeds</th></tr></thead>
        <tbody>
    <?foreach ($_misc as $_feed):?>
            <tr>
                <td class="a-right"><span class="left"><?=$_feed->getLabel()?></span><a href="<?=$_feed->getUrl()?>" class="link-feed"><?=$this->__('Get Feed');?></a></td>
            </tr>
    <?endforeach;?>
         </tbody>
    </table>
    <?endif;?>
    <?if ($_categories || $_misc):?><br/><?endif?>
    <?if($_categories):?>
    <table cellspacing="0" class="data-table" id="rss-table-category">
    <thead><tr><th>Category Feeds</th></tr></thead>
    <tbody>
    <?foreach ($_categories as $_category):?>
    <tr>
        <td class="a-right"><span class="left"><?=$_category->getLabel()?></span><a href="<?=$_category->getUrl()?>" class="link-feed"><?=$this->__('Get Feed');?></a></td>
    </tr>
    <?endforeach;?>
    </tbody>
</table>
<script type="text/javascript">decorateTable('rss-table-misc'); decorateTable('rss-table-category')</script>
<?else:?>
<p><?=$this->__('There are no %s.',$this->__('Rss Feeds'));?></p>
<?endif;?>
