<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<?$_productCollection=$this->getLoadedProductCollection()?>
<?if(!$_productCollection->getSize()):?>
<div class="note-msg">
    <?=$this->__('There are no products matching the selection.')?>
</div>
<?else:?>

<?=$this->getToolbarHtml()?>
<?// List mode?>
<?if($this->getMode()!='grid'):?>
<div class="listing-type-list catalog-listing">
<?foreach ($_productCollection as $_product):?>
    <div class="listing-item ">
        <?// Product Image?>
        <div class="product-image">
            <a href="<?=$_product->getProductUrl()?>" title="<?=$this->htmlEscape($_product->getName())?>">
                <img src="<?=$_product->getSmallImageUrl()?>" width="135" height="135" alt="<?=$this->htmlEscape($_product->getName())?>"/>
            </a>
        </div>

        <?// Product description?>
        <div class="product-shop">
            <h5><a href="<?=$_product->getProductUrl()?>" title="<?=$this->htmlEscape($_product->getName())?>"><?=$_product->getName()?></a></h5>
            <?=$this->helper('review/product')->getSummaryHtml($_product)?>
            <?=$this->helper('catalog/product')->getPriceHtml($_product)?>
            <?if($_product->isSaleable()):?>
            <button class="form-button" onclick="setLocation('<?=$this->getAddToCartUrl($_product)?>')"><span><?=$this->__('Add to Cart')?></span></button>
            <?endif;?>
            <div class="clear"></div>
            <div class="description">
                <?=$_product->getShortDescription()?>
                <a href="<?=$_product->getProductUrl()?>" title="<?=$this->htmlEscape($_product->getName())?>"><small><?=$this->__('Learn More')?></small></a>
            </div>
            <p class="add-to">
                <a href="<?=$this->getAddToWishlistUrl($_product)?>" class="link-cart"><?=$this->__('Add to Wishlist')?></a>
                <?if($_compareUrl=$this->getAddToCompareUrl($_product)):?>
                <span class="pipe">|</span>
                <a href="<?=$_compareUrl?>"><?=$this->__('Add to Compare')?></a>
                <?endif;?>
            </p>
        </div>
    </div>
<?endforeach;?>
</div>


<?else:?>

<?// Grid Mode?>
<div class="listing-type-grid  catalog-listing"> <!-- the class name will change to .listing-type-cell if viewing in list mode -->
<?$_collectionSize = $_productCollection->count()?>
    <table cellspacing="0" class="generic-product-grid" id="product-list-table">
    <?$i=0; foreach ($_productCollection as $_product):?>
    <?if ($i++%3==0):?>
    <tr>
    <?endif?>
        <td>
            <p class="product-image">
                <a href="<?=$_product->getProductUrl()?>" title="<?=$this->htmlEscape($_product->getName())?>">
                    <img src="<?=$_product->getSmallImageUrl()?>" width="135" height="135" alt="<?=$this->htmlEscape($_product->getName())?>"/>
                </a>
            </p>
            <h5><a href="<?=$_product->getProductUrl()?>" title="<?=$this->htmlEscape($_product->getName())?>)"><?=$_product->getName()?></a></h5>
            <?=$this->helper('review/product')->getSummaryHtml($_product, 'short')?>
            <?=$this->helper('catalog/product')->getPriceHtml($_product)?>
            <?if($_product->isSaleable()):?>
            <button class="form-button" onclick="setLocation('<?=$this->getAddToCartUrl($_product)?>')"><span><?=$this->__('Add to Cart')?></span></button>
            <?endif;?>
            <div class="clear"></div>
            <p class="add-to">
                <a href="<?=$this->getAddToWishlistUrl($_product)?>" class="link-cart"><?=$this->__('Add to Wishlist')?></a>
                <?if($_compareUrl=$this->getAddToCompareUrl($_product)):?><br/>
                <a href="<?=$_compareUrl?>"><?=$this->__('Add to Compare')?></a>
                <?endif;?>
            </p>
        </td>
    <?if ($i%3==0):?>
    </tr>
    <?endif?>
    <?endforeach?>
    <?for($i;$i%3!=0;$i++):?>
        <td class="empty-product">&nbsp;</td>
    <?endfor?>
    <?if ($i%3==0):?>
    </tr>
    <?endif?>
    </table>
    <script type="text/javascript">decorateTable('product-list-table')</script>
</div>

<?endif;?>
<?=$this->getToolbarHtml()?>
<?endif;?>