<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php $_product = $this->getProduct() ?>
<?php if (!$_product->isGrouped()): ?>
<div class="price-box">
<?php $_id = $_product->getId() ?>
<?php $_showTax = $_product->getShowTaxInCatalog() ?>
<?php $_priceAfterTax = $_product->getPriceAfterTax() ?>
<?php $_finalPriceAfterTax = $_product->getFinalPriceAfterTax() ?>
<?php $_price = $_showTax==1 ? $_priceAfterTax : $_product->getPrice() ?>
<?php $_finalPrice = $_showTax==1 ? $_finalPriceAfterTax : $_product->getFinalPrice() ?>

<?php if ($_finalPrice == $_price): ?>
    <span class="regular-price" id="product-price-<?php echo $_id ?>">
        <?php echo Mage::helper('core')->currency($_price) ?>
    </span>
    <br/>
<?php else: ?>
    <span class="old-price">
        <span class="label"><?php echo $this->__('Regular Price:') ?></span>
        <span class="price" id="old-price-<?php echo $_id ?>">
            <?php echo Mage::helper('core')->currency($_price) ?>
        </span>
    </span>
    <br/>
    <span class="special-price">
        <span class="label"><?php echo $this->__('Special Price:') ?></span>
        <span class="price" id="product-price-<?php echo $_id ?>">
            <?php echo Mage::helper('core')->currency($_finalPrice) ?>
        </span>
    </span>
    <br/>
<?php endif ?>

<?php if ($_showTax==2): ?>
    <span class="price-after-tax">
        <span class="label"><?php echo $this->__('Including Tax:') ?></span>
        <span class="regular-price" id="price-after-tax-<?php echo $_id ?>">
            <?php echo Mage::helper('core')->currency($_finalPriceAfterTax) ?>
        </span>
    </span>
    <br/>
<?php endif ?>

</div>
<?php endif; ?>