<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="price-box">
<?$_product = $this->getProduct()?>
<?$_id = $_product->getId()?>
<?$_showTax = $_product->getShowTaxInCatalog()?>
<?$_priceAfterTax = $_product->getPriceAfterTax()?>
<?$_finalPriceAfterTax = $_product->getFinalPriceAfterTax()?>
<?$_price = $_showTax==1 ? $_priceAfterTax : $_product->getPrice()?>
<?$_finalPrice = $_showTax==1 ? $_finalPriceAfterTax : $_product->getFinalPrice()?>

<?if ($_finalPrice == $_price):?>
    <span class="regular-price" id="product-price-<?=$_id?>">
        <?=Mage::helper('core')->currency($_price)?>
    </span>
    <br/>
<?else:?>
    <span class="old-price">
        <span class="label"><?=$this->__('Regular Price:')?></span>
        <span class="price" id="old-price-<?=$_id?>">
            <?=Mage::helper('core')->currency($_price)?>
        </span>
    </span>
    <br/>
    <span class="special-price">
        <span class="label"><?=$this->__('Special Price:')?></span>
        <span class="price" id="product-price-<?=$_id?>">
            <?=Mage::helper('core')->currency($_finalPrice)?>
        </span>
    </span>
    <br/>
<?endif?>

<?if ($_showTax==2):?>
    <span class="price-after-tax">
        <span class="label"><?=$this->__('Including Tax:')?></span>
        <span class="regular-price" id="price-after-tax-<?=$_id?>">
            <?=Mage::helper('core')->currency($_finalPriceAfterTax)?>
        </span>
    </span>
    <br/>
<?endif?>

</div>
