<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * Product view template
 *
 * @see Mage_Catalog_Block_Product_View
 */
?>
<div id="messages_product_view"><?=$this->getMessagesBlock()->getGroupedHtml()?></div>
<?$_product=$this->getProduct()?>
<div class="product-info-box">
    <div class="product-essential">

        <div class="product-img-box">
            <?=$this->getChildHtml('media')?>
        </div>

        <div class="product-shop">
            <h3 class="product-name"><?=$_product->getName()?></h3>

            <?if ($this->canEmailToFriend()):?>
                <a href="<?=$this->helper('catalog/product')->getEmailToFriendUrl($_product)?>"><?=$this->__('Email to a Friend')?></a><br />
            <?endif;?>

            <?=$this->helper('review/product')->getSummaryHtml($_product, null, 1)?>

            <form action="<?=$this->getAddToCartUrl($_product)?>" method="post" id="product_addtocart_form">
                <input type="hidden" name="product" value="<?=$_product->getId()?>"/>
                <input type="hidden" name="related_product" id="related-products-field" value=""/>

                <?=$this->getChildHtml('alert_urls')?>

                <?if ($_product->isGrouped()) :?>
                    <?=$this->getChildHtml('grouped_data')?>
                <?elseif ($_product->isConfigurable()): ?>
                    <?=$this->getChildHtml('configurable_data')?>
                <?else:?>
                    <?=$this->getChildHtml('simple_data')?>
                <?endif;?>

            </form>

            <script type="text/javascript">
                var productAddToCartForm = new VarienForm('product_addtocart_form');
                productAddToCartForm.submit = function() {
                    if(this.validator.validate()) {
                        this.form.submit();
                    }
                }.bind(productAddToCartForm);
            </script>

            <div class="clear"></div>
            <div class="divider"></div>

            <h4><?=$this->__('Quick Overview')?></h4>
            <div class="short-description"><?=$_product->getShortDescription()?></div>

        </div>
    </div>

    <div class="product-collateral">

        <div class="collateral-box">
            <div class="head">
                <h4><?=$this->__('Product Description')?></h4>
            </div>
            <div class="product-specs"><?=$_product->getDescription()?></div>
        </div>

        <?if($_additional = $this->getAdditionalData()):?>
        <div class="collateral-box attribute-specs">
            <div class="head">
                <h4><?=$this->__('Additional Information')?></h4>
            </div>
            <table cellspacing="0" class="data-table" id="product-attribute-specs-table">
            <?foreach ($_additional as $_data):?>
            <tr>
                <td class="label"><?=$_data['label']?></td>
                <td class="data"><?=$_data['value']?></td>
            </tr>
            <?endforeach;?>
            </table>
            <script type="text/javascript">decorateTable('product-attribute-specs-table')</script>
        </div>
        <?endif;?>

        <?=$this->getChildHtml('upsell_products')?>
        <?=$this->getChildHtml('product_additional_data')?>
    </div>
</div>