<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * Product view template
 *
 * @see Mage_Catalog_Block_Product_View
 */
?>
<div id="messages_product_view"><?=$this->getMessagesBlock()->getGroupedHtml()?></div>
<?$_product=$this->getProduct()?>
<div class="product-info-box">
    <div class="product-essential">
        <div class="product-img-box">
            <p class="main-product-img">
                <img id="image" src="<?=$_product->getImageUrl()?>" alt="<?=$_product->getName()?>"/>
            </p>
            <div class="image-zoom" id="track_outer">
                <img id="zoom_out" src="<?=$this->getSkinUrl('images/slider_btn_zoom_out.gif')?>" alt="<?=$this->__('Zoom Out')?>" class="btn-zoom-out"/>
                <div id="track">
                    <div id="handle"></div>
                </div>
                <img id="zoom_in" src="<?=$this->getSkinUrl('images/slider_btn_zoom_in.gif')?>" alt="<?=$this->__('Zoom In')?>" class="btn-zoom-in"/>
            </div>
            <script type="text/javascript">
                Event.observe(window, 'load', function() {
                    product_zoom = new Product.Zoom('image', 'track', 'handle', 'zoom_in', 'zoom_out');
                });
            </script>
        <?if ($this->getGalleryImages() && $this->getGalleryImages()->getSize()):?>
            <div class="more-views">
                <h4><?=$this->__('More Views')?></h4>
                <ul>
                <?foreach ($this->getGalleryImages() as $_image):?>
                    <li>
                        <a href="#" onclick="popWin('<?=$this->getGalleryUrl($_image)?>', 'gallery', 'scrollbars=yes,width=300,height=300,resizable=yes');return false;">
                            <img src="<?=$_image->setType(1)->getSourceUrl();?>" width="68" height="68" alt=""/>
                        </a>
                    </li>
                <?endforeach;?>
                </ul>
            </div>
       <?endif;?>
       </div>
       <div class="product-shop">
       <h3 class="product-name"><?=$_product->getName()?></h3>
            <?if ($this->canEmailToFriend()):?>
                <a href="<?=$this->helper('catalog/product')->getEmailToFriendUrl($_product)?>"><?=$this->__('Email to a Friend')?></a><br />
            <?endif;?>
            <?=$this->helper('review/product')->getSummaryHtml($_product, null, 1)?>
            <form action="<?=$this->getAddToCartUrl($_product)?>" method="post" id="product_addtocart_form">
            <input type="hidden" name="product" value="<?=$_product->getId()?>"/>
            <input type="hidden" name="related_product" id="related-products-field" value=""/>

            <?if($_product->isSuperConfig()):?>
                <?=$this->getChildHtml('super_config')?>
            <?endif;?>

            <?$_tierPrices = $this->getTierPrices($_product)?>
            <?if(count($_tierPrices)>0):?>
                <div class="product-pricing">
                    <ul class="bare">
                    <?foreach($_tierPrices as $_price):?>
                        <li><?=$this->__('Buy %s for %s each', $_price['price_qty'], $_price['formated_price'])?>
                        <?if(($_product->getPrice() == $_product->getFinalPrice() && $_product->getPrice() > $_price['price'])
                        || ($_product->getPrice() != $_product->getFinalPrice() &&  $_product->getFinalPrice() > $_price['price'])):?>
                            <?=$this->__('and')?> <strong><?=$this->__('save %s%%', $_price['savePercent'])?>
                        <?endif?></strong>
                        </li>
                    <?endforeach?>
                    </ul>
                </div>
            <?endif;?>

            <?if($_product->isSuperGroup()):?>
                <?=$this->getChildHtml('super_group')?>
            <?endif;?>

            <?if(!$_product->isSuperGroup()):?>
                <?if($_product->isSaleable()):?>
                <p><small><?=$this->__('Availability: In stock.')?></small></p>
                <?else:?>
                <p><small><?=$this->__('Availability: Out of stock.')?></small><br />
                <?//=$this->getAlertHtml('product_back_stock');?></p>
                <?endif;?>
                <?//=$this->getAlertHtml('price_is_changed');?>
                <?=$this->helper('catalog/product')->getPriceHtml($_product)?>

                <?if($_product->isSaleable()):?>
                <fieldset class="add-to-cart-box">
                    <legend><?=$this->__('Add Items to Cart')?></legend>
                    <span class="qty-box"><label for="qty"><?=$this->__('Qty')?>:</label>
                    <input name="qty" type="text" class="input-text qty" id="qty" maxlength="12" value="<?=$this->getMinimalQty($_product)?>"/></span>
                    <button class="form-button" onclick="productAddToCartForm.submit()"><span><?=$this->__('Add to Cart')?></span></button>
                    <?if( $this->helper('wishlist')->isAllow() || $_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product)):?>
                        <strong><?=$this->__('OR')?></strong>
                    <?endif;?>
                </fieldset>
                <?endif;?>

                <div class="add-to-box">
                <?if ($this->helper('wishlist')->isAllow()) :?>
                    <a href="<?=$this->getAddToWishlistUrl($_product)?>"><?=$this->__('Add to Wishlist')?></a><br/>
                <?endif;?>

                <?if($_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product) ):?>
                <a href="<?=$_compareUrl?>"><?=$this->__('Add to Compare')?></a>
                <?endif;?>
                </div>

            <?else:?>
                <p><small><?=$this->__('Availability: In stock.')?></small></p>
                <?if($_product->isSaleable() && $_product->getSuperGroupProductsLoaded()->getSize()):?>
                <button class="form-button" onclick="productAddToCartForm.submit()"><span><?=$this->__('Add to Cart')?></span></button> <strong><?=$this->__('OR')?></strong>
                &nbsp;&nbsp;
                <?endif;?>
                <?if ($this->helper('wishlist')->isAllow()) :?>
                <a href="<?=$this->getAddToWishlistUrl($_product)?>"><?=$this->__('Add to Wishlist')?></a>
                <?endif;?>
                <?if($_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product)):?>
                <span class="pipe">|</span>
                <a href="<?=$_compareUrl?>"><?=$this->__('Add to Compare')?></a>
                <?endif;?>
            <?endif;?>
            </form>
            <script type="text/javascript">
                var productAddToCartForm = new VarienForm('product_addtocart_form');
                productAddToCartForm.submit = function() {
                    if(this.validator.validate()) {
                        this.form.submit();
                    }
                }.bind(productAddToCartForm);
            </script>
            <div class="clear"></div>
            <div class="divider"></div>
           <h4><?=$this->__('Quick Overview')?></h4>
           <div class="short-description"><?=$_product->getShortDescription()?></div>
        </div>
    </div>
        <div class="product-collateral">
        <div class="collateral-box">
            <div class="head">
                <h4><?=$this->__('Product Description')?></h4>
            </div>
            <div class="product-specs"><?=$_product->getDescription()?></div>
        </div>

        <?if($_additional = $this->getAdditionalData()):?>
        <div class="collateral-box attribute-specs">
            <div class="head">
                <h4><?=$this->__('Additional Information')?></h4>
            </div>
            <table cellspacing="0" class="data-table" id="product-attribute-specs-table">
            <?foreach ($_additional as $_data):?>
            <tr>
                <td class="label"><?=$_data['label']?></td>
                <td class="data"><?=$_data['value']?></td>
            </tr>
            <?endforeach;?>
            </table>
            <script type="text/javascript">decorateTable('product-attribute-specs-table')</script>
        </div>
        <?endif;?>
        <?=$this->getChildHtml('upsell_products')?>
        <?=$this->getChildHtml('product_additional_data')?>

    </div>
</div>