<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="switcher" style="margin-bottom:10px;">
    <label for="store_switcher"><?=$this->__('Current Configuration Scope:')?></label>
    <select id="store_switcher" class="system-config-store-switcher" onchange="location.href=this.options[this.selectedIndex].getAttribute('url')">
    <?foreach ($this->getStoreSelectOptions() as $_value=>$_option):?>
    <?if (isset($_option['is_group'])):?>
        <?if ($_option['is_close']):?>
            </optgroup>
        <?else:?>
            <optgroup label="<?=$_option['label']?>" style="<?=$_option['style']?>">
        <?endif;?>
        <?continue?>
    <?endif;?>
      <option value="<?=$_value?>" url="<?=$_option['url']?>" <?=$_option['selected']?'selected':''?> style="<?=$_option['style']?>">
          <?=$_option['label']?>
      </option>
    <?endforeach?>
    </select>
    <div style="margin-top:10px;">
        <a href="<?=$this->getUrl('*/system_store')?>"><?=$this->__('Manage Stores')?></a>
    </div>
</div>

<?if($this->getTitle()):?>
    <h3><?=$this->getTitle()?></h3>
<?endif?>
<?if($this->getTabs()):?>
<ul id="<?=$this->getId()?>" class="tabs config-tabs">
<?foreach ($this->getTabs() as $_tab):?>
    <?if($_tab->getSections()):?>
    <li <?if ($_tab->getClass()):?>class="<?=$_tab->getClass()?>"<?endif?>>
        <dl>
        <dt class="label" style=""><?=$_tab->getLabel()?></dt>
        <?$_iterator = 1;?>
        <?foreach ($_tab->getSections() as $_section):?>
            <dd>
                <a href="<?=$_section->getUrl()?>" class="<?=$_section->getClass()?><?if($_section->getId()==$this->getActiveSection()):?> active<?endif?> <?=$_section->getIsLast()?'last':''?>">
                    <span <?if($_tab->getId()==$this->getActiveTab()):?>class="active"<?endif?>>
                        <?=$_section->getLabel()?>
                    </span>
                </a>
            </dd>
            <?$_iterator++ ;?>
        <?endforeach;?>
        </dl>
    </li>
    <?endif;?>
<?endforeach;?>
</ul>
<?endif;?>
