<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?if ($this->isShow()):?>
<p class="switcher"><label for="store_switcher"><?=$this->__('Show Report for')?>:</label>
<select name="store_switcher" id="store_switcher" class="left-col-block" onchange="return switchStore(this);">
    <option value=""><?=$this->__('All Websites')?></option>
    <?foreach ($this->getWebsiteCollection() as $_website):?>
        <?$showWebsite=false;?>
        <?foreach ($this->getGroupCollection($_website) as $_group):?>
            <?$showGroup=false;?>
            <?foreach ($this->getStoreCollection($_group) as $_store):?>
                <?if ($showWebsite == false):?>
                    <?$showWebsite = true;?>
                    <option website="true" value="<?=$_website->getId()?>"<?if($this->getRequest()->getParam('website') == $_website->getId()):?> selected<?endif;?>><?=$_website->getName()?></option>
                <?endif;?>
                <?if ($showGroup == false):?>
                    <?$showGroup = true;?>
                    <!--optgroup label="&nbsp;&nbsp;&nbsp;<?=$_group->getName()?>"-->
                    <option group="true" value="<?=$_group->getId()?>"<?if($this->getRequest()->getParam('group') == $_group->getId()):?> selected<?endif;?>>&nbsp;&nbsp;&nbsp;<?=$_group->getName()?></option>
                <?endif;?>
                <option value="<?=$_store->getId()?>"<?if($this->getStoreId() == $_store->getId()):?> selected<?endif;?>>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?=$_store->getName()?></option>
            <?endforeach;?>
            <?if ($showGroup):?>
                </optgroup>
            <?endif;?>
        <?endforeach;?>
    <?endforeach;?>
</select>
</p>
<script type="text/javascript">
    function switchStore(obj){
        if (obj.options[obj.selectedIndex].getAttribute('website') == 'true') {
            var selectionType = 'website';
        } else if (obj.options[obj.selectedIndex].getAttribute('group') == 'true') {
            var selectionType = 'group';
        } else {
            var selectionType = 'store';
        }
        var storeParam = obj.value ? selectionType + '/' + obj.value + '/' : '';
        if(obj.switchParams){
            storeParam+= obj.switchParams;
        }
        setLocation('<?=$this->getSwitchUrl()?>'+storeParam);
    }
</script>
<?endif;?>