<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<dl id="dl-<?=$id?>" class="accordion">
<?foreach ($sections as $sectionId=>$section):?>
    <dt id="dt-<?=$id?>-<?=$sectionId?>">
        <a href="javascript:void(0)" onclick="$('dd-<?=$id?>-<?=$sectionId?>')?>">
            <img src="<?=$this->getSkinUrl('images/accordion_'.(!empty($section['active'])?'open':'closed').'.png')?>" alt="" class="v-mid"/>
        </a>
        <strong><?=$section['title']?></strong>
    </dt>
    <dd id="dd-<?=$id?>-<?=$section['id']?>" class="section-menu <?=!empty($section['active'])?'open':''?>">
        <ul>
        <?foreach ($section['children'] as $menuId=>$menuItem):?>
            <li id="li-<?=$id?>-<?=$sectionId?>-<?=$menuId?>">
                <a href="#" title="<?=$menuItem['title']?>">
                    <span><?=$menuItem['label']?></span>
                </a>
            </li>
        <?endforeach?>
        </ul>
    </dd>
<?endforeach?>
</dl>