<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

    <div class="page-head">
        <h3><?=$this->__('Edit Tag')?></h3>
    </div>
    <p>
        <form name="addTagForm" id="addTagForm" action="<?=$this->getFormAction();?>"  method="post">
            <input type="text" class="input-text required-entry" style="width:300px;" name="tagName" value="<?=$this->getTag()->getName()?>" />
            <button class="form-button-alt" onclick="tagForm.submit();"><span><?=$this->__('Save Tag')?></span></button>
        </form>
    </p>
    <script type="text/javascript">
        var tagForm = new VarienForm('addTagForm');
    </script>