<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="account-box ad-tags">
    <div class="head">
            <h4><?=$this->__('My Recent Tags')?></h4>
            <a href="<?=$this->getAllTagsUrl()?>"><?=$this->__('View All Tags')?></a>
    </div>
    <ol>
        <?$iterator = 0?>
        <?foreach( $this->getCollection()->getItems() as $_item ):?>
            <li <?if($iterator % 2 == 0):?>class="odd"<?else:?>class="even"<?endif;?>>
                <div class="count"><?=++$iterator?></div>
                <div class="content">
                    <a href="<?=$_item->getProductUrl()?>"><?=$_item->getName()?></a><br/>
                    <strong><?=$this->__('Tags:')?></strong>
                        <?$_i = 0;?>
                        <?foreach( $_item->getProductTags() as $_tag ):?>
                            <a href="<?=$_tag->getViewTagUrl()?>"><?=$_tag->getName()?></a><?if(++$_i != sizeof($_item->getProductTags()->getItems())):?>,<?endif;?>
                        <?endforeach;?>
                </div>
            </li>
        <?endforeach;?>
    </ol>
</div>
