<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="account-box">
    <div class="page-head">
        <h3><?=$this->__('My Tags')?></h3>
    </div>
    <?=$this->getMessagesBlock()->getGroupedHtml()?>
    <p>
        <?=$this->__('Tag Name: %s', $this->getTagInfo()->getName())?></strong> ( <a href="<?=$this->getTagInfo()->getEditTagUrl();?>"><small><?=$this->__('Edit Tag')?></small></a><span class="separator">|</span><a href="<?=$this->getTagInfo()->getRemoveTagUrl();?>" onclick="return confirm('<?=$this->__('Are you sure you want to delete this tag?')?>');"><?=$this->__('Delete Tag')?></a> )
    </p>
    <?=$this->getToolbarHtml()?>
    <table class="data-table box-table" id="my-tags-table" cellspacing="0">
    <?if( sizeof($this->getMyProducts()) > 0 ):?>
        <col width="100">
        <col>
        <col width="75">
        <tbody>
        <?$iterator = 0?>
        <?foreach($this->getMyProducts() as $_product):?>
            <tr <?if($iterator % 2 == 0):?>class="odd"<?$iterator++;endif;?>>
                <td><a href="<?=$_product->getProductUrl();?>"><img src="<?=$_product->getSmallImageUrl()?>" alt="" height="100" width="100"></a></td>
                <td>

                    <h5><a href="<?=$_product->getProductUrl()?>"><?=$_product->getName()?></a></h5>
                    <?=$this->helper('catalog/product')->getPriceHtml($_product)?>
                    <?=$this->helper('review/product')->getSummaryHtml($_product, 'short')?>
                    <p><?=$_product->getDescription()?></p>
                </td>
                <td class="a-center">
                    <button class="form-button" onclick="setLocation('<?=$this->getUrl('checkout/cart/add',array('product'=>$_product->getId()))?>')"><span><?=$this->__('Add to Cart')?></span></button>
                    <?if ($this->helper('wishlist')->isAllow()) :?>
                    <br><a href="<?=$this->getUrl('wishlist/index/add',array('product'=>$_product->getId()))?>"><?=$this->__('Add to Wishlist')?></a>
                    <?endif;?>
                </td>
            </tr>
        <?endforeach;?>
        </tbody>
    <?else:?>
            <tr>
            <td><p><?=$this->__("Unable to find any products tagged with '%s' in the current store", $this->getTagInfo()->getName() )?></p></td>
            </tr>
    <?endif;?>
    </table>
    <script type="text/javascript">decorateTable('my-tags-table')</script>
    <?=$this->getToolbarHtml()?>
</div>
