<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   default_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?if ($_products = $this->getProducts()):?>
<p><?=$this->__('You are receiving this notification because you subscribed to receive alerts when the following products are back in stock:')?></p>
<p><table>
<?foreach ($_products as $_product):?>
    <tr>
        <td><a href="<?=$_product->getProductUrl()?>"><img src="<?=$_product->getThumbnailUrl()?>" border="0" align="left" height="75" width="75"></a></td>
        <td>
            <div><a href="<?=$_product->getProductUrl()?>"><b><?=$_product->getName()?></b></a></div>
            <?if ($shortDescription = $_product->getShortDescription()):?>
            <p><small><?=$shortDescription?></small></p>
            <?endif;?>
            <p><b><?=$this->__('Price:')?></b> <?=Mage::helper('core')->currency($_product->getPrice())?>
            <?if ($_product->getPrice() != $_product->getFinalPrice()):?>
            <br /><b><?=$this->__('Special price:')?></b> <font color="red"><?=Mage::helper('core')->currency($_product->getFinalPrice())?></font>
            <?endif;?></p>
            <p><small><a href="<?=$this->getProductUnsubscribeUrl($_product->getId())?>"><?=$this->__('Click here not to receive alerts for this product')?></a></small></p>
        </td>
    </tr>
<?endforeach;?>
</table>
<p><a href="<?=$this->getUnsubscribeUrl()?>"><?=$this->__('Unsubscribe from all price alerts')?></a></p>
<?endif;?>