<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?
/**
 * Category left navigation
 * 
 * @see Mage_Catalog_Block_Navigation
 */
?>
<?$_categories=$this->getCurrentChildCategories()?>
<?if($_categories->count()):?>
<div class="box layered-nav">
        <div class="head">
            <h3><?=$this->__('Browse By')?></h3>
        </div>
        <div class="border-creator">
        <div class="narrow-by">
                                <dl id="narrow-by-list">
                <dt><?=$this->__('Category')?></dt>
                <dd>
                    <ol>
                    <?foreach ($_categories as $_category):?>
                        <?if($_category->getIsActive()):?>
                        <li>
                            <a href="<?=$this->getCategoryUrl($_category)?>"<?if ($this->isCategoryActive($_category)):?> class="active"<?endif?>><?=$_category->getName()?></a> (<?=$_category->getProductCount()?>)
                        </li>
                        <?endif;?>
                    <?endforeach?>
                    </ol>
                </dd>
                                </dl><script type="text/javascript">decorateDataList('narrow-by-list')</script>
                            </div>
                        </div>
                    </div>
<?endif;?>
<!-- [ends] .browse-by // -->
