<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?
/**
 * Top menu for store
 *
 * @see Mage_Catalog_Block_Navigation
 */
?>
<div class="header-nav-container">
    <div class="header-nav">
        <h4 class="no-show"><?=$this->__('Category Navigation:')?></h4>
        <ul id="nav">
        <?foreach ($this->getStoreCategories(10) as $_category):?>
            <?=$this->drawItem($_category)?>
        <?endforeach?>
			<li>
        </ul>
    </div>



    <?=$this->getChildHtml('topLeftLinks')?>




</div>