<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?$_order = $this->getOrder()?>
<!--<div class="page-head button-level">
    <h2><?=$this->__('Refunds')?></h2>
    <button class="form-button" onclick="window.print();"><span><?=$this->__('Print All Refunds')?></span></button>
</div>-->
<h3><?=$this->__('Order #%s', $_order->getRealOrderId())?></h3>
<?$_creditmemo = $this->getCreditmemo()?>
<?if($_creditmemo):?>
    <?$_creditmemos = array($_creditmemo);?>
<?else:?>
    <?$_creditmemos = $_order->getCreditmemosCollection()?>
<?endif;?>
<?foreach ($_creditmemos as $_creditmemo):?>
    <div class="divider"></div>
    <div class="head">
        <h3><?=$this->__('Refund #%s', $_creditmemo->getIncrementId())?></h3>
        <!--<a href="#"><?=$this->__('Print Invoice')?></a>-->
    </div>
    <div class="col2-set">
        <div class="col-1">
            <h4><?=$this->__('Shipping Address')?></h4>
            <?$_shipping = $_creditmemo->getShippingAddress()?>
            <address><?=$_shipping->getFirstname()?> <?=$_shipping->getLastname()?><br/>
            <?=$_shipping->getCompany()?><br/>
            <?=$_shipping->getStreet()?><br/>
            <?=$_shipping->getCity()?>, <?=$_shipping->getRegion()?> <?=$_shipping->getPostcode()?><br/>
            <strong>T</strong> | <?=$_shipping->getTelephone();
            if ($_shipping->getFax()):?><br /><strong>F</strong> | <?=$_shipping->getFax()?><?endif;?></address>
        </div>
        <div class="col-2">
            <h4><?=$this->__('Billing Address')?></h4>
            <?$_billing = $_creditmemo->getbillingAddress()?>
            <address><?=$_order->getBillingAddress()->format('html')?></address>
        </div>
    </div>
    <br/>
    <div class="col2-set">
        <div class="col-1">
            <h4><?=$this->__('Shipping Method')?></h4>
             <?=$_order->getShippingDescription()?>
        </div>
        <div class="col-2">
            <h4><?=$this->__('Payment Method')?></h4>
            <?=$this->getPaymentInfoHtml()?>
        </div>
    </div>
    <br/>
    <h4><?=$this->__('Items Ordered')?></h4>
    <table cellspacing="0" class="data-table" id="my-orders-table">
    <thead>
        <tr>
            <th><?=$this->__('Product Name')?></th>
            <th width="10%"><?=$this->__('SKU')?></th>
            <th width="10%"><?=$this->__('Price')?></th>
            <th class="a-center" width="5%"><?=$this->__('Qty')?></th>
            <th><?=$this->__('Subtotal')?></th>
            <th class="wrap" width="7%"><?=$this->__('Tax Amount')?></th>
            <th class="wrap" width="7%"><?=$this->__('Discount Amount')?></th>
            <th class="wrap"><?=$this->__('Row Total')?></th>
        </tr>
    </thead>
    <tbody>
        <?$_items = $_creditmemo->getAllItems();?>
        <?$_count = count($_items);?>
        <?$_index = 0;?>
        <?foreach ($_items as $_item):?>
            <tr <?=($_index++ > $_count ? ' class="last"' : '')?> id="order-item-row-<?=$_item->getId()?>">
                <td>
                    <?=$_item->getName()?>
                    <?=$_item->getDescription()?>
                </td>
                <td><?=$_item->getSku()?></td>
                <td class="a-right nowrap"><?=$_order->formatPrice($_item->getPrice())?> </td>
                <td><?=$_item->getQty()*1?></td>
                <td class="a-right"><?=$_order->formatPrice($_item->getRowTotal())?></td>
                <td class="a-right"><?=$_order->formatPrice($_item->getTaxAmount())?></td>
                <td class="a-right"><?=$_order->formatPrice(-$_item->getDiscountAmount())?></td>
                <td class="last a-right nowrap">
                    <?=$_order->formatPrice($_item->getRowTotal()-$_item->getDiscountAmount()+$_item->getTaxAmount())?>
                </td>
            </tr>
        <?endforeach;?>

    </tbody>
    <tfoot>
            <?if ((float) $_creditmemo->getSubtotal()):?>
        <tr>
            <td colspan="7" class="a-right"><?=$this->__('Subtotal')?></td>
            <td class="last a-right"><?=$_order->formatPrice($_creditmemo->getSubtotal())?></td>
        </tr>
        <?endif;?>
        <?if ((float) $_creditmemo->getTaxAmount()):?>
        <tr>
            <td colspan="7" class="a-right"><?=$this->__('Tax')?></td>
            <td class="last a-right"><?=$_order->formatPrice($_creditmemo->getTaxAmount())?></td>
        </tr>
        <?endif;?>

        <?if ((float) $_creditmemo->getShippingAmount() || $_creditmemo->getShippingDescription()):?>
        <tr>
            <td colspan="7" class="a-right"><?=$this->__('Shipping')?></td>
            <td class="last a-right"><?=$_order->formatPrice($_creditmemo->getShippingAmount())?></td>
        </tr>
        <?endif;?>
        <?if ((float) $_creditmemo->getDiscountAmount()):?>
        <tr>
            <td colspan="7" class="a-right"><?=$this->__('Discount')?></td>
            <td class="last a-right"><?=$_order->formatPrice(-$_creditmemo->getDiscountAmount())?></td>
        </tr>
        <?endif;?>

        <?if ((float) $_creditmemo->getGiftcertAmount()):?>
        <tr>
            <td colspan="7" class="a-right"><?=$this->__('Gift Certificate')?></td>
            <td class="last a-right"><?=$_order->formatPrice($_creditmemo->getGiftcertAmount())?></td>
        </tr>
        <?endif;?>

        <?if ((float) $_creditmemo->getAdjustmentPositive()):?>
        <tr>
            <td colspan="7" class="a-right"><?=$this->__('Adjustment Refund')?></td>
            <td class="last a-right"><?=$_order->formatPrice($_creditmemo->getAdjustmentPositive())?></td>
        </tr>
        <?endif;?>

        <?if ((float) $_creditmemo->getAdjustmentNegative()):?>
        <tr>
            <td colspan="7" class="a-right"><?=$this->__('Adjustment Fee')?></td>
            <td class="last a-right"><?=$_order->formatPrice($_creditmemo->getAdjustmentNegative())?></td>
        </tr>
        <?endif;?>
         <tr>
            <td colspan="7" class="a-right">
                <strong><?=$this->__('Grand Total')?></strong>
            </td>
            <td class="last a-right">
                <strong><?=$_order->formatPrice($_creditmemo->getGrandTotal())?></strong>
            </td>
        </tr>
        <?if ($this->getCanDisplayTotalPaid()):?>
        <tr>
            <td colspan="7" class="a-right">
                <strong><?=$this->__('Total Paid')?></strong>
            </td>
            <td class="last a-right">
                <strong><?=$_order->formatPrice($_creditmemo->getTotalPaid())?></strong>
            </td>
        </tr>
        <?endif;?>
        <?if ($this->getCanDisplayTotalRefunded()):?>
        <tr>
            <td colspan="7" class="a-right">
                <strong><?=$this->__('Total Refunded')?></strong>
            </td>
            <td class="last a-right">
                <strong><?=$_order->formatPrice($_creditmemo->getTotalRefunded())?></strong>
            </td>
        </tr>
        <?endif;?>
        <?if ($this->getCanDisplayTotalDue()):?>
        <tr>
            <td colspan="7" class="a-right">
                <strong><?=$this->__('Total Due')?></strong>
            </td>
            <td class="last a-right">
                <strong><?=$_order->formatPrice($_creditmemo->getTotalDue())?></strong>
            </td>
        </tr>
        <?endif;?>
    </tfoot>
</table>
    <br/>
<?endforeach;?>
<script type="text/javascript">window.print();</script>