<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
            <td style="width:50%;">
                <h3>
                  <?if($this->getUser()->getUserId()):?>
                  <?$_userName = $this->getUser()->getFirstname() . ' ' . $this->getUser()->getLastname()?>
                  <?=$this->__("Edit User '%s'", $_userName)?>
                  <?else:?>
                  <?=$this->__('Add New User')?>
                  <?endif;?>
                </h3>
            </td>
            <td class="form-buttons">
            <?=$this->getBackButtonHtml()?>
            <?=$this->getResetButtonHtml()?>
            <?=$this->getDeleteButtonHtml()?>
            <?=$this->getSaveButtonHtml()?>
   </table>
</div>
<form action="<?=$this->getUrl('*/*/saveuser')?>" method="POST" id="user_edit_form">
</form>
<script type="text/javascript" language="javascript">
    var userForm = new varienForm('user_edit_form');
</script>