<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<input type="hidden" id="<?=$this->getId()?>_raw_options" name="_options_json">
<table cellspacing="0" width="100%">
    <tr>
        <td class="content-left-nav">
			<ul id="<?=$this->getId()?>" class="tabs">
				<li>
					<a href="#" id="<?=$this->getId()?>_options" title="<?=Mage::helper('catalog')->__('Options')?>" class="option-item-link">
						<span><div class="changed" title="<?=Mage::helper('catalog')->__('The information in this tab has been changed.')?>"></div><div class="error" title="<?=Mage::helper('catalog')->__('This tab contains invalid data. Please solve the problem before saving.')?>"></div><div class="option-label-text"><?=Mage::helper('catalog')->__('Options')?></div></span>
					</a>
					<div id="<?=$this->getId()?>_options_content" style="display:none">
						<?=$this->getChildHtml('option_form')?>
					</div>
				</li>
			</ul>
			<ul id="<?=$this->getId()?>_template" class="no-display">
				<li>
					<a href="_url_" id="_id_" title="#{label}" class="option-item-link">
						<span><div class="changed" title="<?=Mage::helper('catalog')->__('The information in this tab has been changed.')?>"></div><div class="error" title="<?=Mage::helper('catalog')->__('This tab contains invalid data. Please solve the problem before saving.')?>"></div><div class="option-label-text">#{label}</div></span>
					</a>
					<div id="_id__content" style="display:none">#{content}</div>
				</li>
			</ul>
        </td>
        <td>
            <div class="content" id="<?=$this->getId()?>_destanation">
            	
            </div>
        </td>
    </tr>
</table>
<script>
var <?=$this->getTabJsObjectName()?> = new Bundle.Tabs('<?=$this->getId()?>','<?=$this->getId()?>_destanation','<?=$this->getId()?>_options','<?=$this->getId()?>_template');
var <?=$this->getJsObjectName()?> = new Bundle.Options('<?=$this->getJsContainerHtmlId()?>',<?=$this->getTabJsObjectName()?>,'<?=$this->getUrl('*/*/bundle')?>', '<?=$this->getId()?>_raw_options', '<?=$this->getJsTemplateHtmlId()?>');
<?=$this->getJsObjectName()?>.jsController = '<?=$this->getJsObjectName()?>';
<?=$this->getJsObjectName()?>.optionLabelNewText = '<?=Mage::helper('catalog')->__('Option')?> ';
<?foreach ($this->getBundleOptions() as $_option):?>
<?=$this->getJsObjectName()?>.addItem('<?=$_option->getId()?>','<?=$this->getEscaped($_option->getLabel())?>','<?=$_option->getPosition()?>',<?=$this->getOptionProductsJSON($_option)?>);
<?endforeach;?>
</script>
